### ISSUE TITLE
[BUG] NullPointerException with option -ultra

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apim-cli#12]
**API-Mgr. CLI version**
1.0

**API-Manager and Service-Pack Version**
7.6.2 SP4

**Expected behavior**

**Actual behavior**
With OrgAdmin credentials, if I run apim api get ... with the option -ultra, I am getting a NullPointerException
It works fine with -wide!

**Log-Output in Debug**
```
java.lang.NullPointerException
        at com.axway.apim.api.export.impl.ConsoleAPIExporter.getOrgCount(ConsoleAPIExporter.java:141)
        at com.axway.apim.api.export.impl.ConsoleAPIExporter.lambda$printUltra$22(ConsoleAPIExporter.java:80)
        at com.github.freva.asciitable.ColumnData.getCellValue(ColumnData.java:15)
        at com.github.freva.asciitable.AsciiTable.lambda$null$0(AsciiTable.java:40)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
        at com.github.freva.asciitable.AsciiTable.lambda$getTable$2(AsciiTable.java:41)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
        at com.github.freva.asciitable.AsciiTable.getTable(AsciiTable.java:42)
        at com.axway.apim.api.export.impl.ConsoleAPIExporter.printUltra(ConsoleAPIExporter.java:70)
        at com.axway.apim.api.export.impl.ConsoleAPIExporter.execute(ConsoleAPIExporter.java:41)
        at com.axway.apim.APIExportApp.runExport(APIExportApp.java:98)
        at com.axway.apim.APIExportApp.export(APIExportApp.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:138)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:76)
```

**Test case sample**
> Please describe the steps you have done to replicate the issue

**Comment by cwiechmann** [comment]
@jschaefer77, thanks for reporting this issue!
