### ISSUE TITLE
AppException during upgrade of a published API as orgadmin

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apim-cli#125]
**API-Mgr. CLI version**
1.3.3

**API-Manager and Service-Pack Version**
7.7.20200730

**Expected behavior**
Supress Exceptions during API upgrade as OrgAdmin

**Actual behavior**
uncaught AppException.

**Log-Output in Debug**
3299   INFO        RollbackAction| Rollback FE-API: 'Petstore API 2' (ID: '82e3afcd-6adf-4919-8e4b-673ed5ceb3f7' / State: 'unpublished')
3381   ERROR APIManagerAPIAdapter| Error updating API status. Received Status-Code: 403, Response: '{"errors":[{"code":403,"message":"Forbidden"}]}'
3383   ERROR       RollbackAction| Error while deleting FE-API to roll it back
com.axway.apim.lib.errorHandling.AppException: The status change from: 'unpublished' to 'unpublished' is not possible!
        at com.axway.apim.adapter.APIStatusManager.update(APIStatusManager.java:152)
        at com.axway.apim.adapter.APIStatusManager.update(APIStatusManager.java:63)
        at com.axway.apim.apiimport.rollback.RollbackAPIProxy.rollback(RollbackAPIProxy.java:28)
        at com.axway.apim.apiimport.rollback.RollbackHandler.executeRollback(RollbackHandler.java:60)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:111)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.axway.apim.lib.errorHandling.AppException: Cannot update API-Proxy status.
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.updateAPIStatus(APIManagerAPIAdapter.java:655)
        at com.axway.apim.adapter.APIStatusManager.update(APIStatusManager.java:135)
        ... 11 more
Caused by: com.axway.apim.lib.errorHandling.AppException: Error updating API status. Received Status-Code: 403
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.updateAPIStatus(APIManagerAPIAdapter.java:652)
        ... 12 more
3440   ERROR APIManagerAPIAdapter| Error deleting Backend-API. Response-Code: 403, Response: '{"errors":[{"code":403,"message":"Cannot delete an API that has been virtualized."}]}'
3442   ERROR       RollbackAction| Error while deleting BE-API with ID: '3a37e0f5-fb52-4224-86f1-4313cd2d9bb2' to roll it back
com.axway.apim.lib.errorHandling.AppException: Cannot delete Backend-API.
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.deleteBackendAPI(APIManagerAPIAdapter.java:610)
        at com.axway.apim.apiimport.rollback.RollbackBackendAPI.rollback(RollbackBackendAPI.java:24)
        at com.axway.apim.apiimport.rollback.RollbackHandler.executeRollback(RollbackHandler.java:60)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:111)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.axway.apim.lib.errorHandling.AppException: Error deleting Backend-API. Response-Code: 403
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.deleteBackendAPI(APIManagerAPIAdapter.java:607)
        ... 10 more
3447   INFO       RollbackHandler| Rolled back: '[Frontend-API: false, Backend-API: false]'
3448   ERROR         APIImportApp| The status change from: 'published' to 'published' is not possible!
com.axway.apim.lib.errorHandling.AppException: The status change from: 'published' to 'published' is not possible!
        at com.axway.apim.adapter.APIStatusManager.update(APIStatusManager.java:152)
        at com.axway.apim.adapter.APIStatusManager.update(APIStatusManager.java:72)
        at com.axway.apim.apiimport.actions.CreateNewAPI.execute(CreateNewAPI.java:65)
        at com.axway.apim.apiimport.APIImportManager.applyChanges(APIImportManager.java:50)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:103)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.axway.apim.lib.errorHandling.AppException: Cannot update API-Proxy status.
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.updateAPIStatus(APIManagerAPIAdapter.java:655)
        at com.axway.apim.adapter.APIStatusManager.update(APIStatusManager.java:135)
        ... 11 more
Caused by: com.axway.apim.lib.errorHandling.AppException: Error updating API status. Received Status-Code: 200
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.updateAPIStatus(APIManagerAPIAdapter.java:652)
        ... 12 more

**Test case sample**
As OrgAdmin, try to update a published API. As expected, the CLI creates a new backend and frontend API and triggers the publication approval process. The result in API Manager is fine, but there is now always an uncaught AppException in the console output.

**Comment by cwiechmann** [comment]
Looks like another duplicate to issue: #134 - Also here it's stated:
`... Exception: Error updating API status. Received Status-Code: 200`

**Comment by cwiechmann** [comment]
The following 403 error message originates from the fact that the status code 200 was considered an error.
