### ISSUE TITLE
State change from unpublished to published throws AppException

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apim-cli#133]
**API-Mgr. CLI version**
1.3.3

**API-Manager and Service-Pack Version**
7.7.20200730

**Expected behavior**
With a state change in the API config file from unpublished to published, the API should be published without an AppException in the CLI output with the next "apim import ..." run.

**Actual behavior**
API gets published in API Manager after a state change, but throws an misleading exception and error message.

**Log-Output in Debug**
2263   ERROR         APIImportApp| The status change from: 'published' to 'published' is not possible!
com.axway.apim.lib.errorHandling.AppException: The status change from: 'published' to 'published' is not possible!  
        at com.axway.apim.adapter.APIStatusManager.update(APIStatusManager.java:152)
        at com.axway.apim.adapter.APIStatusManager.update(APIStatusManager.java:74)
        at com.axway.apim.apiimport.actions.UpdateExistingAPI.execute(UpdateExistingAPI.java:49)
        at com.axway.apim.apiimport.APIImportManager.applyChanges(APIImportManager.java:76)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:103)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.axway.apim.lib.errorHandling.AppException: Cannot update API-Proxy status.
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.updateAPIStatus(APIManagerAPIAdapter.java:655)
        at com.axway.apim.adapter.APIStatusManager.update(APIStatusManager.java:135)
        ... 11 more
Caused by: com.axway.apim.lib.errorHandling.AppException: Error updating API status. Received Status-Code: 200      
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.updateAPIStatus(APIManagerAPIAdapter.java:652)
        ... 12 more

**Test case sample**
as orgAdmin:
- Import an API with state 'unpublished' in API config.
- Run the import again with state 'published' in API config. Check now the console output.

**Comment by cwiechmann** [comment]
That is a duplicate to issue #134 as it also considered the status code 200 as a bad response. 
`Error updating API status. Received Status-Code: 200`
