### ISSUE TITLE
NullPointer Exception when using Outbound OAuth

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apim-cli#143]
**API-Mgr. CLI version**
1.3.3

**API-Manager and Service-Pack Version**
7.7-September

**Expected behavior**
It should be possible to configure an API with OAuth-Outbound and even if the configuration might be invalid it must handle it gracefully.

**Actual behavior**
A NullpointerException is thrown for the following configuration

```json
{
    "name": "My OAuth API",
    "path": "/api/v1/Some.Services/XmlApi",
    "state": "published",
    "version": "kk1",
    "organization": "API Development",
    "apiDefinition": "the-api-definition.json",
    "backendBasepath": "https://the.backend.of.the.service/Some.Services/XmlApi",
    "replaceHostInSwagger": false,
    "authenticationProfiles":[
      {
         "name":"_default",
         "isDefault":"true",
         "parameters":{
            "providerProfile":"<Name-of-configured-OAuth-Profile>",
            "ownerId":"${authentication.subject.id}"
         },
         "type":"oauth"
      }
   ]
}
```

**Log-Output in Debug**
```
0      INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20200930) on: https://10.32.81.17:7175
254    INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: 'C:\OFFICE\PROJECTS\API Management\API Management Implementation Project\VNAPIProjects\projects\api-virtualServices\trunk\apiEixNordpoolDayAhead-internal\api-config\Nordpool-DayAhead-API.json' (absolute path)
285    INFO      APISpecification| Used the configured backendBasepath: 'https://apidayahead.test.nordpoolgroup.com/DAW.Services/XmlApi' to adjust the Swagger definition.
385    ERROR         APIImportApp| Cannot validate/fulfill configuration file.
com.axway.apim.lib.errorHandling.AppException: Cannot validate/fulfill configuration file.
        at com.axway.apim.apiimport.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:215)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:79)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:59)
        at com.axway.apim.APIImportApp.main(APIImportApp.java:45)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
        at com.axway.apim.apiimport.APIImportConfigAdapter.handleOutboundOAuthAuthN(APIImportConfigAdapter.java:799)
        at com.axway.apim.apiimport.APIImportConfigAdapter.validateOutboundAuthN(APIImportConfigAdapter.java:788)
        at com.axway.apim.apiimport.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:203)

```

**Comment by cwiechmann** [comment]
The NPE occurs if the given OAuth-Provider-Profile is invalid/unknown. Now it's gracefully handled and returned with a proper Error-Message:
`The OAuth provider profile is unkown: 'My invalid profile name'`
