### ISSUE TITLE
Exception When Exporting API Manager Settings (Remote Hosts)

### ISSUE THREAD

**Issue by arnievoke** [Axway-API-Management-Plus/apim-cli#152]
${AXWAY_APIM_CLI_HOME}/scripts/apim.sh settings get -s mars-de -type remotehosts -ultra -o json -t config.out

Results in:

----------------------------------------------------------------------------------------
API-Manager CLI: 1.3.3
                                                                        
To report issues or get help, please visit: 
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: API-Manager - S E T T I N G S (1.3.3)
----------------------------------------------------------------------------------------
147    INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20200730) on: https://10.99.215.66:8075
294    ERROR PIManagerSettingsApp| 
java.lang.NullPointerException
	at com.axway.apim.setup.impl.JsonAPIManagerSetupExporter.getExportFolder(JsonAPIManagerSetupExporter.java:84)
	at com.axway.apim.setup.impl.JsonAPIManagerSetupExporter.export(JsonAPIManagerSetupExporter.java:40)
	at com.axway.apim.setup.APIManagerSettingsApp.exportAPIManagerSetup(APIManagerSettingsApp.java:132)
	at com.axway.apim.setup.APIManagerSettingsApp.runExport(APIManagerSettingsApp.java:89)
	at com.axway.apim.setup.APIManagerSettingsApp.exportConfig(APIManagerSettingsApp.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
	at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)

**Comment by cwiechmann** [comment]
Thanks for reporting this issue @arnievoke. I fixed this in the source and it will be delivered with version 1.3.6. In the meantime, as you may already know, add another type (policies, config or policies) while exporting remote hosts to avoid this issue.
