### ISSUE TITLE
Export-Error when using a Custom-Properties-Model

### ISSUE THREAD

**Issue by ftriolet** [Axway-API-Management-Plus/apim-cli#163]
**API-Mgr. CLI version**
1.3.6

**API-Manager and Service-Pack Version**
7.7

**Expected behavior**
export app config file must contain custom attributes

**Actual behavior**
Error parsing API-Manager custom properties

**Log-Output in Debug**
```
   ERROR PIManagerSettingsApp| Error parsing API-Manager custom properties
com.axway.apim.lib.errorHandling.AppException: Error parsing API-Manager custom properties
        at com.axway.apim.adapter.customProperties.APIManagerCustomPropertiesAdapter.getCustomProperties(APIManagerCustomPropertiesAdapter.java:75)
        at com.axway.apim.adapter.customProperties.APIManagerCustomPropertiesAdapter.getCustomProperties(APIManagerCustomPropertiesAdapter.java:80)
        at com.axway.apim.setup.impl.ConsoleAPIManagerSetupExporter.export(ConsoleAPIManagerSetupExporter.java:56)
        at com.axway.apim.setup.APIManagerSettingsApp.exportAPIManagerSetup(APIManagerSettingsApp.java:132)
        at com.axway.apim.setup.APIManagerSettingsApp.runExport(APIManagerSettingsApp.java:87)
        at com.axway.apim.setup.APIManagerSettingsApp.exportConfig(APIManagerSettingsApp.java:65)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
```

**Test case sample**
> my application custom attribute contains custom optional element as describe in documentation :

custom

Optional. A free-form object to allow extending the schema of a custom property.

As an example, for API Portal, permissions can be overridden for oadmin and user roles using:

    custom: {
        apiportal: {
            permissions: {
                oadmin: { read: true, write: false },
                user: { read: true, write: false }
            }
        },
        authorization: { type: 'basic', realm: 'portal' },
        required: true
    }
}

**Comment by ftriolet** [comment]
API-Manager and Service-Pack Version
7.7.20200730

**Comment by cwiechmann** [comment]
Thanks for reporting this issue @ftriolet. I think this even happens for APIs and Organizations. Not only for Applications as it's the general Custom-Properties configuration parser. I'm going to fix this with the next release.

**Comment by cwiechmann** [comment]
The issue is fixed and will delivered with the next release 1.3.7
