### ISSUE TITLE
NPE when trying to export application with unknown ID

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apim-cli#168]
**API-Mgr. CLI version**
1.3.7

**API-Manager and Service-Pack Version**
7.7-2021-March

**Expected behavior**
Able to export applications when they have configured custom properties

**Actual behavior**
java.lang.NullPointerException in addCustomPropertiesForEntity

**Log-Output in Debug**
```
C:\Users\cwiechmann>apim app get -id 93ff2c6d-a257-4c73-93ea-ab1be8e55b43 -u apiadmin -p changeme -h manager -port 443
----------------------------------------------------------------------------------------
API-Manager CLI: 1.3.7

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: Application - E X P O R T / U T I L S (1.3.7)
----------------------------------------------------------------------------------------
1439   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20210330) on: https://manager:443
1653   ERROR ApplicationExportApp| Can't initialize API-Manager API-Representation.
com.axway.apim.lib.errorHandling.AppException: Can't initialize API-Manager API-Representation.
        at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.getApplications(APIMgrAppsAdapter.java:149)
        at com.axway.apim.appexport.ApplicationExportApp.runExport(ApplicationExportApp.java:103)
        at com.axway.apim.appexport.ApplicationExportApp.export(ApplicationExportApp.java:70)
        at com.axway.apim.appexport.ApplicationExportApp.export(ApplicationExportApp.java:61)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: java.lang.NullPointerException
        at com.axway.apim.lib.utils.Utils.addCustomPropertiesForEntity(Utils.java:230)
        at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.getApplications(APIMgrAppsAdapter.java:146)
        ... 9 more
```

**Test case sample**
> Please describe the steps you have done to replicate the issue

**Comment by cwiechmann** [comment]
Now the APIMgrAppsAdapter handles are 404 response, when searching for applications and returns an empty result instead of null.

https://github.com/Axway-API-Management-Plus/apim-cli/blob/a75c7122ce935474042d47378fc2750c3eaeb896/modules/apim-adapter/src/main/java/com/axway/apim/adapter/clientApps/APIMgrAppsAdapter.java#L100-L104
