### ISSUE TITLE
MalformedURLException for Backend-URL not causing the CLI to fail

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apim-cli#175]
**API-Mgr. CLI version**
1.3.7

**API-Manager and Service-Pack Version**
7.7-March

**Expected behavior**
Malformed configured backend URL should cause the APIM-CLI to fail during import

**Actual behavior**
The CLI is reporting this error:
```
java.net.MalformedURLException: no protocol: ${BACKEND_HOST}/api/api/emr/diagnostic/
	at java.net.URL.<init>(URL.java:611)
	at java.net.URL.<init>(URL.java:508)
	at java.net.URL.<init>(URL.java:457)
	at com.axway.apim.api.definition.Swagger2xSpecification.configureBasepath(Swagger2xSpecification.java:45)
	at com.axway.apim.apiimport.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:198)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:79)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:59)
	at com.axway.apim.APIImportApp.main(APIImportApp.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
```
But it continues as normal.

**Comment by cwiechmann** [comment]
Now the following is logged and the CLI-Import process stops:
```
0      INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20210330) on: https://manager.axway-amplify-central.com:443
202    INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: 'C:\Axway\Tools\apim-cli-1.3.8-SNAPSHOT\samples\petstore.json' (absolute path)
286    ERROR         APIImportApp| Cannot validate/fulfill configuration file.
com.axway.apim.lib.errorHandling.AppException: Cannot validate/fulfill configuration file.
        at com.axway.apim.apiimport.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:216)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:79)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:59)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.axway.apim.lib.errorHandling.AppException: The backendBasepath: 'some-invalid' is invalid.
        at com.axway.apim.api.definition.Swagger2xSpecification.configureBasepath(Swagger2xSpecification.java:96)
        at com.axway.apim.apiimport.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:198)
        ... 8 more
Caused by: java.net.MalformedURLException: no protocol: some-invalid
        at java.base/java.net.URL.<init>(URL.java:672)
        at java.base/java.net.URL.<init>(URL.java:568)
        at java.base/java.net.URL.<init>(URL.java:515)
        at com.axway.apim.api.definition.Swagger2xSpecification.configureBasepath(Swagger2xSpecification.java:46)
        ... 9 more
```
