### ISSUE TITLE
No changes for an application should not log an Exception

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apim-cli#176]
**User story**
An exception looks like an error, but in that case it is not an error and should therefore not log an exception.

**Additional context**
```
com.axway.apim.lib.errorHandling.AppException: No changes detected between Desired- and Actual-App.
	at com.axway.apim.appimport.ClientAppImportManager.replicate(ClientAppImportManager.java:39)
	at com.axway.apim.appimport.ClientApplicationImportApp.importApp(ClientApplicationImportApp.java:87)
	at com.axway.apim.appimport.ClientApplicationImportApp.importApp(ClientApplicationImportApp.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
	at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
```

**Comment by cwiechmann** [comment]
Fixed with the refactored Error-Handling no longer using a Singleton ErrorState-
