### ISSUE TITLE
clearCache is mandatory when using different stage parameters

### ISSUE THREAD

**Issue by ftriolet** [Axway-API-Management-Plus/apim-cli#264]
**API-Mgr. CLI version**
1.10.1

**API-Manager and Service-Pack Version**
.7.20200730

**Expected behavior**
I want to execute apim-cli in different stage without having to clear cache 

**Actual behavior**
if I run an apim-cli command in one stage and another in a different stage. I have an error because API ids are differents

**Log-Output in Debug**

```
apim app get -s rec -api "API"
----------------------------------------------------------------------------------------
API-Manager CLI: 1.10.1

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: Application - E X P O R T / U T I L S (1.10.1)
----------------------------------------------------------------------------------------
3404   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20200730) on: https://api-rec/
Loading details of 209 applications [*********-] 90%
16639  INFO  ApplicationExportApp| Found 7 application(s).

apim app get -s int -api "API"
----------------------------------------------------------------------------------------
API-Manager CLI: 1.10.1

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: Application - E X P O R T / U T I L S (1.10.1)
----------------------------------------------------------------------------------------
3587   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20200730) on: https://api-int/
Loading details of 264 applications [*******---] 70%14073  ERROR APIManagerAPIAdapter| Unable to find API with ID: f65e6416-cc0f-48b5-9127-75310b362eaa. Please have in mind during API-Update the ID is re-created or add -ignoreCache !
14079  ERROR agerAPIAccessAdapter| Error loading API-Access for applications from API-Manager. Can't process response: [{"id":"b521a216-c091-4553-935c-5133b2af7b4b","apiId":"f65e6416-cc0f-48b5-9127-75310b362eaa","createdBy":"cc961668-2029-4f2e-bfdb-6c78e6198edf","state":"approved","createdOn":1641313505882,"enabled":true}]
com.axway.apim.lib.errorHandling.AppException: Unable to find API with ID: f65e6416-cc0f-48b5-9127-75310b362eaa referenced by Application: ASM Partenaires. You may try again with -clearCache
        at com.axway.apim.adapter.apis.APIManagerAPIAccessAdapter.getAPIAccess(APIManagerAPIAccessAdapter.java:123) [apimcli-apim-adapter-1.10.1.jar:1.10.1]
        at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.addAPIAccess(APIMgrAppsAdapter.java:341) [apimcli-apim-adapter-1.10.1.jar:1.10.1]
        at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.getApplications(APIMgrAppsAdapter.java:157) [apimcli-apim-adapter-1.10.1.jar:1.10.1]
        at com.axway.apim.appexport.ApplicationExportApp.runExport(ApplicationExportApp.java:126) [apimcli-apps-1.10.1.jar:1.10.1]
        at com.axway.apim.appexport.ApplicationExportApp.export(ApplicationExportApp.java:96) [apimcli-apps-1.10.1.jar:1.10.1]
        at com.axway.apim.appexport.ApplicationExportApp.export(ApplicationExportApp.java:59) [apimcli-apps-1.10.1.jar:1.10.1]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:141) [apimcli-tool-1.10.1.jar:1.10.1]
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77) [apimcli-tool-1.10.1.jar:1.10.1]
14098  INFO          AppException| You may enable debug to get more details. See: https://github.com/Axway-API-Management-Plus/apim-cli/wiki/9.1.-Enable-Debug
14098  ERROR         AppException| Can't initialize API-Manager API-Representation.
                                 | Error reading application API Access.
                                 | Error loading API-Access for applications from API-Manager
                                 | **Unable to find API with ID: f65e6416-cc0f-48b5-9127-75310b362eaa referenced by Application: APPLI Partenaires. You may try again with -clearCache**

```
**Test case sample**
apim app get -s ENV1 -api "oneAPI"
apim app get -s ENV2 -api "oneAPI"

if I clear All cache between the two commands, it's OK

Maybe, it would be interesting to prefix objet key in the cache with the stage parameter

**Comment by cwiechmann** [comment]
Thanks for creating this issue @ftriolet. I assume you agree to implement/fix this based on the API-Manager connection URL incl. the port. Right?
