### ISSUE TITLE
Error creating API-Proxy (FE-API). Received Status-Code: 500

### ISSUE THREAD

**Issue by giovane-merisio-ag** [Axway-API-Management-Plus/apim-cli#265]
**API-Mgr. CLI version**
1.2.1

**API-Manager and Service-Pack Version**
7.7.0

**Expected behavior**
API imported sucessfully

**Actual behavior**
Error 500 on import.

**Log-Output in Debug**
Error creating API-Proxy (FE-API). Received Status-Code: 500, Response: '{"errors":[{"code":500,"message":"Internal server error"}]}'

**Question**
When running the apim api import command above on Linux, i'm getting the error message:

`apim.sh api import -c import.config-prod.json -h myapimanager.com.br -u user -p secret -force`

**CLI Log Execution**
```
----------------------------------------------------------------------------------------
API-Manager CLI: 1.2.1
                                                                        
To report issues or get help, please visit: 
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: API - I M P O R T (1.2.1)
----------------------------------------------------------------------------------------
0      INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.0) on: [https://mysite.com.br:443](https://mysite.com.br/)
116    INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: '../myfile.json' (relative path)
216    INFO      APIImportManager| No existing API found, creating new!
333    INFO          CreateNewAPI| Create published API: 'My API' 1.0.0 based on Swagger 2.0 specification.
127739 ERROR APIManagerAPIAdapter| Error creating API-Proxy (FE-API). Received Status-Code: 500, Response: '{"errors":[{"code":500,"message":"Internal server error"}]}'
127795 INFO        RollbackAction| Rollback FE-API: 'My API' (ID: 'abd33009-e08e-416c-a3ae-2fac4481fbbb' / State: 'unpublished')
127845 INFO  APIManagerAPIAdapter| API: My API successfully deleted
127941 INFO       RollbackHandler| Rolled back: '[Frontend-API: false, Backend-API: true]'
127942 ERROR         APIImportApp| Can't create API-Proxy.
com.axway.apim.lib.errorHandling.AppException: Can't create API-Proxy.
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.createAPIProxy(APIManagerAPIAdapter.java:532)
	at com.axway.apim.apiimport.actions.CreateNewAPI.execute(CreateNewAPI.java:45)
	at com.axway.apim.apiimport.APIImportManager.applyChanges(APIImportManager.java:48)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
	at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.axway.apim.lib.errorHandling.AppException: Error creating API-Proxy (FE-API). Received Status-Code: 500
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.createAPIProxy(APIManagerAPIAdapter.java:527)

```

On this case project import, when we import on stage enviromnent, it worked. When we import on the production enviromnent don't. Looking for the error line in the apim-cli files I found the 514 line on the method whit name "createAPIProxy" in the file below:

https://github.com/Axway-API-Management-Plus/apim-cli/blob/dc62e0cba922d06b4adf9c74bc146b38f6c896d2/modules/apim-adapter/src/main/java/com/axway/apim/adapter/apis/APIManagerAPIAdapter.java#L514

When I import the same file using the manual way (_login on API Manager Site -> Backend API -> New API -> Import from swagger_) It works with no errors.

**Comment by cwiechmann** [comment]
Hi @giovane-merisio-ag, the version you are using is pretty old. 
Can you please update to the [latest](https://github.com/Axway-API-Management-Plus/apim-cli/releases/latest) available version of the APIM-CLI and try again?
