### ISSUE TITLE
Unable to export/import an application that have many users

### ISSUE THREAD

**Issue by archi73** [Axway-API-Management-Plus/apim-cli#270]
**API-Mgr. CLI version**
1.10.1

**API-Manager and Service-Pack Version**
7.7.20210830

**Expected behavior**
Export an application that have been shared to many users (example : 200 users)
then update the list of shared users
then import an application that have been shared to many users (example : 200 users)

If I do it in the API Manager web interface it works as expected. When i use apim-cli it throws an error.

**Actual behavior**
Export and import are not working when too many users have access to an application (it works as expected for smaller numbers)

Example of export of an application in json with 200 shared users
```
----------------------------------------------------------------------------------------
API-Manager CLI: 1.10.1
                                                                        
To report issues or get help, please visit: 
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: Application - E X P O R T / U T I L S (1.10.1)
----------------------------------------------------------------------------------------
3454   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20210830) on: https://myurl:8075
9049   ERROR PIManagerUserAdapter| Sent request: https://myurl:8075/api/portal/v1.3/users/ab97b647...
9049   ERROR PIManagerUserAdapter| Received Status-Code: 403, Response: '<html><body>Forbidden</body></html>'
9064   INFO          AppException| You may enable debug to get more details. See: https://github.com/Axway-API-Management-Plus/apim-cli/wiki/9.1.-Enable-Debug
9064   ERROR         AppException| Can't initialize API-Manager API-Representation.
                                 | Error reading application permissions. Error: Error cant read users from API-Manager with filter: UserFilter [loginName=null, id=ab97b647...]
                                 | Error cant read users from API-Manager with filter: UserFilter [loginName=null, id=ab97b647...]
                                 | 
9486   WARN     APIManagerAdapter| Logout failed with statusCode: 401. Got response: '{"errors":[{"code":102,"message":"Authorization required"}]}'
```

**Log-Output in Debug**

Example of export of an application in json with 200 shared users (with debug level)
```
----------------------------------------------------------------------------------------
API-Manager CLI: 1.10.1
                                                                        
To report issues or get help, please visit: 
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: Application - E X P O R T / U T I L S (1.10.1)
----------------------------------------------------------------------------------------
1094   DEBUG nvironmentProperties| Trying to load environment properties from file: C:\apim-cli\apim-cli-1.10.1/conf/env.properties ... not found.
2266   DEBUG    APIManagerAdapter| Logging in with User: 'myuser'
3641   DEBUG ManagerConfigAdapter| Load API-Manager configuration.
3735   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20210830) on: https://myurl:8075
3735   DEBUG rOrganizationAdapter| Load organizations from API-Manager using filter: OrgFilter [name=myOrg, id=null]
3798   DEBUG tomPropertiesAdapter| Read configured custom properties from API-Manager
3844   DEBUG    APIMgrAppsAdapter| Sending request to find existing applications: https:/myurl:8075/api/portal/v1.3/applications?field=orgid&op=eq&value=dad2c82d...
4048   DEBUG rOrganizationAdapter| Load organizations from API-Manager using filter: OrgFilter [name=null, id=dad2c82d...]
4204   DEBUG PIManagerUserAdapter| Load users from API-Manager using filter: UserFilter [loginName=null, id=35d6e60f....]
4235   DEBUG PIManagerUserAdapter| Load users from API-Manager using filter: UserFilter [loginName=null, id=07bc34a1...]
...
8845   DEBUG PIManagerUserAdapter| Load users from API-Manager using filter: UserFilter [loginName=null, id=ab97b647...]
8861   ERROR PIManagerUserAdapter| Sent request: https://myurl:8075/api/portal/v1.3/users/ab97b647...
8861   ERROR PIManagerUserAdapter| Received Status-Code: 403, Response: '<html><body>Forbidden</body></html>'
8861   ERROR         AppException| Can't initialize API-Manager API-Representation.
                                 | Error reading application permissions. Error: Error cant read users from API-Manager with filter: UserFilter [loginName=null, id=ab97b647...]
                                 | Error cant read users from API-Manager with filter: UserFilter [loginName=null, id=ab97b647-...]
                                 | 
com.axway.apim.lib.errorHandling.AppException: Can't initialize API-Manager API-Representation.
	at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.getApplications(APIMgrAppsAdapter.java:164) ~[apimcli-apim-adapter-1.10.1.jar:1.10.1]
	at com.axway.apim.appexport.ApplicationExportApp.runExport(ApplicationExportApp.java:126) ~[apimcli-apps-1.10.1.jar:1.10.1]
	at com.axway.apim.appexport.ApplicationExportApp.export(ApplicationExportApp.java:98) [apimcli-apps-1.10.1.jar:1.10.1]
	at com.axway.apim.appexport.ApplicationExportApp.export(ApplicationExportApp.java:59) [apimcli-apps-1.10.1.jar:1.10.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_291]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_291]
	at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:141) [apimcli-tool-1.10.1.jar:1.10.1]
	at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77) [apimcli-tool-1.10.1.jar:1.10.1]
Caused by: com.axway.apim.lib.errorHandling.AppException: Error reading application permissions. Error: Error cant read users from API-Manager with filter: UserFilter [loginName=null, id=ab97
b647-1831-4c75-ad2c-dfb698cccf6f]
	at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.addApplicationPermissions(APIMgrAppsAdapter.java:329) ~[apimcli-apim-adapter-1.10.1.jar:1.10.1]
	at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.getApplications(APIMgrAppsAdapter.java:156) ~[apimcli-apim-adapter-1.10.1.jar:1.10.1]
	... 9 more
Caused by: com.axway.apim.lib.errorHandling.AppException: Error cant read users from API-Manager with filter: UserFilter [loginName=null, id=ab97b647...]
	at com.axway.apim.adapter.user.APIManagerUserAdapter.readUsersFromAPIManager(APIManagerUserAdapter.java:102) ~[apimcli-apim-adapter-1.10.1.jar:1.10.1]
	at com.axway.apim.adapter.user.APIManagerUserAdapter.getUsers(APIManagerUserAdapter.java:112) ~[apimcli-apim-adapter-1.10.1.jar:1.10.1]
	at com.axway.apim.adapter.user.APIManagerUserAdapter.getUser(APIManagerUserAdapter.java:158) ~[apimcli-apim-adapter-1.10.1.jar:1.10.1]
	at com.axway.apim.adapter.user.APIManagerUserAdapter.getUserForId(APIManagerUserAdapter.java:153) ~[apimcli-apim-adapter-1.10.1.jar:1.10.1]
	at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.addApplicationPermissions(APIMgrAppsAdapter.java:323) ~[apimcli-apim-adapter-1.10.1.jar:1.10.1]
	at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.getApplications(APIMgrAppsAdapter.java:156) ~[apimcli-apim-adapter-1.10.1.jar:1.10.1]
	... 9 more
Caused by: com.axway.apim.lib.errorHandling.AppException: 
	at com.axway.apim.adapter.user.APIManagerUserAdapter.readUsersFromAPIManager(APIManagerUserAdapter.java:89) ~[apimcli-apim-adapter-1.10.1.jar:1.10.1]
	at com.axway.apim.adapter.user.APIManagerUserAdapter.getUsers(APIManagerUserAdapter.java:112) ~[apimcli-apim-adapter-1.10.1.jar:1.10.1]
	at com.axway.apim.adapter.user.APIManagerUserAdapter.getUser(APIManagerUserAdapter.java:158) ~[apimcli-apim-adapter-1.10.1.jar:1.10.1]
	at com.axway.apim.adapter.user.APIManagerUserAdapter.getUserForId(APIManagerUserAdapter.java:153) ~[apimcli-apim-adapter-1.10.1.jar:1.10.1]
	at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.addApplicationPermissions(APIMgrAppsAdapter.java:323) ~[apimcli-apim-adapter-1.10.1.jar:1.10.1]
	at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.getApplications(APIMgrAppsAdapter.java:156) ~[apimcli-apim-adapter-1.10.1.jar:1.10.1]
	... 9 more
8861   DEBUG    APIManagerAdapter| Closing cache ...
9345   WARN     APIManagerAdapter| Logout failed with statusCode: 401. Got response: '{"errors":[{"code":102,"message":"Authorization required"}]}'
```

**Test case sample**

`apim app get -h {myhost} -u {myusername} -p {mypassword} -orgName {myorganisation} -o json -t C:\temp -deleteTarget
`
`apim app import -h {myhost} -u {myusername} -p {mypassword} -c C:\temp\file.json
`

**Comment by cwiechmann** [comment]
Hi @archi73, That's because of the throttling protection for the API-Manager REST-API, which has been introduced some time ago. It then invalidates your session and you have to re-login.

See the following information and you should increase the limit:
https://docs.axway.com/bundle/axway-open-docs/page/docs/apim_administration/apimgr_admin/api_mgmt_config/index.html#configure-api-manager-request-rate-limiter

**Comment by cwiechmann** [comment]
FYI, the APIM-CLI is using internal caching, especially for the export, which should also help here. Once application details have been loaded they are cached and re-used next time. But only if the APIM-CLI finishes as the cache is closed/committed at the end of the process.
See here: https://github.com/Axway-API-Management-Plus/apim-cli/wiki/8.4.-Caching

I try to improve the APIM-CLI catching this error and log a hint about the API-Manager REST-API Throttling-Settings to make it easier for users to fix this problem on their own. I'm afraid there is not much more I can do.

**Comment by archi73** [comment]
Hi @cwiechmann, it worked thanks. I will see how to use the cache a little more to avoid hitting quotas.
