### ISSUE TITLE
jackson annotation bug :  Unrecognized field "queryStringPassThrough"  in InBoundProfile class

### ISSUE THREAD

**Issue by mmehali** [Axway-API-Management-Plus/apim-cli#286]
### APIM-CLI version

1.11.0

### API-Management version

7.7.20220530

### Bug description

Hello,

When i want to retrieve the list of apis in an organization with below command :
    
   ..\scripts\apim.bat api get -s D -org "org_name"

I get the exception:
    UnrecognizedPropertyException: Unrecognized field "queryStringPassThrough"

For more details see the stacktrace

Thanks

### Steps to reproduce

..\scripts\apim.bat api get -s D -org "orgname"

### Relevant log output

```shell
API-Manager CLI: 1.11.0

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: API - E X P O R T / U T I L S (1.11.0)
----------------------------------------------------------------------------------------
1221   DEBUG nvironmentProperties| Trying to load environment properties from file: env.properties ... not found.
1233   DEBUG nvironmentProperties| Loaded environment properties from file: env.D.properties
1507   DEBUG    APIManagerAdapter| Logging in with User: 'apiadmin'
4075   DEBUG ManagerConfigAdapter| Load API-Manager configuration.
5723   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20220530) on: https://....:80..
5734   DEBUG tomPropertiesAdapter| Read configured custom properties from API-Manager
5781   DEBUG APIManagerAPIAdapter| Sending request to find existing APIs: https://....:80../api/portal/v1.3/proxies
6084   DEBUG rOrganizationAdapter| Load organizations from API-Manager using filter: OrgFilter [name=null, id=6f40cbe7-1dd1-44fa-a870-25dc5df6033a]
6144   ERROR         AppException| Cannot read APIs from API-Manager
com.axway.apim.lib.errorHandling.AppException: Cannot read APIs from API-Manager        
  at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPIs(APIManagerAPIAdapter.java:136) ~[apimcli-apim-adapter-1.11.0.jar:1.11.0]        
  at com.axway.apim.APIExportApp.execute(APIExportApp.java:207) [apimcli-apis-1.11.0.jar:1.11.0]        
  at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:72) [apimcli-apis-1.11.0.jar:1.11.0]        
  at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:62) [apimcli-apis-1.11.0.jar:1.11.0]        
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]        
  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]        
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]        
  at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]        
  at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:141) [apimcli-tool-1.11.0.jar:1.11.0]        
  at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77) [apimcli-tool-1.11.0.jar:1.11.0]
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "queryStringPassThrough" 
(class com.axway.apim.api.model.InboundProfile), not marked as 
ignorable (4 known properties: "monitorAPI", "securityProfile", "monitorSubject", "corsProfile"]) 
at [Source: (StringReader); line: 1, column: 1237] 
(through reference chain: java.util.ArrayList[0]->com.axway.apim.api.API["inboundProfiles"]->java.util.LinkedHashMap["_default"]
->com.axway.apim.api.model.InboundProfile["queryStringPassThrough"])        
  at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1989) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:609) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:437) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3612) ~[jackson-databind-2.13.2.1.jar:2.13.2.1]        
  at com.axway.apim.adapter.apis.APIManagerAPIAdapter.filterAPIs(APIManagerAPIAdapter.java:234) ~[apimcli-apim-adapter-1.11.0.jar:1.11.0]        
  at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPIs(APIManagerAPIAdapter.java:120) ~[apimcli-apim-adapter-1.11.0.jar:1.11.0]        
  ... 9 more
6160   DEBUG    APIManagerAdapter| Closing cache ...
```

**Comment by cwiechmann** [comment]
Hi @mmehali, This requires a new version of the APIM-CLI which is about to be released beginning next week.

**Comment by mmehali** [comment]
Hi, 
Thank you for your quick reply @cwiechmann. it is with pleasure that I will use the new version

**Comment by cwiechmann** [comment]
Version 1.12.0 released
