### ISSUE TITLE
Issues during APIM CLI Login v1.12.1

### ISSUE THREAD

**Issue by giancolli** [Axway-API-Management-Plus/apim-cli#294]
### APIM-CLI version

1.12.1

### API-Management version

7.7.20220530

### Bug description

Sometimes the login with APIM-CLI works, when it calls _https://******:8075_ 

```
./apim.sh api get -s ***

3187   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20220530) on: https://****.net:8075
Loading details of 154 APIs [*********-] 90%
34398  INFO          APIExportApp| 154 API(s) selected.

```

But unfortunately most of the times it tries to reach _https://*****:8075/api/portal/v1.4/login_ and the login fails

```
./apim.sh api get -s ***

452    DEBUG nvironmentProperties| Loaded environment properties from file: env.properties
454    DEBUG nvironmentProperties| Loaded environment properties from file: env.usint.properties
570    DEBUG    APIManagerAdapter| Logging in with User: 'apiadmin'
1761   WARN     APIManagerAdapter| Login failed with statusCode: 403 ... Try again in 1000 milliseconds. (you may set -retryDelay <milliseconds>)
3481   ERROR         AppException| Can't login to API-Manager https://*******:8075/api/portal/v1.4/login
                                 | Login finally failed with statusCode: 403
com.axway.apim.lib.errorHandling.AppException: Can't login to API-Manager https://********:8075/api/portal/v1.4/login
        at com.axway.apim.adapter.APIManagerAdapter.loginToAPIManager(APIManagerAdapter.java:258) ~[apimcli-apim-adapter-1.12.1.jar:1.12.1]
        at com.axway.apim.adapter.APIManagerAdapter.<init>(APIManagerAdapter.java:185) ~[apimcli-apim-adapter-1.12.1.jar:1.12.1]
        at com.axway.apim.adapter.APIManagerAdapter.getInstance(APIManagerAdapter.java:147) ~[apimcli-apim-adapter-1.12.1.jar:1.12.1]
        at com.axway.apim.APIExportApp.execute(APIExportApp.java:201) ~[apimcli-apis-1.12.1.jar:1.12.1]
        at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:74) ~[apimcli-apis-1.12.1.jar:1.12.1]
        at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:62) ~[apimcli-apis-1.12.1.jar:1.12.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:141) ~[apimcli-tool-1.12.1.jar:1.12.1]
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77) ~[apimcli-tool-1.12.1.jar:1.12.1]
Caused by: com.axway.apim.lib.errorHandling.AppException: Login finally failed with statusCode: 403
        at com.axway.apim.adapter.APIManagerAdapter.loginToAPIManager(APIManagerAdapter.java:241) ~[apimcli-apim-adapter-1.12.1.jar:1.12.1]
        ... 11 more

```

Can you gently take a look and suggest a solution to always refer to _https://<server>:8075_  during authentication?

Thanks
Gianmario

**Comment by rathnapandi** [comment]
Hi @giancolli, 

Does the login process is failing with same stage (- s parameter) or different stage?
Also, can you check the error on API Gateway trace and share it?

Thanks
Rathna

**Comment by giancolli** [comment]
Hi @rathnapandi,

I tried the login with different stage files (all of them working 100% of the times with v1.3.12). 
For each of them, I faced the same behavior: it works only when it invokes _https://******:8075_ and fails when invoking _https://*****:8075/api/portal/v1.4/login_

Following I attach traces for a successful and not successful login, I have not found anything strange from a first look.
[unsuccesful.txt](https://github.com/Axway-API-Management-Plus/apim-cli/files/9119157/unsuccesful.txt)
[sucessful.txt](https://github.com/Axway-API-Management-Plus/apim-cli/files/9119158/sucessful.txt)

Let me know if you can find anything.

Thanks 
Gianmario

**Comment by rathnapandi** [comment]
Hi Gianmario, 
Based on the log, API manager could not find the usersession id send by apim cli. 
Are you running more than one API Manager behind the LB (Load Balancer)?  If so are you pointing to LB URL or API Manager URL?

@giancolli

**Comment by giancolli** [comment]
Hi @rathnapandi

**Comment by giancolli** [comment]
Hi @rathnapandi,

We are running more than one API Manager behind an LB, nevertheless, the CLI only refers to one of the nodes all the time.

Thanks
Gianmario

**Comment by rathnapandi** [comment]
Hi @giancolli, 

Both success and failure calls invoke  https://*****:8075/api/portal/v1.4/login ( which is the authentication endpoint). 

Can you you double check the password being used in env files?  I was wrong in my earlier comment, the logs generate a session id first  and validates username and password. If  the validation is  success, it setup a cookie header or it will return error. 

Thanks
Rathna

**Comment by giancolli** [comment]
Hi @rathnapandi,

I can confirm the env files where the same and not modified during the attempts.

Nevertheless, the issue seems not occurring anymore so I'm not currently able to replicate it.

Feel free to close the issue, if also on your side you are unable to replicate it.


BR
Gianmario
