### ISSUE TITLE
AXWAY_APIM_CLI_HOME in the environment may break tests

### ISSUE THREAD

**Issue by saper** [Axway-API-Management-Plus/apim-cli#306]
### APIM-CLI version

1.12.4-SNAPSHOT as of 27198e50bccb78422039b5affd60c0e94d08fedc

### API-Management version

unknown

### Bug description

Observed: `AXWAY_APIM_CLI_HOME` in the outside environment influences how the unit tests behave
Expected: Environment variables do not influence the unit tests at all

### Steps to reproduce

* I have  AXWAY_APIM_CLI_HOME set to my real production configuration with 4 gateways and HTTP proxy
* I run `mvn install` on a git checkout as of commit 27198e50bccb78422039b5affd60c0e94d08fedc or 5e5add313a2a5a1dff9e9cc82d4e8da1d7f1d8d5
* 3 test fail

if I unset the variable everything works again

### Relevant log output

```shell
Tests run: 168, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 2.563 sec <<< FAILURE! - in TestSuite
testPropertyFileWithoutStage(com.axway.lib.CoreCLIOptionsTest)  Time elapsed: 0.005 sec  <<< FAILURE!
java.lang.AssertionError: expected [https://localhost:8075] but found [https://null:8075]
        at com.axway.lib.CoreCLIOptionsTest.testPropertyFileWithoutStage(CoreCLIOptionsTest.java:67)

testProxyParametersFromStage(com.axway.lib.CoreCLIOptionsTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: expected [proxyHost] but found [null]
        at com.axway.lib.CoreCLIOptionsTest.testProxyParametersFromStage(CoreCLIOptionsTest.java:77)

testStagePropertyFiles(com.axway.lib.CoreCLIOptionsTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: expected [yetanotherUser] but found [null]
        at com.axway.lib.CoreCLIOptionsTest.testStagePropertyFiles(CoreCLIOptionsTest.java:55)


Results :

Failed tests:
  CoreCLIOptionsTest.testPropertyFileWithoutStage:67 expected [https://localhost:8075] but found [https://null:8075]
  CoreCLIOptionsTest.testProxyParametersFromStage:77 expected [proxyHost] but found [null]
  CoreCLIOptionsTest.testStagePropertyFiles:55 expected [yetanotherUser] but found [null]

Tests run: 168, Failures: 3, Errors: 0, Skipped: 0
```

**Comment by rathnapandi** [comment]
The above scenario was not handled.  The fix is available in develop branch.
