### ISSUE TITLE
Different error with each deploy for same api config

### ISSUE THREAD

**Issue by siemprepe** [Axway-API-Management-Plus/apim-cli#309]
### APIM-CLI version

1.3.7

### API-Management version

7.7.20210530

### Bug description

I have an api that fails with a different error message at each deploy. After the third deploy, the api was actually created, except for the organisation and application access grants. The openapi specification seems to be valid. When adding it as a backend api in the UI it imports succesfully.

### Relevant log output

```shell
Api config file:

{
  "name": "ADCS Test Feedback API",
  "path": "/adcs-test-feedback",
  "state": "published",
  "version": "1.0",
  "organization": "API Development",
  "apiDefinition": "adcstestfeedbackapi.json",
  "clientOrganizations": ["ALL"],
  "backendBasepath":"https://{{ adcstestfeedbackapi_host }}",
  "applications" : [
              {"name" : "ADCS", "enabled" : true, "state" : "approved", "oauthResources" : [ ]}
          ],
  "vhost": "{{ api_vhost }}",
  "inboundProfiles": {
       "_default": {
         "securityProfile": "_default",
         "corsProfile": "_default",
         "monitorAPI": true,
         "monitorSubject": "authentication.subject.id"
       }
     },
    "securityProfiles" : [ {
              "name" : "_default",
              "isDefault" : true,
              "devices" : [ {
                "name" : "OAuth (External)",
                "type" : "oauthExternal",
                "order" : 1,
                "properties" : {
                  "tokenStore" : "Acerta External Oauth",
                  "accessTokenLocation" : "HEADER",
                  "authorizationHeaderPrefix" : "Bearer",
                  "accessTokenLocationQueryString" : "",
                  "scopesMustMatch" : "Any",
                  "scopes" : "user_code",
                  "removeCredentialsOnSuccess" : "true",
                  "implicitGrantEnabled" : "true",
                  "implicitGrantLoginEndpointUrl" : "https://localhost:8089/api/oauth/authorize",
                  "implicitGrantLoginTokenName" : "access_token",
                  "authCodeGrantTypeEnabled" : "false",
                  "authCodeGrantTypeRequestEndpointUrl" : "https://localhost:8089/api/oauth/authorize",
                  "authCodeGrantTypeRequestClientIdName" : "client_id",
                  "authCodeGrantTypeRequestSecretName" : "client_secret",
                  "authCodeGrantTypeTokenEndpointUrl" : "https://localhost:8089/api/oauth/token",
                  "authCodeGrantTypeTokenEndpointTokenName" : "access_code",
                  "useClientRegistry" : "true",
                  "subjectSelector" : "${oauth.token.client_id}",
                  "oauth.token.valid" : "${oauth.token.valid}",
                  "oauth.token.client_id" : "${oauth.token.client_id}",
                  "oauth.token.scopes" : "${oauth.token.scopes}"
                }
              } ]
            } ]
}

First deploy:

----------------------------------------------------------------------------------------
Module: API - I M P O R T (1.3.7)
----------------------------------------------------------------------------------------
0      INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20210530) on: https://v13l016300.azure.local:8075
148    INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: '/opt/action-runner-Acerta-ICT-1/_work/apim-hybrid/apim-hybrid/apideploy/adcstestfeedbackapi/adcstestfeedbackapi.swagger.yaml' (relative path)
298    INFO  IImportConfigAdapter| Handling configured client-applications.
485    INFO  IImportConfigAdapter| Found existing application: 'ADCS' (null) based on given name 'ADCS'
581    INFO      APIImportManager| No existing API found, creating new!
814    INFO          CreateNewAPI| Create published API: 'ADCS Test Feedback API' 1.0 based on Open API 3.0 (YAML) specification.
1063   ERROR APIManagerAPIAdapter| Error creating API-Proxy (FE-API). Received Status-Code: 500, Response: '{"errors":[{"code":500,"message":"Internal server error"}]}'
1171   INFO        RollbackAction| No FE-API found to rollback.
1282   INFO       RollbackHandler| Rolled back: '[Frontend-API: false, Backend-API: true]'
1282   ERROR         APIImportApp| Can't create API-Proxy.
com.axway.apim.lib.errorHandling.AppException: Can't create API-Proxy.
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.createAPIProxy(APIManagerAPIAdapter.java:589)
	at com.axway.apim.apiimport.actions.CreateNewAPI.execute(CreateNewAPI.java:45)
	at com.axway.apim.apiimport.APIImportManager.applyChanges(APIImportManager.java:49)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:103)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
	at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.axway.apim.lib.errorHandling.AppException: Error creating API-Proxy (FE-API). Received Status-Code: 500
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.createAPIProxy(APIManagerAPIAdapter.java:584)
	... 10 more
Return code 35
Error: Process completed with exit code 35.

Second deploy:

----------------------------------------------------------------------------------------
Module: API - I M P O R T (1.3.7)
----------------------------------------------------------------------------------------
0      INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20210530) on: https://v13l016300.azure.local:8075
157    INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: '/opt/action-runner-Acerta-ICT-1/_work/apim-hybrid/apim-hybrid/apideploy/adcstestfeedbackapi/adcstestfeedbackapi.swagger.yaml' (relative path)
309    INFO  IImportConfigAdapter| Handling configured client-applications.
507    INFO  IImportConfigAdapter| Found existing application: 'ADCS' (null) based on given name 'ADCS'
629    INFO      APIImportManager| No existing API found, creating new!
893    INFO          CreateNewAPI| Create published API: 'ADCS Test Feedback API' 1.0 based on Open API 3.0 (YAML) specification.
1550   INFO      ManageClientOrgs| Granting permission to all organizations
1803   INFO      ManageClientApps| Creating API-Access for the following apps: '[[ADCS]]'
1803   INFO      ManageClientApps| Creating API-Access for application 'ADCS'
2254   ERROR agerAPIAccessAdapter| Error creating/updating API Access: APIAccess [apiName=null, apiVersion=null, id=null, apiId=763bd75b-e60a-48ec-9141-20cabf0955ec]. Response-Code: 500. Got response: '{"errors":[{"code":500,"message":"Internal server error"}]}'
2256   INFO        RollbackAction| Rollback FE-API: 'ADCS Test Feedback API' (ID: '763bd75b-e60a-48ec-9141-20cabf0955ec' / State: 'unpublished')
2626   ERROR APIManagerAPIAdapter| Error deleting API-Proxy. Response-Code: 500, Response: '{"errors":[{"code":500,"message":"Internal server error"}]}'
2627   ERROR       RollbackAction| Error while deleting FE-API to roll it back
com.axway.apim.lib.errorHandling.AppException: Cannot delete API-Proxy.
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.deleteAPIProxy(APIManagerAPIAdapter.java:656)
	at com.axway.apim.apiimport.rollback.RollbackAPIProxy.rollback(RollbackAPIProxy.java:30)
	at com.axway.apim.apiimport.rollback.RollbackHandler.executeRollback(RollbackHandler.java:60)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:111)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
	at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.axway.apim.lib.errorHandling.AppException: Error deleting API-Proxy. Response-Code: 500
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.deleteAPIProxy(APIManagerAPIAdapter.java:652)
	... 10 more
2792   INFO       RollbackHandler| Rolled back: '[Frontend-API: false, Backend-API: true]'
2792   ERROR         APIImportApp| Can't create API access requests.
com.axway.apim.lib.errorHandling.AppException: Can't create API access requests.
	at com.axway.apim.apiimport.actions.ManageClientApps.createAppSubscription(ManageClientApps.java:128)
	at com.axway.apim.apiimport.actions.ManageClientApps.execute(ManageClientApps.java:72)
	at com.axway.apim.apiimport.actions.CreateNewAPI.execute(CreateNewAPI.java:80)
	at com.axway.apim.apiimport.APIImportManager.applyChanges(APIImportManager.java:49)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:103)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
	at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.axway.apim.lib.errorHandling.AppException: Failure creating API-Access for application: 'ADCS'. Error creating/updating API Access.
	at com.axway.apim.apiimport.actions.ManageClientApps.createAppSubscription(ManageClientApps.java:123)
	... 11 more
Caused by: com.axway.apim.lib.errorHandling.AppException: Error creating/updating API Access.
	at com.axway.apim.adapter.apis.APIManagerAPIAccessAdapter.createAPIAccess(APIManagerAPIAccessAdapter.java:222)
	at com.axway.apim.apiimport.actions.ManageClientApps.createAppSubscription(ManageClientApps.java:121)
	... 11 more
Caused by: com.axway.apim.lib.errorHandling.AppException: Error creating/updating API Access. Response-Code: 500
	at com.axway.apim.adapter.apis.APIManagerAPIAccessAdapter.createAPIAccess(APIManagerAPIAccessAdapter.java:214)
	... 12 more
Return code 60
Error: Process completed with exit code 60.

Third deploy:

----------------------------------------------------------------------------------------
Module: API - I M P O R T (1.3.7)
----------------------------------------------------------------------------------------
0      INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20210530) on: https://v13l016300.azure.local:8075
148    INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: '/opt/action-runner-Acerta-ICT-1/_work/apim-hybrid/apim-hybrid/apideploy/adcstestfeedbackapi/adcstestfeedbackapi.swagger.yaml' (relative path)
300    INFO  IImportConfigAdapter| Handling configured client-applications.
499    INFO  IImportConfigAdapter| Found existing application: 'ADCS' (null) based on given name 'ADCS'
594    INFO      APIImportManager| No existing API found, creating new!
834    INFO          CreateNewAPI| Create published API: 'ADCS Test Feedback API' 1.0 based on Open API 3.0 (YAML) specification.
1424   INFO      ManageClientOrgs| Granting permission to all organizations
1528   WARN  APIManagerAPIAdapter| Got unexpected error: 'Unknown API' while creating API-Access ... Try again in 1 second.
2679   ERROR APIManagerAPIAdapter| Error granting access to API: 'ADCS Test Feedback API' (ID: cfe2ab56-5e58-4456-a0ff-b6d8cbf37faa). Received Status-Code: 500, Response: {"errors":[{"code":404,"message":"Unknown API"}]}
2679   ERROR APIManagerAPIAdapter| grantAccessToOrgs: '['API Development', 'testorgje', 'Acerta', 'Community']'
2680   ERROR APIManagerAPIAdapter| allOrgs: 'true'
2681   INFO        RollbackAction| Rollback FE-API: 'ADCS Test Feedback API' (ID: 'cfe2ab56-5e58-4456-a0ff-b6d8cbf37faa' / State: 'unpublished')
2844   ERROR APIManagerAPIAdapter| Error updating API status. Received Status-Code: 500, Response: '{"errors":[{"code":500,"message":"Internal server error"}]}'
2844   ERROR       RollbackAction| Error while deleting FE-API to roll it back
com.axway.apim.lib.errorHandling.AppException: The status change from: 'unpublished' to 'unpublished' is not possible!
	at com.axway.apim.adapter.APIStatusManager.update(APIStatusManager.java:152)
	at com.axway.apim.adapter.APIStatusManager.update(APIStatusManager.java:63)
	at com.axway.apim.apiimport.rollback.RollbackAPIProxy.rollback(RollbackAPIProxy.java:28)
	at com.axway.apim.apiimport.rollback.RollbackHandler.executeRollback(RollbackHandler.java:60)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:111)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
	at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.axway.apim.lib.errorHandling.AppException: Cannot update API-Proxy status.
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.updateAPIStatus(APIManagerAPIAdapter.java:725)
	at com.axway.apim.adapter.APIStatusManager.update(APIStatusManager.java:135)
	... 11 more
Caused by: com.axway.apim.lib.errorHandling.AppException: Error updating API status. Received Status-Code: 500
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.updateAPIStatus(APIManagerAPIAdapter.java:722)
	... 12 more
2908   ERROR APIManagerAPIAdapter| Error deleting Backend-API. Response-Code: 403, Response: '{"errors":[{"code":403,"message":"Cannot delete an API that has been virtualized."}]}'
2908   ERROR       RollbackAction| Error while deleting BE-API with ID: '9a92c058-5487-490d-a65e-ce34cd48ae94' to roll it back
com.axway.apim.lib.errorHandling.AppException: Cannot delete Backend-API.
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.deleteBackendAPI(APIManagerAPIAdapter.java:680)
	at com.axway.apim.apiimport.rollback.RollbackBackendAPI.rollback(RollbackBackendAPI.java:24)
	at com.axway.apim.apiimport.rollback.RollbackHandler.executeRollback(RollbackHandler.java:60)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:111)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
	at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.axway.apim.lib.errorHandling.AppException: Error deleting Backend-API. Response-Code: 403
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.deleteBackendAPI(APIManagerAPIAdapter.java:677)
	... 10 more
2909   INFO       RollbackHandler| Rolled back: '[Frontend-API: false, Backend-API: false]'
2909   ERROR         APIImportApp| Can't grant access to organization.
com.axway.apim.lib.errorHandling.AppException: Can't grant access to organization.
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.grantClientOrganization(APIManagerAPIAdapter.java:1059)
	at com.axway.apim.apiimport.actions.ManageClientOrgs.execute(ManageClientOrgs.java:46)
	at com.axway.apim.apiimport.actions.CreateNewAPI.execute(CreateNewAPI.java:77)
	at com.axway.apim.apiimport.APIImportManager.applyChanges(APIImportManager.java:49)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:103)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
	at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.axway.apim.lib.errorHandling.AppException: Error granting API access. Received Status-Code: 500
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.grantClientOrganization(APIManagerAPIAdapter.java:1047)
	... 11 more
Return code 59
Error: Process completed with exit code 59.
```

**Comment by rathnapandi** [comment]
@siemprepe 
Can you try with the latest version of CLI and share your results?

**Comment by rathnapandi** [comment]
@siemprepe, 

Also, can you check the API gateway logs, it will provide more insight about the error.

**Comment by rathnapandi** [comment]
Unable to reproduce.
