### ISSUE TITLE
APIs with "Per-method Overrides" causing exceptions in APIM CLI

### ISSUE THREAD

**Issue by TimVaupel** [Axway-API-Management-Plus/apim-cli#310]
### APIM-CLI version

1.12.1 (& 1.12.3)

### API-Management version

7.7.20220530

### Bug description

We have updated API Manager to Version 7.7.20220530 and since then CLI command "api get" is causing following issues:

```
./apim.sh api get -s DEV

...
Cannot deserialize value of type `java.util.ArrayList<com.axway.apim.api.model.APIMethod>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (String)"{"errors":[{"code":403,"message":"User does not have access to API"}]}"; line: 1, column: 1]
...
```
![image](https://user-images.githubusercontent.com/113672242/190666911-e2c521ff-0c85-4e72-a7ce-3b94aa5b12f1.png)
![image](https://user-images.githubusercontent.com/113672242/190666962-e459783c-ca52-41af-a7e1-a562eb3aac9b.png)

We found out that this issue is related to "Per-method overrides": e.g.:
![image](https://user-images.githubusercontent.com/113672242/190667418-6ceaa29d-2cb7-4be7-beb9-011cb86a490c.png)

After removing this option from all APIs "api get" is working fine again. But for some APIs we need this option.

With APIM Version 7.7.20210530 (and CLI 1.12.1 or 1.12.3) it's working.

### Steps to reproduce

1. virtualize an API with "Per-method overrides" option
2. try to export or get all APIs with "./apim.sh api get -s <stage>"

### Relevant log output

```shell
4498   ERROR         AppException| Cannot read APIs from API-Manager
                                 | Error cant load API-Methods for API: '623b8d5a-694a-4b0b-a991-73f84451cfd9' from API-Manager.
com.axway.apim.lib.errorHandling.AppException: Cannot read APIs from API-Manager
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPIs(APIManagerAPIAdapter.java:136) ~[apimcli-apim-adapter-1.12.1.jar:1.12.1]
	at com.axway.apim.APIExportApp.execute(APIExportApp.java:207) ~[apimcli-apis-1.12.1.jar:1.12.1]
	at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:72) ~[apimcli-apis-1.12.1.jar:1.12.1]
	at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:62) ~[apimcli-apis-1.12.1.jar:1.12.1]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:141) ~[apimcli-tool-1.12.1.jar:1.12.1]
	at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77) ~[apimcli-tool-1.12.1.jar:1.12.1]
Caused by: com.axway.apim.lib.errorHandling.AppException: Error cant load API-Methods for API: '623b8d5a-694a-4b0b-a991-73f84451cfd9' from API-Manager.
	at com.axway.apim.adapter.apis.APIManagerAPIMethodAdapter.getAllMethodsForAPI(APIManagerAPIMethodAdapter.java:67) ~[apimcli-apim-adapter-1.12.1.jar:1.12.1]
	at com.axway.apim.adapter.apis.APIManagerAPIMethodAdapter.getMethodForId(APIManagerAPIMethodAdapter.java:88) ~[apimcli-apim-adapter-1.12.1.jar:1.12.1]
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter._translateMethodIds(APIManagerAPIAdapter.java:380) ~[apimcli-apim-adapter-1.12.1.jar:1.12.1]
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.translateMethodIds(APIManagerAPIAdapter.java:271) ~[apimcli-apim-adapter-1.12.1.jar:1.12.1]
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPIs(APIManagerAPIAdapter.java:123) ~[apimcli-apim-adapter-1.12.1.jar:1.12.1]
	... 9 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<com.axway.apim.api.model.APIMethod>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (String)"{"errors":[{"code":403,"message":"User does not have access to API"}]}"; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1462) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:392) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:252) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3612) ~[jackson-databind-2.13.3.jar:2.13.3]
	at com.axway.apim.adapter.apis.APIManagerAPIMethodAdapter.getAllMethodsForAPI(APIManagerAPIMethodAdapter.java:65) ~[apimcli-apim-adapter-1.12.1.jar:1.12.1]
	at com.axway.apim.adapter.apis.APIManagerAPIMethodAdapter.getMethodForId(APIManagerAPIMethodAdapter.java:88) ~[apimcli-apim-adapter-1.12.1.jar:1.12.1]
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter._translateMethodIds(APIManagerAPIAdapter.java:380) ~[apimcli-apim-adapter-1.12.1.jar:1.12.1]
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.translateMethodIds(APIManagerAPIAdapter.java:271) ~[apimcli-apim-adapter-1.12.1.jar:1.12.1]
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPIs(APIManagerAPIAdapter.java:123) ~[apimcli-apim-adapter-1.12.1.jar:1.12.1]
	... 9 more
4502   DEBUG    APIManagerAdapter| Closing cache ...
4572   TRACE    APIManagerAdapter| Cache Closed.
```

**Comment by rathnapandi** [comment]
Hi @TimVaupel , 

I could not reproduce the issue on my setup with user role api administrator and organization administrator. 

Could you please change log_level to debug and try exporting a specific API with name filter and share the logs?
 example command -

./apim.sh api get -u apiadmin -p "changeme" -h 10.10.10.25 -o json -n "Swagger Petstore - OpenAPI 3.0".

**Comment by TimVaupel** [comment]
Hi @rathnapandi ,

thanks for your feedback.
I tested some scenarios again and it seems that the issue is related to _organization membership_, _the user roles_ and _PER-METHOD override_ option.

My User has following membership:
![image](https://user-images.githubusercontent.com/113672242/191341035-4c7accd7-0fb4-4bf5-83fd-c89e2de7a64a.png)

In the first Organization "Org.A" we have some APIs and there are some APIs in Organization "APIM Platform Mgmt". In first step, no API has "PER-METHOD OVERRIDE".
In "Org.A" I'm Org. Admin in "APIM Platform Mgmt" I have just a user role.


When trying to get all APIs I would expect getting only those from "Org.A".
But when executing `apim.sh api get -s DEV` I'm getting all APIs from all Organizations (even from those where I don't have a membership). Not sure if that is the expected behaviour?

When I now add a "PER-METHOD OVERRIDE" option to one of the APIs belonging to "APIM Platform Mgmt" (where I just have "User" Role or belonging to any other Org-Unit where I don't have access to):
![image](https://user-images.githubusercontent.com/113672242/191341641-1924327a-f8c3-46bd-88e0-59a959144d64.png)

...and I try to get all APIs again (`apim.sh api get -s DEV`)  then I'm getting the error as described above. 
`...
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type java.util.ArrayList<com.axway.apim.api.model.APIMethod> from Object value (token JsonToken.START_OBJECT)
 at [Source: (String)"{"errors":[{"code":403,"message":"User does not have access to API"}]}"; line: 1, column: 1]
...`


Are you able to reproduce this?


Thanks and best regards,
Tim

**Comment by rathnapandi** [comment]
Hi @TimVaupel, 

I can reproduce the issue.  If we export the APIs belong to user organizations with role org admin, will fix the issue. 

If we use API administrator role, it will export everything. 
With user role, we can't export. 

Thanks
Rathna
