### ISSUE TITLE
Doubt about application quota change

### ISSUE THREAD

**Issue by renankaic** [Axway-API-Management-Plus/apim-cli#312]
### APIM-CLI version

1.12.3

### API-Management version

7.7.20210530

### Question

Hello all!

Please, could you advise about the following doubt that I have regarding APIM CLI:

I need to apply a quota for specific applications (filtering then by a pattern in their names) - how can I do that using APIM CLI?

I thinking about exporting the applications, adding the quota object with the desired behavior in their files and then re-importing them again.

I would like to know if this is the correct way or there is a better way for doing that.

Thanks in advance!

**Comment by renankaic** [comment]
Hi!
I tried to apply the following quota in one application for test purposes:
```
"appQuota": {
        "restrictions": [{
            "api": "MySystem - MyFunc - v3 - PRD",
            "method": "POST /MyFuncUpdate",
            "type": "throttle",
            "config": {
                "messages": "40",
                "period": "hour",
                "per": 1
            }
        }]
    }
```

But I received the following error when using debug log:
```
4075   DEBUG agerAPIAccessAdapter| Load API-Access with type: applications from API-Manager with ID: 3abcf012-16e5-4ce0-a736-d9bb654c4628
4144   ERROR    APIMgrAppsAdapter| Error creating/updating application quota. Response-Code: 400. Got response: '{"errors":[{"code":102,"message":"Cannot modify Default Quota properties"}]}'
4146   ERROR         AppException| Error creating/updating application. Error: Error creating application quota. Error: Error creating application' Response-Code: 400
                                 | Error creating application quota. Error: Error creating application' Response-Code: 400
                                 | Error creating application' Response-Code: 400
com.axway.apim.lib.errorHandling.AppException: Error creating/updating application. Error: Error creating application quota. Error: Error creating application' Response-Code: 400
        at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.createOrUpdateApplication(APIMgrAppsAdapter.java:433) ~[apimcli-apim-adapter-1.12.3.jar:1.12.3]
        at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.createOrUpdateApplication(APIMgrAppsAdapter.java:367) ~[apimcli-apim-adapter-1.12.3.jar:1.12.3]
        at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.updateApplication(APIMgrAppsAdapter.java:359) ~[apimcli-apim-adapter-1.12.3.jar:1.12.3]
        at com.axway.apim.appimport.ClientAppImportManager.replicate(ClientAppImportManager.java:45) ~[apimcli-apps-1.12.3.jar:1.12.3]
        at com.axway.apim.appimport.ClientApplicationImportApp.importApp(ClientApplicationImportApp.java:88) ~[apimcli-apps-1.12.3.jar:1.12.3]
        at com.axway.apim.appimport.ClientApplicationImportApp.importApp(ClientApplicationImportApp.java:59) ~[apimcli-apps-1.12.3.jar:1.12.3]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_332]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_332]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_332]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_332]
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:141) ~[apimcli-tool-1.12.3.jar:1.12.3]
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77) ~[apimcli-tool-1.12.3.jar:1.12.3]
Caused by: com.axway.apim.lib.errorHandling.AppException: Error creating application quota. Error: Error creating application' Response-Code: 400
        at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.saveQuota(APIMgrAppsAdapter.java:599) ~[apimcli-apim-adapter-1.12.3.jar:1.12.3]
        at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.createOrUpdateApplication(APIMgrAppsAdapter.java:429) ~[apimcli-apim-adapter-1.12.3.jar:1.12.3]
        ... 11 more
Caused by: com.axway.apim.lib.errorHandling.AppException: Error creating application' Response-Code: 400
        at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.saveQuota(APIMgrAppsAdapter.java:594) ~[apimcli-apim-adapter-1.12.3.jar:1.12.3]
        at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.createOrUpdateApplication(APIMgrAppsAdapter.java:429) ~[apimcli-apim-adapter-1.12.3.jar:1.12.3]
        ... 11 more
4151   DEBUG    APIManagerAdapter| Closing cache ...
```


Did I do something wrong?

**Comment by rathnapandi** [comment]
Hi @renankaic, 

The syntax doesn't look right.  Please find below the sample. 

```
{
   "name":"Samples Quota Multiple restrictions",
   "path":"/samples/quota/multipleRestrictions/v1/api",
   "state":"published",
   "version":"1.0.1",
   "organization":"API Development",
   "applicationQuota":{
      "restrictions":[
         {
            "method":"*",
            "type":"throttlemb",
            "config":{
               "period":"hour",
               "mb":128,
               "per":1
            }
         }, 
         {
            "method":"*",
            "type":"throttlemb",
            "config":{
               "period":"day",
               "mb":8000,
               "per":1
            }
         }, 
         {
            "method":"*",
            "type":"throttle",
            "config":{
               "period":"minute",
               "messages":1500,
               "per":30
            }
         }
      ]
   },
   "systemQuota":{
      "restrictions":[
         {
            "method":"*",
            "type":"throttlemb",
            "config":{
               "period":"hour",
               "md":2048,
               "per":1
            }
         }, 
         {
            "method":"*",
            "type":"throttle",
            "config":{
               "period":"minute",
               "messages":10000,
               "per":30
            }
         }
      ]
   }
}


```
