### ISSUE TITLE
Get API causes an error when related certificates contains slash character '/' in their CN   

### ISSUE THREAD

**Issue by drissslim** [Axway-API-Management-Plus/apim-cli#315]
### APIM-CLI version

1.12.3

### API-Management version

7.7.20220830

### Bug description

Hi,
I'm experiencing issue when trying to get API from API Manager when the certificate exposed within an API contains a slash character '/' in their CN. Indeed, apim-cli is trying to save the certificate using the CN and without replacing this '/' with another charaxter like dash '-' as it's already done for the basePath. The result is that the full path to save the crt file isn't valid.

Could you please help on that?

Thanks.    

### Steps to reproduce

Get API with a certificate that the common name contains slash character '/'

### Relevant log output

```shell
2022-10-13 15:00:16,882 [JsonAPIExporter] INFO : Successfully exported API: 'FAETON-RDVP_RAFAEL_v1.0 (documentation v2.4)' into folder: /QSSE/tmp/apim-cli-1.13.0/scripts/rdvPermis-rafael
2022-10-13 15:00:16,899 [JsonAPIExporter] ERROR: Can't export API: Can't write certificate to disc Please check in API-Manager UI the API is valid.
com.axway.apim.lib.errorHandling.AppException: Can't write certificate to disc
    at com.axway.apim.api.export.impl.JsonAPIExporter.storeCaCerts(JsonAPIExporter.java:146)
    at com.axway.apim.api.export.impl.JsonAPIExporter.saveAPILocally(JsonAPIExporter.java:115)
    at com.axway.apim.api.export.impl.JsonAPIExporter.execute(JsonAPIExporter.java:50)
    at com.axway.apim.APIExportApp.execute(APIExportApp.java:222)
    at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:87)
    at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:78)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:141)
    at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77)
Caused by: com.axway.apim.lib.errorHandling.AppException: Can't write file
    at com.axway.apim.api.export.impl.JsonAPIExporter.writeBytesToFile(JsonAPIExporter.java:157)
    at com.axway.apim.api.export.impl.JsonAPIExporter.storeCaCerts(JsonAPIExporter.java:144)
    ... 11 more
Caused by: java.io.FileNotFoundException: /QSSE/tmp/apim-cli-1.13.0/scripts/v212-gdd-spd-ws-gdd/AutoritédeCertificationRacineANTS/AV3.crt (Aucun fichier ou dossier de ce type)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
    at com.axway.apim.api.export.impl.JsonAPIExporter.writeBytesToFile(JsonAPIExporter.java:154)
    ... 12 more
2022-10-13 15:00:16,900 [APIExportApp] ERROR: Can't write certificate to disc
                                 | Can't write file
com.axway.apim.lib.errorHandling.AppException: Can't write certificate to disc
    at com.axway.apim.api.export.impl.JsonAPIExporter.storeCaCerts(JsonAPIExporter.java:146)
    at com.axway.apim.api.export.impl.JsonAPIExporter.saveAPILocally(JsonAPIExporter.java:115)
    at com.axway.apim.api.export.impl.JsonAPIExporter.execute(JsonAPIExporter.java:50)
    at com.axway.apim.APIExportApp.execute(APIExportApp.java:222)
    at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:87)
    at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:78)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:141)
    at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77)
Caused by: com.axway.apim.lib.errorHandling.AppException: Can't write file
    at com.axway.apim.api.export.impl.JsonAPIExporter.writeBytesToFile(JsonAPIExporter.java:157)
    at com.axway.apim.api.export.impl.JsonAPIExporter.storeCaCerts(JsonAPIExporter.java:144)
    ... 11 more
Caused by: java.io.FileNotFoundException: /QSSE/tmp/apim-cli-1.13.0/scripts/v212-gdd-spd-ws-gdd/AutoritédeCertificationRacineANTS/AV3.crt (Aucun fichier ou dossier de ce type)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
    at com.axway.apim.api.export.impl.JsonAPIExporter.writeBytesToFile(JsonAPIExporter.java:154)
    ... 12 more
```

**Comment by rathnapandi** [comment]
@drissslim 
Can you share CN name? I will add it to junit test.

**Comment by drissslim** [comment]
Hi Rathna,
Please find here an example of certificate that can be including a slash '/'.
Thanks.
[Gendarmerie_nationale.zip](https://github.com/Axway-API-Management-Plus/apim-cli/files/9952077/Gendarmerie_nationale.zip)

**Comment by drissslim** [comment]
Hi Rathna,
Please find here anothe example:
CN=Autorité de Certification Racine ANTS/A V3 ou encore CN=IGC/A AC racine Etat Français

**Comment by drissslim** [comment]
Thanks a lot Rathna for fixing the issue :)
