### ISSUE TITLE
Unknow Error when trying to get the API

### ISSUE THREAD

**Issue by drissslim** [Axway-API-Management-Plus/apim-cli#316]
### APIM-CLI version

1.12.3

### API-Management version

7.7.20220228

### Question

Hi,
I'm getting this error when trying to execute this command on API Manager version 7.7.20210530 and using apim-cli 1.12.3. The execution was stopped after getting this error. The error isn't not clear and isn't referring to a specific API.
Could you please help to understand what's happening on? 

Below the stacktrace:

`Loading details of 200 APIs [*---------] 10%56943  INFO  APIManagerAPIAdapter| Loading application quotas for 1 subscribed applications.
57500  INFO  APIManagerAPIAdapter| Successfully downloaded API-Specification with version 2.0 from Frontend-API.
57626  INFO  agger2xSpecification| Used the backendBasePath: 'http://int-lb-efpr2-egeb.dtct.minint.fr:28122/rest-service/fpr/person/photos' to adjust the API-Specification.
Loading details of 200 APIs [*---------] 10%58601  INFO  APIManagerAPIAdapter| Loading application quotas for 1 subscribed applications.
Loading details of 200 APIs [*---------] 10%59214  ERROR    APIMgrAppsAdapter| Error cant load subscribes applications from API-Manager. Can't parse response: {"errors":[{"code":102,"message":"Authorization required"}]}
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<com.axway.apim.api.model.apps.ClientApplication>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (String)"{"errors":[{"code":102,"message":"Authorization required"}]}"; line: 1, column: 1]
    at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.13.3.jar:2.13.3]
    at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741) ~[jackson-databind-2.13.3.jar:2.13.3]
    at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515) ~[jackson-databind-2.13.3.jar:2.13.3]
    at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1462) ~[jackson-databind-2.13.3.jar:2.13.3]
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:392) ~[jackson-databind-2.13.3.jar:2.13.3]
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:252) ~[jackson-databind-2.13.3.jar:2.13.3]
    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28) ~[jackson-databind-2.13.3.jar:2.13.3]
    at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.13.3.jar:2.13.3]
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674) ~[jackson-databind-2.13.3.jar:2.13.3]
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629) ~[jackson-databind-2.13.3.jar:2.13.3]
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3612) ~[jackson-databind-2.13.3.jar:2.13.3]
    at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.getAppsSubscribedWithAPI(APIMgrAppsAdapter.java:177) ~[apimcli-apim-adapter-1.12.3.jar:1.12.3]
    at com.axway.apim.adapter.apis.APIManagerAPIAdapter.addClientApplications(APIManagerAPIAdapter.java:457) ~[apimcli-apim-adapter-1.12.3.jar:1.12.3]
    at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPIs(APIManagerAPIAdapter.java:101) ~[apimcli-apim-adapter-1.12.3.jar:1.12.3]
    at com.axway.apim.APIExportApp.execute(APIExportApp.java:212) ~[apimcli-apis-1.12.3.jar:1.12.3]
    at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:87) ~[apimcli-apis-1.12.3.jar:1.12.3]
    at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:78) ~[apimcli-apis-1.12.3.jar:1.12.3]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
    at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:141) ~[apimcli-tool-1.12.3.jar:1.12.3]
    at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77) ~[apimcli-tool-1.12.3.jar:1.12.3]
59220  INFO          AppException| You may enable debug to get more details. See: https://github.com/Axway-API-Management-Plus/apim-cli/wiki/9.1.-Enable-Debug
59221  ERROR         AppException| Cannot read APIs from API-Manager
                                 | Error cant load subscribes applications from API-Manager.
59702  WARN     APIManagerAdapter| Logout failed with statusCode: 401. Got response: '{"errors":[{"code":102,"message":"Authorization required"}]}'
[sadr-khanlouph@l0247488:/var/tmp/apim-cli-1.12.3/scripts$](mailto:sadr-khanlouph@l0247488:/var/tmp/apim-cli-1.12.3/scripts$)`

Thank you.

**Comment by mvenzke-axway** [comment]
It looks like it's getting a response from APIM like {"code":102,"message":"Authorization required"} instead of a list of APIs.

**Comment by rathnapandi** [comment]
@drissslim Can i close the issue if it is working on your environment.

**Comment by drissslim** [comment]
absolutely thanks @rathnapandi !
