### ISSUE TITLE
Export of API created manually in API Manager fails with apim-cli.

### ISSUE THREAD

**Issue by denache19** [Axway-API-Management-Plus/apim-cli#337]
### APIM-CLI version

1.13.2

### API-Management version

7.7.0.20221130

### Bug description

Exporting an api created manually in API Manager (Backend) using apim-cli doesn't work.

### Steps to reproduce

Create an api via the backend within API Manager.
Virtualize and attempt to export it with below command:
./apim.sh -h apigwhost -port 8075 -u apiadmin -p changeme1 -s api get -n "testapi" -o json

### Relevant log output

```shell
./apim.sh -h apigwhost -port 8075 -u apiadmin -p changeme1 -s api get "*" -o json

2022-12-15 17:23:13,745 [APIManagerCLI] INFO : API-Manager CLI: 1.13.2
2022-12-15 17:23:13,748 [APIManagerCLI] INFO : Module: API - E X P O R T / U T I L S (1.13.2)
2022-12-15 17:23:13,775 [EnvironmentProperties] DEBUG: Trying to load environment properties from file: env.properties ... not found.
2022-12-15 17:23:13,776 [EnvironmentProperties] DEBUG: Trying to load environment properties from file: env.api.properties ... not found.
2022-12-15 17:23:13,792 [APIManagerAdapter] DEBUG: Logging in with User: 'apiadmin'
2022-12-15 17:23:14,366 [APIManagerConfigAdapter] DEBUG: Load API-Manager configuration.
2022-12-15 17:23:15,113 [APIManagerAdapter] INFO : Successfully connected to API-Manager (7.7.20221130) on: https://apigwhost:8075
2022-12-15 17:23:15,116 [APIManagerCustomPropertiesAdapter] DEBUG: Read configured custom properties from API-Manager
2022-12-15 17:23:15,183 [APIManagerAPIAdapter] DEBUG: Sending request to find existing APIs: https://apigwhost:8075/api/portal/v1.4/proxies
2022-12-15 17:23:15,268 [APIManagerOrganizationAdapter] DEBUG: Load organizations from API-Manager using filter: OrgFilter [name=null, id=8ad85cda-9a68-420e-80a7-1fbdd1f0e688]
2022-12-15 17:23:15,309 [APIManagerAPIAdapter] DEBUG: Found: 3 exposed API(s) (apiPath: 'null', filter: APIFilter [id=null, name=null, vhost=null, apiPath=null, queryStringVersion=null, state=null, deprecated=false, retired=false, loadBackendAPI=false], vhost: 'null', requestedType: proxies)
2022-12-15 17:23:15,310 [APIManagerQuotaAdapter] DEBUG: Load quotas with ID: 00000000-0000-0000-0000-000000000001 from API-Manager.
2022-12-15 17:23:15,336 [APIManagerQuotaAdapter] DEBUG: Load quotas with ID: 00000000-0000-0000-0000-000000000000 from API-Manager.
2022-12-15 17:23:15,355 [APIManagerOrganizationAdapter] DEBUG: Load organizations from API-Manager using filter: OrgFilter [name=null, id=null]
2022-12-15 17:23:15,416 [APISpecificationFactory] DEBUG: Handle API-Specification: {"openapi":"3.0.2","info":{"title":"Swagger Petstore - OpenAPI 3.0","description":"This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about\nSwagger at [h... , apiDefinitionFile: petstore_2022-12-15T15:23:15Z.json , API Name : PetStore
2022-12-15 17:23:15,434 [APISpecificationFactory] DEBUG: Can't handle API specification with class: com.axway.apim.api.apiSpecification.Swagger2xSpecification
2022-12-15 17:23:15,439 [APISpecificationFactory] DEBUG: Can't handle API specification with class: com.axway.apim.api.apiSpecification.Swagger1xSpecification
2022-12-15 17:23:15,461 [APIManagerAPIAdapter] DEBUG: Resource Uri : https://petstore3.swagger.io/api/v3/openapi.json
2022-12-15 17:23:15,485 [APIManagerRemoteHostsAdapter] DEBUG: Load remote hosts from API-Manager using filter: UserFilter [name=r2, id=null]
2022-12-15 17:23:15,503 [APIManagerUserAdapter] DEBUG: Load users from API-Manager using filter: UserFilter [loginName=null, id=73687dfb-6414-4e03-bb55-a8d87fe365c0]
2022-12-15 17:23:15,550 [APISpecificationFactory] DEBUG: Handle API-Specification: {"openapi":"3.0.2","info":{"title":"Swagger Petstore - OpenAPI 3.0","description":"This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about\nSwagger at [h... , apiDefinitionFile: apitest_2022-12-15T15:23:15Z.json , API Name : apitest
2022-12-15 17:23:15,553 [APISpecificationFactory] DEBUG: Can't handle API specification with class: com.axway.apim.api.apiSpecification.Swagger2xSpecification
2022-12-15 17:23:15,554 [APISpecificationFactory] DEBUG: Can't handle API specification with class: com.axway.apim.api.apiSpecification.Swagger1xSpecification
2022-12-15 17:23:15,575 [APIManagerAPIAdapter] DEBUG: Resource Uri : https://petstore3.swagger.io/api/v3/openapi.json
2022-12-15 17:23:15,600 [APIManagerRemoteHostsAdapter] DEBUG: Load remote hosts from API-Manager using filter: UserFilter [name=myremotehost, id=null]
2022-12-15 17:23:15,612 [APIMgrAppsAdapter] DEBUG: Load subscribed applications for API-ID: 2e9ca40d-a860-44fb-ba2a-4429a242279c from API-Manager
2022-12-15 17:23:15,660 [APISpecificationFactory] DEBUG: Handle API-Specification: {
  "id" : "0bec928d-db47-499c-95e9-565210cf315f",
  "description" : "",
  "deprecated" : false,
  "apiVersion" : "1.0",
  "swaggerVersion" : "1.1",
  "basePath" : "https://10.133.134.184:28080",
  "r... , apiDefinitionFile: healthcheckapi_v1.1_2022-12-15T15:23:15Z.json , API Name : HealthCheckAPI
2022-12-15 17:23:15,661 [APISpecificationFactory] DEBUG: Can't handle API specification with class: com.axway.apim.api.apiSpecification.Swagger2xSpecification
2022-12-15 17:23:15,681 [APIExportApp] ERROR: Cannot read APIs from API-Manager
                                 | Cannot parse API-Definition for API: 'HealthCheckAPI' (1.0) on path: '/healthchecktest'
                                 | Cannot parse Backend-API for API: 'HealthCheckAPI (1.0) exposed on path: /healthchecktest' in order to change API-Specification
com.axway.apim.lib.errorHandling.AppException: Cannot read APIs from API-Manager
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPIs(APIManagerAPIAdapter.java:111)
        at com.axway.apim.APIExportApp.execute(APIExportApp.java:212)
        at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:87)
        at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:78)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:132)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:76)
Caused by: com.axway.apim.lib.errorHandling.AppException: Cannot parse API-Definition for API: 'HealthCheckAPI' (1.0) on path: '/healthchecktest'
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.addOriginalAPIDefinitionFromAPIM(APIManagerAPIAdapter.java:531)
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPIs(APIManagerAPIAdapter.java:101)
        ... 9 more
Caused by: com.axway.apim.lib.errorHandling.AppException: Cannot parse Backend-API for API: 'HealthCheckAPI (1.0) exposed on path: /healthchecktest' in order to change API-Specification
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.addBackendResourcePath(APIManagerAPIAdapter.java:584)
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.addOriginalAPIDefinitionFromAPIM(APIManagerAPIAdapter.java:526)
        ... 10 more
Caused by: java.lang.NullPointerException
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.addBackendResourcePath(APIManagerAPIAdapter.java:577)
        ... 11 more
```

**Comment by JSomervilleFromAz** [comment]
Hi @rathnapandi 
Does this check in actually fix the problem exporting an API that was created in the UI by hand?  

Using the UI, I am able to export such an API using BeAPI export and Catalog get swagger links, all that is missing is the BeAPI export original API definition option.  Is that what apim cli tries to use and fails to parse?

Do you have a timeline on when this fix will be released?

Thanks
Jim

**Comment by rathnapandi** [comment]
@JSomervilleFromAz, 

New release is available.
