### ISSUE TITLE
APIM-CLI - parsing valid metadata fails for OdataV4 api

### ISSUE THREAD

**Issue by denache19** [Axway-API-Management-Plus/apim-cli#363]
### APIM-CLI version

1.34.4

### API-Management version

7.7.0.20230228

### Bug description

We've identified an issue with the APIM-CLI during API import of OData v4 metadata.edmx (specification for odata services).

Some schema elements within Metadata.edmx do not have an EntityContainer (which is valid against the given schema of https://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/os/schemas/edm.xsd).

Actually APIM-CLI supports the import of Odata v4 metadata files.
However in this special use case it's throwing a nullpointer exception here:
https://github.com/Axway-API-Management-Plus/apim-cli/blob/develop/modules/apim-adapter/src/main/java/com/axway/apim/api/specification/ODataV4Specification.java

In Line 77:
for (EdmEntitySet entityType : schema.getEntityContainer().getEntitySets()) {

It's trying to execute the method getEntitySets on the results of getEntityContainer but as per
https://olingo.apache.org/javadoc/odata4/org/apache/olingo/commons/api/edm/EdmSchema.html The method getEntityContainer() might return null!:

getEntityContainer
EdmEntityContainer getEntityContainer()
Returns:
the entity container for this schema. May be null.

So the method is executed on null and therefore CLI is throwing nullpointer exception.

The CLI should therefore validate if getEntityContainer() is null first before executing the getEntitySets method on it.

By the way same logic should be applied in this file in line 81:
for (EdmSingleton edmSingleton : schema.getEntityContainer().getSingletons()) {

### Steps to reproduce

Use metadata-config.json and apim-cli with latest release.
[axway@SL2SUPPCUST9490 scripts]$ ./apim.sh api import -s api-env -c ../apis/metadata-config.json

### Relevant log output

```shell
2023-03-12 14:53:58,178 [APIManagerCLI] INFO : API-Manager CLI: 1.13.4
2023-03-12 14:53:58,180 [APIManagerCLI] INFO : Module: API - I M P O R T (1.13.4)
2023-03-12 14:53:58,188 [EnvironmentProperties] DEBUG: Trying to load environment properties from file: env.properties ... not found.
2023-03-12 14:53:58,195 [EnvironmentProperties] DEBUG: Loaded environment properties from file: env.api-env.properties
2023-03-12 14:53:58,534 [APIMHttpClient] DEBUG: API Manager CLI timeout : 30000
2023-03-12 14:53:58,582 [RestAPICall] DEBUG: Http verb:POST and URI: https://localhost:8075/api/portal/v1.4/login
2023-03-12 14:53:58,895 [RestAPICall] DEBUG: Http verb:GET and URI: https://localhost:8075/api/portal/v1.4/currentuser
2023-03-12 14:53:58,989 [RestAPICall] DEBUG: Http verb:GET and URI: https://localhost:8075/api/portal/v1.4/config
2023-03-12 14:53:59,103 [APIManagerAdapter] INFO : Successfully connected to API-Manager (7.7.20230228) on: https://localhost:8075
2023-03-12 14:53:59,114 [APIImportConfigAdapter] DEBUG: Handling JSON Configuration file : ../apis/metadata-config.json
2023-03-12 14:53:59,201 [APIManagerOrganizationAdapter] DEBUG: Load organizations from API-Manager using filter: OrgFilter [name=CI/POI3, id=null]
2023-03-12 14:53:59,202 [APIManagerOrganizationAdapter] DEBUG: Load organization with URI: https://localhost:8075/api/portal/v1.4/organizations?field=name&op=eq&value=CI%2FPOI3
2023-03-12 14:53:59,202 [RestAPICall] DEBUG: Http verb:GET and URI: https://localhost:8075/api/portal/v1.4/organizations?field=name&op=eq&value=CI%2FPOI3
2023-03-12 14:53:59,253 [APISpecificationFactory] INFO : Reading API-Definition (Swagger/WSDL) from file: /home/axway/api/onprem/77Feb23/apigateway/apim-cli-1.13.4/apis/metadata.xml (absolute path)
2023-03-12 14:53:59,254 [APISpecificationFactory] DEBUG: Handle API-Specification: <?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
        <Schema Namespace="System.Collections.Generic"... , apiDefinitionFile: metadata.xml , API Name : TEST DOTNET OData Service
2023-03-12 14:53:59,263 [APISpecificationFactory] DEBUG: Can't handle API specification with class: com.axway.apim.api.specification.Swagger2xSpecification
2023-03-12 14:53:59,264 [APISpecificationFactory] DEBUG: Can't handle API specification with class: com.axway.apim.api.specification.Swagger1xSpecification
2023-03-12 14:53:59,265 [APISpecificationFactory] DEBUG: Can't handle API specification with class: com.axway.apim.api.specification.OAS3xSpecification
2023-03-12 14:53:59,265 [WSDLSpecification] DEBUG: No WSDL specification. Specification doesn't contain wsdl in the first 500 characters.
2023-03-12 14:53:59,265 [APISpecificationFactory] DEBUG: Can't handle API specification with class: com.axway.apim.api.specification.WSDLSpecification
2023-03-12 14:53:59,265 [WADLSpecification] DEBUG: No WADL specification. Specification doesn't contain WADL namespace: wadl.dev.java.net in the first 500 characters.
2023-03-12 14:53:59,265 [APISpecificationFactory] DEBUG: Can't handle API specification with class: com.axway.apim.api.specification.WADLSpecification
2023-03-12 14:53:59,321 [ODataV2Specification] ERROR: Error parsing OData specification.
org.apache.olingo.odata2.api.ep.EntityProviderException: Invalid or missing namespace for 'Schema'.
        at org.apache.olingo.odata2.core.ep.consumer.XmlMetadataConsumer.checkEdmNamespace(XmlMetadataConsumer.java:946)
        at org.apache.olingo.odata2.core.ep.consumer.XmlMetadataConsumer.readMetadata(XmlMetadataConsumer.java:102)
        at org.apache.olingo.odata2.core.edm.provider.EdmxProvider.parse(EdmxProvider.java:51)
        at org.apache.olingo.odata2.core.ep.ProviderFacadeImpl.readMetadata(ProviderFacadeImpl.java:230)
        at org.apache.olingo.odata2.api.ep.EntityProvider.readMetadata(EntityProvider.java:876)
        at com.axway.apim.api.specification.ODataV2Specification.parse(ODataV2Specification.java:69)
        at com.axway.apim.api.specification.APISpecificationFactory.getAPISpecification(APISpecificationFactory.java:66)
        at com.axway.apim.api.specification.APISpecificationFactory.getAPISpecification(APISpecificationFactory.java:43)
        at com.axway.apim.apiimport.APIImportConfigAdapter.addAPISpecification(APIImportConfigAdapter.java:204)
        at com.axway.apim.apiimport.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:157)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:68)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:133)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77)
2023-03-12 14:53:59,328 [APISpecificationFactory] DEBUG: Can't handle API specification with class: com.axway.apim.api.specification.ODataV2Specification
2023-03-12 14:53:59,328 [APISpecificationFactory] DEBUG: Can't handle API specification with class: com.axway.apim.api.specification.ODataV3Specification
2023-03-12 14:53:59,437 [ODataV4Specification] ERROR: Error parsing OData V4 MetaData.
java.lang.NullPointerException
        at com.axway.apim.api.specification.ODataV4Specification.parse(ODataV4Specification.java:77)
        at com.axway.apim.api.specification.APISpecificationFactory.getAPISpecification(APISpecificationFactory.java:66)
        at com.axway.apim.api.specification.APISpecificationFactory.getAPISpecification(APISpecificationFactory.java:43)
        at com.axway.apim.apiimport.APIImportConfigAdapter.addAPISpecification(APIImportConfigAdapter.java:204)
        at com.axway.apim.apiimport.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:157)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:68)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:133)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77)
2023-03-12 14:53:59,438 [APISpecificationFactory] DEBUG: Can't handle API specification with class: com.axway.apim.api.specification.ODataV4Specification
2023-03-12 14:53:59,438 [APISpecificationFactory] ERROR: API: TEST DOTNET OData Service has a unknown/invalid API-Specification: <?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
        <Schema Namespace="System.Collections.Generic"...
2023-03-12 14:53:59,440 [APIImportApp] ERROR: Can't handle API specification. No suitable API-Specification implementation available.
com.axway.apim.lib.error.AppException: Can't handle API specification. No suitable API-Specification implementation available.
        at com.axway.apim.api.specification.APISpecificationFactory.getAPISpecification(APISpecificationFactory.java:91)
        at com.axway.apim.api.specification.APISpecificationFactory.getAPISpecification(APISpecificationFactory.java:43)
        at com.axway.apim.apiimport.APIImportConfigAdapter.addAPISpecification(APIImportConfigAdapter.java:204)
        at com.axway.apim.apiimport.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:157)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:68)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:133)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77)
2023-03-12 14:53:59,441 [APIManagerAdapter] DEBUG: Closing cache ...
2023-03-12 14:53:59,441 [RestAPICall] DEBUG: Http verb:DELETE and URI: https://localhost:8075/api/portal/v1.4/login
```

**Comment by rathnapandi** [comment]
The nullpointer exception is fixed as part of 1.13.5 release.
