### ISSUE TITLE
Error updating existing app quota that has no pre-existing quota

### ISSUE THREAD

**Issue by ConanScott** [Axway-API-Management-Plus/apim-cli#371]
### APIM-CLI version

1.13.5

### API-Management version

7.7.0.20220830

### Bug description

When api-cli is used to add a quota to an existing app that currently has no quota it incorrectly issues a PUT on the quota endpoint, resulting in a 400 error. 

This works as expected when an app already has a quota. Also, when creating a new app, apim-cli correctly issues a POST on the quota endpoint.

### Steps to reproduce

1) Create an app with no quota either via the Web UI or via apim-cli. 
2) Attempt to update this app with a quota using apim-cli and observe the 400 error and the PUT in the Gateway logs

You can use app config files similar to the attached to reproduce. Also attached is a screenshot of the PUT from Gateway logs
<img width="1408" alt="Screenshot 2023-03-21 at 1 15 38 am" src="https://user-images.githubusercontent.com/19841169/226774878-1ea938bc-0b84-4d5c-8ef2-e18fedf517df.png">

### Relevant log output

```shell
$ scripts/apim.sh app import -s api-env -c Example-App-Create/application-config.json
 
----------------------------------------------------------------------------------------
API-Manager CLI: 1.12.2
                                                                        
To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: Application - I M P O R T (1.12.2)
----------------------------------------------------------------------------------------
519    DEBUG nvironmentProperties| Trying to load environment properties from file: env.properties ... not found.
521    DEBUG nvironmentProperties| Loaded environment properties from file: env.api-env.properties
660    DEBUG    APIManagerAdapter| Logging in with User: 'apiadmin'
1134   DEBUG ManagerConfigAdapter| Load API-Manager configuration.
1511   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20220830) on: https://almalinux9:8075
1579   DEBUG nfigClientAppAdapter| Error reading single application: Cannot deserialize value of type `java.util.ArrayList<com.axway.apim.api.model.apps.ClientApplication>` from Object value (token `JsonToken.START_OBJECT`)
at [Source: (String)"{
  "name" : "Example App",
  "organization" : "Example Org",
  "state" : "approved",
  "enabled" : true,
  "apis" : [ {
    "apiName" : "Example API",
    "apiVersion" : "1.0.6"
  } ],
  "permissions" : []
}
"; line: 1, column: 1]. Trying to read single application now.
1581   DEBUG rOrganizationAdapter| Load organizations from API-Manager using filter: OrgFilter [name=Example Org, id=null]
1644   DEBUG APIManagerAPIAdapter| Sending request to find existing APIs: https://almalinux9:8075/api/portal/v1.4/proxies?field=name&op=eq&value=Example+API
1778   DEBUG rOrganizationAdapter| Load organizations from API-Manager using filter: OrgFilter [name=null, id=b49ffeb6-5e45-4fbe-9e16-28ee1362a8d4]
1816   DEBUG APIManagerAPIAdapter| Found: 1 exposed API(s)
1817   DEBUG tomPropertiesAdapter| Read configured custom properties from API-Manager
1859   DEBUG    APIMgrAppsAdapter| Sending request to find existing applications: https://almalinux9:8075/api/portal/v1.4/applications?field=name&op=eq&value=Example+App
1924   DEBUG    APIMgrAppsAdapter| Found: 0 applications
2068   DEBUG agerAPIAccessAdapter| Load API-Access with type: applications from API-Manager with ID: 955a453e-501d-4f54-b9d6-46b2918b4a65
2107   INFO  ApplicationImportApp| Successfully replicated application: Example App into API-Manager
2107   DEBUG    APIManagerAdapter| Closing cache ...

$ scripts/apim.sh app import -s api-env -c Example-App-UpdateQuota/application-config.json
 
----------------------------------------------------------------------------------------
API-Manager CLI: 1.12.2
                                                                       
To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: Application - I M P O R T (1.12.2)
----------------------------------------------------------------------------------------
516    DEBUG nvironmentProperties| Trying to load environment properties from file: env.properties ... not found.
519    DEBUG nvironmentProperties| Loaded environment properties from file: env.api-env.properties
632    DEBUG    APIManagerAdapter| Logging in with User: 'apiadmin'
1070   DEBUG ManagerConfigAdapter| Load API-Manager configuration.
1150   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20220830) on: https://almalinux9:8075
1201   DEBUG nfigClientAppAdapter| Error reading single application: Cannot deserialize value of type `java.util.ArrayList<com.axway.apim.api.model.apps.ClientApplication>` from Object value (token `JsonToken.START_OBJECT`)
at [Source: (String)"{
  "name" : "Example App",
  "organization" : "Example Org",
  "state" : "approved",
  "enabled" : true,
  "appQuota" : {
    "restrictions" : [ {
      "apiPath" : "/v3",
      "method" : "*",
      "type" : "throttle",
      "config" : {
        "period" : "second",
        "per" : "5",
        "messages" : "10"
      }
    } ]
  },
  "apis" : [ {
    "apiName" : "Example API",
    "apiVersion" : "1.0.6"
  } ],
  "permissions" : [ ]
}
"; line: 1, column: 1]. Trying to read single application now.
1204   DEBUG rOrganizationAdapter| Load organizations from API-Manager using filter: OrgFilter [name=Example Org, id=null]
1258   DEBUG APIManagerAPIAdapter| Sending request to find existing APIs: https://almalinux9:8075/api/portal/v1.4/proxies?field=path&op=eq&value=%2Fv3
1389   DEBUG rOrganizationAdapter| Load organizations from API-Manager using filter: OrgFilter [name=null, id=b49ffeb6-5e45-4fbe-9e16-28ee1362a8d4]
1421   DEBUG APIManagerAPIAdapter| Found: 1 exposed API(s)
1421   DEBUG APIManagerAPIAdapter| Sending request to find existing APIs: https://almalinux9:8075/api/portal/v1.4/proxies?field=name&op=eq&value=Example+API
1476   DEBUG APIManagerAPIAdapter| Found: 1 exposed API(s)
1477   DEBUG tomPropertiesAdapter| Read configured custom properties from API-Manager
1524   DEBUG    APIMgrAppsAdapter| Sending request to find existing applications: https://almalinux9:8075/api/portal/v1.4/applications?field=name&op=eq&value=Example+App
1576   DEBUG    APIMgrAppsAdapter| Found: 1 applications
1577   DEBUG IManagerQuotaAdapter| Load quotas with ID: 955a453e-501d-4f54-b9d6-46b2918b4a65 from API-Manager.
1621   DEBUG APIManagerAPIAdapter| Sending request to find existing APIs: https://almalinux9:8075/api/portal/v1.4/proxies/621179c4-d28c-48c0-ab1a-17481774d1f3
1653   DEBUG rOrganizationAdapter| Load organizations from API-Manager using filter: OrgFilter [name=null, id=c46e06e8-e958-4438-8a72-133bac6e4ee0]
1684   DEBUG APIManagerAPIAdapter| Found: 1 exposed API(s)
1687   DEBUG APIManagerAPIAdapter| Sending request to find existing APIs: https://almalinux9:8075/api/portal/v1.4/proxies/232bfdbc-f88b-4439-a803-7b1cdf0b8da4
1733   DEBUG APIManagerAPIAdapter| Found: 1 exposed API(s)
1733   DEBUG APIManagerAPIAdapter| Sending request to find existing APIs: https://almalinux9:8075/api/portal/v1.4/proxies/a5405304-3a9a-4d5f-af0c-d5bdfa58a829
1769   DEBUG APIManagerAPIAdapter| Found: 1 exposed API(s)
1770   DEBUG APIManagerAPIAdapter| Sending request to find existing APIs: https://almalinux9:8075/api/portal/v1.4/proxies/fb7bbb0f-44da-4ace-ba2a-8de287a0bd63
1805   DEBUG APIManagerAPIAdapter| Found: 1 exposed API(s)
1806   DEBUG APIManagerAPIAdapter| Sending request to find existing APIs: https://almalinux9:8075/api/portal/v1.4/proxies/78c2d90b-c5c3-43d0-a339-8deab770f748
1837   DEBUG APIManagerAPIAdapter| Found: 1 exposed API(s)
1978   INFO  ientAppImportManager| Update existing application: Example App (955a453e-501d-4f54-b9d6-46b2918b4a65)
2064   DEBUG agerAPIAccessAdapter| Load API-Access with type: applications from API-Manager with ID: 955a453e-501d-4f54-b9d6-46b2918b4a65
2130   ERROR    APIMgrAppsAdapter| Error creating/updating application quota. Response-Code: 400. Got response: '{"errors":[{"code":102,"message":"Cannot modify Default Quota properties"}]}'
2135   ERROR         AppException| Error creating/updating application. Error: Error creating application quota. Error: Error creating application' Response-Code: 400
                                 | Error creating application quota. Error: Error creating application' Response-Code: 400
                                 | Error creating application' Response-Code: 400
com.axway.apim.lib.errorHandling.AppException: Error creating/updating application. Error: Error creating application quota. Error: Error creating application' Response-Code: 400
                at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.createOrUpdateApplication(APIMgrAppsAdapter.java:433) ~[apimcli-apim-adapter-1.12.2.jar:1.12.2]
                at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.createOrUpdateApplication(APIMgrAppsAdapter.java:367) ~[apimcli-apim-adapter-1.12.2.jar:1.12.2]
                at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.updateApplication(APIMgrAppsAdapter.java:359) ~[apimcli-apim-adapter-1.12.2.jar:1.12.2]
                at com.axway.apim.appimport.ClientAppImportManager.replicate(ClientAppImportManager.java:45) ~[apimcli-apps-1.12.2.jar:1.12.2]
                at com.axway.apim.appimport.ClientApplicationImportApp.importApp(ClientApplicationImportApp.java:88) ~[apimcli-apps-1.12.2.jar:1.12.2]
                at com.axway.apim.appimport.ClientApplicationImportApp.importApp(ClientApplicationImportApp.java:59) ~[apimcli-apps-1.12.2.jar:1.12.2]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
                at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
                at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
                at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:141) ~[apimcli-tool-1.12.2.jar:1.12.2]
                at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77) ~[apimcli-tool-1.12.2.jar:1.12.2]
Caused by: com.axway.apim.lib.errorHandling.AppException: Error creating application quota. Error: Error creating application' Response-Code: 400
                at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.saveQuota(APIMgrAppsAdapter.java:599) ~[apimcli-apim-adapter-1.12.2.jar:1.12.2]
                at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.createOrUpdateApplication(APIMgrAppsAdapter.java:429) ~[apimcli-apim-adapter-1.12.2.jar:1.12.2]
                ... 11 more
Caused by: com.axway.apim.lib.errorHandling.AppException: Error creating application' Response-Code: 400
                at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.saveQuota(APIMgrAppsAdapter.java:594) ~[apimcli-apim-adapter-1.12.2.jar:1.12.2]
                at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.createOrUpdateApplication(APIMgrAppsAdapter.java:429) ~[apimcli-apim-adapter-1.12.2.jar:1.12.2]
                ... 11 more
2140   DEBUG    APIManagerAdapter| Closing cache ...
```

**Comment by rathnapandi** [comment]
Fixed as part of 1.13.6
