### ISSUE TITLE
Read Time out on API Creation

### ISSUE THREAD

**Issue by EmmanuelGillet** [Axway-API-Management-Plus/apim-cli#383]
### APIM-CLI version

1.13.6

### Question

Hello
I have an error "Read Time out" that keeps raising for all Swagger 2.0 API. How can I increase the timeout ? Or is it related to an unknown error ? 
I have no idea why it happens, as it works perfectly with OAS 3 API
I have added the api-config.json and the swaggerfile, but not the cert files
[Downloads.zip](https://github.com/Axway-API-Management-Plus/apim-cli/files/11220731/Downloads.zip)
2023-04-13T09:34:59.7823535Z     "/docu... , apiDefinitionFile: API GED 1.17.json , API Name : API GED 1.17 

2023-04-13T09:34:59.7896191Z [m[34m2023-04-13 11:34:59,788 [APISpecificationFactory] INFO : Detected: Swagger 2.0 specification. 
2023-04-13T09:34:59.7897917Z [m[34m2023-04-13 11:34:59,789 [Swagger2xSpecification] INFO : Adding default basePath / to swagger
2023-04-13T09:34:59.8008808Z [m[m2023-04-13 11:34:59,798 [APIManagerCustomPropertiesAdapter] DEBUG: Read configured custom properties from API-Manager
2023-04-13T09:34:59.8011244Z [m[m2023-04-13 11:34:59,798 [RestAPICall] DEBUG: Http verb:GET and URI: https://10.AA.BB.CC:8075/api/portal/v1.4/config/customproperties
2023-04-13T09:34:59.8623458Z [m[m2023-04-13 11:34:59,861 [RestAPICall] DEBUG: Http verb:POST and URI: https://10.AA.BB.CC:8075/api/portal/v1.4/certinfo
2023-04-13T09:34:59.8883911Z [m[m2023-04-13 11:34:59,887 [RestAPICall] DEBUG: Http verb:POST and URI: https://10.AA.BB.CC:8075/api/portal/v1.4/certinfo
2023-04-13T09:34:59.9096581Z [m[m2023-04-13 11:34:59,907 [RestAPICall] DEBUG: Http verb:POST and URI: https://10.AA.BB.CC:8075/api/portal/v1.4/certinfo
2023-04-13T09:34:59.9343585Z [m[34m2023-04-13 11:34:59,932 [APIImportApp] INFO : Lookup actual API based on Path: /GED-INT/gestionDocuments/v1  
2023-04-13T09:34:59.9437483Z [m[m2023-04-13 11:34:59,941 [RestAPICall] DEBUG: Http verb:GET and URI: https://10.AA.BB.CC:8075/api/portal/v1.4/proxies?field=path&op=eq&value=%2FGED-INT%2FgestionDocuments%2Fv1
2023-04-13T09:35:00.0296218Z [m[m2023-04-13 11:35:00,027 [APIManagerAPIAdapter] DEBUG: No existing API found based on filter: [apiPath=/GED-INT/gestionDocuments/v1]
2023-04-13T09:35:00.0302599Z [m[m2023-04-13 11:35:00,029 [APIChangeState] DEBUG: No existing API found. Creating  complete new API
2023-04-13T09:35:00.0318497Z [m[m2023-04-13 11:35:00,030 [RestAPICall] DEBUG: Http verb:GET and URI: https://10.AA.BB.CC:8075/api/portal/v1.4/config
2023-04-13T09:35:00.0638370Z [m[34m2023-04-13 11:35:00,059 [APIImportManager] INFO : No existing API found, creating new!
2023-04-13T09:35:00.0656739Z [m[m2023-04-13 11:35:00,062 [APIManagerAPIAdapter] DEBUG: Import backend API: API GED 1.17 based on Swagger 2.0 specification.
2023-04-13T09:35:00.0658001Z [m[m2023-04-13 11:35:00,063 [RestAPICall] DEBUG: Http verb:POST and URI: https://10.AA.BB.CC:8075/api/portal/v1.4/apirepo/import/
2023-04-13T09:35:00.2380922Z [m[34m2023-04-13 11:35:00,237 [CreateNewAPI] INFO : Create published API: API GED 1.17 1.17  based on Swagger 2.0 specification.
2023-04-13T09:35:00.2384378Z [m[m2023-04-13 11:35:00,237 [APIManagerAPIAdapter] DEBUG: Create Front-End API: API GED 1.17(API-Proxy)
2023-04-13T09:35:00.2386193Z [m[m2023-04-13 11:35:00,237 [RestAPICall] DEBUG: Http verb:POST and URI: https://10.AA.BB.CC:8075/api/portal/v1.4/proxies
2023-04-13T09:35:30.2755936Z [m[34m2023-04-13 11:35:30,274 [RollbackHandler] INFO : Rollback is disabled.
2023-04-13T09:35:30.2774252Z [m[1;31m2023-04-13 11:35:30,275 [APIImportApp] ERROR: Can't create API-Proxy.
2023-04-13T09:35:30.2775656Z                                  | Unable to send HTTP-Request.
2023-04-13T09:35:30.2778060Z com.axway.apim.lib.error.AppException: Can't create API-Proxy.
2023-04-13T09:35:30.2793550Z 	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.createAPIProxy(APIManagerAPIAdapter.java:548)
2023-04-13T09:35:30.2801891Z 	at com.axway.apim.apiimport.actions.CreateNewAPI.execute(CreateNewAPI.java:49)
2023-04-13T09:35:30.2802686Z 	at com.axway.apim.apiimport.APIImportManager.applyChanges(APIImportManager.java:48)
2023-04-13T09:35:30.2803498Z 	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:95)
2023-04-13T09:35:30.2804127Z 	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:53)
2023-04-13T09:35:30.2804671Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-04-13T09:35:30.2805291Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-04-13T09:35:30.2806553Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-04-13T09:35:30.2807286Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2023-04-13T09:35:30.2808016Z 	at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:133)
2023-04-13T09:35:30.2808702Z 	at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77)
2023-04-13T09:35:30.2809762Z Caused by: com.axway.apim.lib.error.AppException: Unable to send HTTP-Request.
2023-04-13T09:35:30.2810889Z 	at com.axway.apim.lib.utils.rest.RestAPICall.sendRequest(RestAPICall.java:51)
2023-04-13T09:35:30.2811754Z 	at com.axway.apim.lib.utils.rest.POSTRequest.execute(POSTRequest.java:20)
2023-04-13T09:35:30.2812639Z 	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.createAPIProxy(APIManagerAPIAdapter.java:538)
2023-04-13T09:35:30.2813249Z 	... 10 more
2023-04-13T09:35:30.2813696Z Caused by: java.net.SocketTimeoutException: Read timed out
2023-04-13T09:35:30.2814245Z 	at java.net.SocketInputStream.socketRead0(Native Method)
2023-04-13T09:35:30.2814938Z 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
2023-04-13T09:35:30.2815640Z 	at java.net.SocketInputStream.read(SocketInputStream.java:171)
2023-04-13T09:35:30.2816309Z 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
2023-04-13T09:35:30.2816951Z 	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)

**Comment by rathnapandi** [comment]
Hi @EmmanuelGillet, 

Can you increase the timeout value via input parameter timeout and test it?

example  ./apim.sh api get -timeout 70000 -s api-env

**Comment by EmmanuelGillet** [comment]
Hello and thanks for the reply,
it appears that the error is not related to apimcli but rather to the definition file that was setting a wrong value compared to the targeted API Manager.
The question is no longer valid

**Comment by EmmanuelGillet** [comment]
The question is no longer valid
