### ISSUE TITLE
Nullpoint Exception when downloading API Spec via apim CLI

### ISSUE THREAD

**Issue by tropotica** [Axway-API-Management-Plus/apim-cli#384]
### APIM-CLI version

1.13.6

### API-Management version

tested with 7.7.0.20211130 and 7.7.0.20220228

### Bug description

Up to apim CLI version 1.12.3 it was possible to download a specific API via CLI without any issues. All version past the 1.12.3 version throw a nullpoint exception. 
We could narrow the issue to the conversion to json. The spec can be downloaded in yaml, but fails in json.
The spec itself is provided by a vendor and should contain no actual issues. 
Were there some additional checks or measures implemented for CLI version after the above mentioned one?

```
[root@SL2SUPPAPP8143 scripts]# ./apim.sh apim api get -h 10.133.132.116 -u user -p password -org "API Development" -name "dev_calponia.yaml_2023-04-17T13 34 51Z.yaml" -o json

----------------------------------------------------------------------------------------
API-Manager CLI: 1.12.3

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: API - E X P O R T / U T I L S (1.12.3)
----------------------------------------------------------------------------------------
2757   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20211130) on: https://10.133.132.116:8075
6012   INFO          APIExportApp| 1 API(s) selected.
6015   WARN      APIResultHandler| Local export folder: /opt/Axway-7.7.0/apim-cli-1.12.3/scripts/http-com.bosch.BBM.CalibrationWorkplace.dev-calponia already exists. API will not be exported. (You may set -deleteTarget)
6064   INFO       JsonAPIExporter| Successfully exported API: 'dev_calponia.yaml_2023-04-17T13 34 51Z.yaml (2.0.1)' into folder: /opt/Axway-7.7.0/apim-cli-1.12.3/scripts/http-com.bosch.BBM.CalibrationWorkplace.dev-calponia


[root@SL2SUPPAPP8143 scripts]# ./apim.sh apim api get -h 10.133.132.116 -u user -p password -org "API Development" -name "dev_calponia.yaml_2023-04-17T13 34 51Z.yaml" -o json

2023-04-18 12:03:24,064 [APIManagerCLI] INFO : API-Manager CLI: 1.13.6
2023-04-18 12:03:24,068 [APIManagerCLI] INFO : Module: API - E X P O R T / U T I L S (1.13.6)
2023-04-18 12:03:26,363 [APIManagerAdapter] INFO : Successfully connected to API-Manager (7.7.20211130) on: https://10.133.132.116:8075
[Fatal Error] :1:1: Content is not allowed in prolog.
2023-04-18 12:03:29,014 [WSDLSpecification] ERROR: Error parsing WSDL : Content is not allowed in prolog.
2023-04-18 12:03:29,201 [ODataV4Specification] ERROR: Error parsing OData V4 MetaData.
java.lang.IllegalArgumentException: Could not parse as Edmx document
        at org.apache.olingo.client.core.serialization.ClientODataDeserializerImpl.toMetadata(ClientODataDeserializerImpl.java:148)
        at org.apache.olingo.client.core.serialization.ODataReaderImpl.readMetadata(ODataReaderImpl.java:67)
        at com.axway.apim.api.specification.ODataV4Specification.parse(ODataV4Specification.java:53)
        at com.axway.apim.api.specification.APISpecificationFactory.getAPISpecification(APISpecificationFactory.java:66)
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.addOriginalAPIDefinitionFromAPIM(APIManagerAPIAdapter.java:471)
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPIs(APIManagerAPIAdapter.java:89)
        at com.axway.apim.APIExportApp.execute(APIExportApp.java:180)
        at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:55)
        at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:133)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character 'o' (code 111) in prolog
 at [row,col {unknown-source}]: [1,5]
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._initializeXmlReader(XmlFactory.java:734)
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:600)
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:30)
        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1084)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3714)
        at org.apache.olingo.client.core.serialization.ClientODataDeserializerImpl.toMetadata(ClientODataDeserializerImpl.java:141)
        ... 14 more
Caused by: com.fasterxml.aalto.WFCException: Unexpected character 'o' (code 111) in prolog
 at [row,col {unknown-source}]: [1,5]
        at com.fasterxml.aalto.in.XmlScanner.reportInputProblem(XmlScanner.java:1333)
        at com.fasterxml.aalto.in.XmlScanner.throwUnexpectedChar(XmlScanner.java:1519)
        at com.fasterxml.aalto.in.XmlScanner.reportPrologUnexpChar(XmlScanner.java:1379)
        at com.fasterxml.aalto.in.StreamScanner.nextFromProlog(StreamScanner.java:187)
        at com.fasterxml.aalto.stax.StreamReaderImpl.next(StreamReaderImpl.java:790)
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._initializeXmlReader(XmlFactory.java:729)
        ... 19 more
2023-04-18 12:03:29,202 [APISpecificationFactory] ERROR: API: dev_calponia.yaml_2023-04-17T13 34 51Z.yaml has a unknown/invalid API-Specification: openapi: 3.0.0
info:
  title: Calponia API
  version: 2.0.1
  description: ''
  x-logo:
    url: /v2/logo.png
    backgroundColor: '#fafafa'
servers:
  - url: 'https://l2758-iflmap.hcisbp.eu1.hana....
2023-04-18 12:03:29,505 [APIExportApp] INFO : 1 API(s) selected.
2023-04-18 12:03:29,509 [UnknownAPISpecification] ERROR: API: 'dev_calponia.yaml_2023-04-17T13 34 51Z.yaml' has a unkown/invalid API-Specification: API-Specification is null
2023-04-18 12:03:29,511 [APIExportApp] ERROR: null
java.lang.NullPointerException
        at java.io.FileOutputStream.write(FileOutputStream.java:313)
        at com.axway.apim.api.export.impl.APIResultHandler.writeBytesToFile(APIResultHandler.java:281)
        at com.axway.apim.api.export.impl.JsonAPIExporter.saveAPILocally(JsonAPIExporter.java:88)
        at com.axway.apim.api.export.impl.JsonAPIExporter.execute(JsonAPIExporter.java:53)
        at com.axway.apim.APIExportApp.execute(APIExportApp.java:190)
        at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:55)
        at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:133)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77)
```

The same issue on August 2022 version: 

```
[root@SL2SUPPECD8821 scripts]# ./apim.sh apim api get -h 10.133.132.38 -u user -p password -org "Community" -name "dev_calponia.yaml_2023-04-17T13 34 51Z.yaml" -o json

2023-04-18 17:49:51,975 [APIManagerCLI] INFO : API-Manager CLI: 1.13.6
2023-04-18 17:49:51,979 [APIManagerCLI] INFO : Module: API - E X P O R T / U T I L S (1.13.6)
2023-04-18 17:49:54,244 [APIManagerAdapter] INFO : Successfully connected to API-Manager (7.7.20220830) on: https://10.133.132.38:8075
[Fatal Error] :1:1: Content is not allowed in prolog.
2023-04-18 17:49:56,310 [WSDLSpecification] ERROR: Error parsing WSDL : Content is not allowed in prolog.
2023-04-18 17:49:56,483 [ODataV4Specification] ERROR: Error parsing OData V4 MetaData.
java.lang.IllegalArgumentException: Could not parse as Edmx document
        at org.apache.olingo.client.core.serialization.ClientODataDeserializerImpl.toMetadata(ClientODataDeserializerImpl.java:148)
        at org.apache.olingo.client.core.serialization.ODataReaderImpl.readMetadata(ODataReaderImpl.java:67)
        at com.axway.apim.api.specification.ODataV4Specification.parse(ODataV4Specification.java:53)
        at com.axway.apim.api.specification.APISpecificationFactory.getAPISpecification(APISpecificationFactory.java:66)
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.addOriginalAPIDefinitionFromAPIM(APIManagerAPIAdapter.java:471)
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPIs(APIManagerAPIAdapter.java:89)
        at com.axway.apim.APIExportApp.execute(APIExportApp.java:180)
        at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:55)
        at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:133)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character 'o' (code 111) in prolog
 at [row,col {unknown-source}]: [1,5]
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._initializeXmlReader(XmlFactory.java:734)
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:600)
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._createParser(XmlFactory.java:30)
        at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1084)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3714)
        at org.apache.olingo.client.core.serialization.ClientODataDeserializerImpl.toMetadata(ClientODataDeserializerImpl.java:141)
        ... 14 more
Caused by: com.fasterxml.aalto.WFCException: Unexpected character 'o' (code 111) in prolog
 at [row,col {unknown-source}]: [1,5]
        at com.fasterxml.aalto.in.XmlScanner.reportInputProblem(XmlScanner.java:1333)
        at com.fasterxml.aalto.in.XmlScanner.throwUnexpectedChar(XmlScanner.java:1519)
        at com.fasterxml.aalto.in.XmlScanner.reportPrologUnexpChar(XmlScanner.java:1379)
        at com.fasterxml.aalto.in.StreamScanner.nextFromProlog(StreamScanner.java:187)
        at com.fasterxml.aalto.stax.StreamReaderImpl.next(StreamReaderImpl.java:790)
        at com.fasterxml.jackson.dataformat.xml.XmlFactory._initializeXmlReader(XmlFactory.java:729)
        ... 19 more
2023-04-18 17:49:56,484 [APISpecificationFactory] ERROR: API: dev_calponia.yaml_2023-04-17T13 34 51Z.yaml has a unknown/invalid API-Specification: openapi: 3.0.1
info:
  title: Calponia API
  version: 2.0.1
  description: ''
  x-logo:
    url: /v2/logo.png
    backgroundColor: '#fafafa'
servers:
  - url: 'https://l2758-iflmap.hcisbp.eu1.hana....
2023-04-18 17:49:56,717 [APIExportApp] INFO : 1 API(s) selected.
2023-04-18 17:49:56,721 [UnknownAPISpecification] ERROR: API: 'dev_calponia.yaml_2023-04-17T13 34 51Z.yaml' has a unkown/invalid API-Specification: API-Specification is null
2023-04-18 17:49:56,722 [APIExportApp] ERROR: null
java.lang.NullPointerException
        at java.io.FileOutputStream.write(FileOutputStream.java:313)
        at com.axway.apim.api.export.impl.APIResultHandler.writeBytesToFile(APIResultHandler.java:281)
        at com.axway.apim.api.export.impl.JsonAPIExporter.saveAPILocally(JsonAPIExporter.java:88)
        at com.axway.apim.api.export.impl.JsonAPIExporter.execute(JsonAPIExporter.java:53)
        at com.axway.apim.APIExportApp.execute(APIExportApp.java:190)
        at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:55)
        at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:133)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77)

```

### Steps to reproduce

To reproduce this issue you need to:
1. Import the attached swagger and modify from .txt into .yaml (I was not able to import the yaml file here).
2. Download the spec using the following command with apim cli 1.13.6 version: ./apim.sh apim api get -h 10.133.132.38 -u user -p password -org "Community" -name "dev_calponia.yaml_2023-04-17T13 34 51Z.yaml" -o json
[dev_calponia.yaml_2023-04-17T13 34 51Z (1).txt](https://github.com/Axway-API-Management-Plus/apim-cli/files/11263595/dev_calponia.yaml_2023-04-17T13.34.51Z.1.txt)

**Comment by rathnapandi** [comment]
Hi @tropotica, 

Can you test it with  
[axway-apimcli-1.13.7-SNAPSHOT.zip](https://github.com/Axway-API-Management-Plus/apim-cli/files/11290699/axway-apimcli-1.13.7-SNAPSHOT.zip) ?

**Comment by tropotica** [comment]
Hi @rathnapandi,

It's working fine with 1.13.7.
Thank you!
