### ISSUE TITLE
NPE when trying to import OpenAPI 3.0 spec without given servers

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apim-cli#40]
**API-Mgr. CLI version**
1.1.0

**API-Manager and Service-Pack Version**
7.7-March

**Expected behavior**
Import OpenAPI 3.0.1 specification **without** having `servers` defined by using backendBasepath instruction in config file.

**Actual behavior**
A NullPointerException appears when trying to setup the given backendBasepath in OpenAPI 3.0 file:

**Log-Output in Debug**
```
790    ERROR     APISpecification| Cannot replace host in provided Swagger-File. Continue with given host.
java.lang.NullPointerException
        at com.axway.apim.api.definition.OAS3xSpecification.configureBasepath(OAS3xSpecification.java:37)
        at com.axway.apim.api.definition.OAS3xSpecification.configure(OAS3xSpecification.java:55)
        at com.axway.apim.api.definition.APISpecificationFactory.getAPISpecification(APISpecificationFactory.java:44)
        at com.axway.apim.api.definition.APISpecificationFactory.getAPISpecification(APISpecificationFactory.java:28)
        at com.axway.apim.apiimport.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:222)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
```

**Comment by cwiechmann** [comment]
Issue is solved and will be delivered with 1.2.0
