### ISSUE TITLE
Deleting a V-Host is not considered as a modification?

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apim-cli#457]
### APIM-CLI version

1.14.0

### API-Management version

7.7.20220228

### Question

We tried to export and import all API by deleting the "vhost" parameter but apim-cli always returns us : no changes

2024-02-12 16:01:33,152 [APIChangeState] DEBUG: No change for property: corsProfiles [Desired: [com.axway.apim.api.model.CorsProfile@f13ae8a6] vs Actual: [com.axway.apim.api.model.CorsProfile@f13ae8a6]]
2024-02-12 16:01:33,152 [APIChangeState] DEBUG: Ignoring Null-Property: clientOrganizations [Desired: null  vs Actual: ['SERVICES CENTRAUX']]
2024-02-12 16:01:33,152 [APIChangeState] DEBUG: Ignoring Null-Property: applications [Desired: null  vs Actual: []]
2024-02-12 16:01:33,152 [APIChangeState] DEBUG: No change for property: path [Desired: /healthcheck_rng vs Actual: /healthcheck_rng]
2024-02-12 16:01:33,152 [APIChangeState] DEBUG: No change for property: state [Desired: published vs Actual: published]
2024-02-12 16:01:33,152 [APIChangeState] DEBUG: No change for property: version [Desired: 1.0 vs Actual: 1.0]
2024-02-12 16:01:33,152 [APIChangeState] DEBUG: Ignoring Null-Property: vhost [Desired: null  vs Actual: apis-interne-int.di.cdc.fr]
2024-02-12 16:01:33,152 [APIChangeState] DEBUG: No change for property: name [Desired: Rennaud_healthcheck vs Actual: Rennaud_healthcheck]
2024-02-12 16:01:33,152 [APIChangeState] DEBUG: No change for property: organization [Desired: 'SERVICES CENTRAUX' vs Actual: 'SERVICES CENTRAUX']
2024-02-12 16:01:33,152 [APIChangeState] DEBUG: Ignoring Null-Property: retirementDate [Desired: null  vs Actual: 0]
2024-02-12 16:01:33,152 [APIChangeState] DEBUG: Ignoring Null-Property: apiMethods [Desired: null  vs Actual: [com.axway.apim.api.model.APIMethod@c209191a]]
2024-02-12 16:01:33,152 [RestAPICall] DEBUG: Http verb:GET and URI: https://apimanager-support-interne-int.serv.cdc.fr:443/api/portal/v1.4/config
2024-02-12 16:01:33,190 [APIImportManager] DEBUG: BUT, no changes detected between Import- and API-Manager-API. Exiting now...
2024-02-12 16:01:33,190 [APIImportApp] WARN : No changes detected between Import- and API-Manager-API: 'Rennaud_healthcheck' (b4eec62a-0819-4861-8656-aa8574fe6637)
com.axway.apim.lib.error.AppException: No changes detected between Import- and API-Manager-API: 'Rennaud_healthcheck' (b4eec62a-0819-4861-8656-aa8574fe6637)
        at com.axway.apim.apiimport.APIImportManager.applyChanges(APIImportManager.java:58)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:95)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:133)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77)
2024-02-12 16:01:33,190 [APIManagerAdapter] DEBUG: Closing cache ...
2024-02-12 16:01:33,190 [RestAPICall] DEBUG: Http verb:DELETE and URI: https://apimanager-support-interne-int.serv.cdc.fr:443/api/portal/v1.4/login
No changes detected. Existing with RC: 0

**Comment by rathnapandi** [comment]
Hi @Rennaud, 

Please test with 
[axway-apimcli-1.14.4-SNAPSHOT.tar.gz](https://github.com/Axway-API-Management-Plus/apim-cli/files/14515928/axway-apimcli-1.14.4-SNAPSHOT.tar.gz) for the fix.

**Comment by Rennaud** [comment]
Hi @rathnapandi,
I did try with the v1.14.4 but it still doesn't modify the API published : 
$ ./apim.sh api import -c "C:\Users\caxwayac-e\Documents\export_apimcli\api-manager\INT\support-interne\vhostTest\healthcheck_rng\api-config.json" -h apimanager-support-interne-int.serv.cdc.fr -port 443 --username apiadmin --password changeme -force
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11+28, mixed mode)
2024-03-08 17:48:22,555 [APIManagerCLI] INFO : API-Manager CLI: 1.14.4-SNAPSHOT
2024-03-08 17:48:22,570 [APIManagerCLI] INFO : Module: API - I M P O R T  (1.14.4-SNAPSHOT)
2024-03-08 17:48:24,010 [APIManagerAdapter] INFO : Successfully connected to API-Manager (7.7.20220228) on: https://apimanager-support-interne-int.serv.cdc.fr:443
2024-03-08 17:48:24,520 [APISpecificationFactory] INFO : Reading API-Definition (Swagger/WSDL) from file: C:\Users\caxwayac-e\Documents\export_apimcli\api-manager\INT\support-interne\vhostTest\healthcheck_rng\Rennaud_healthcheck.json (absolute path)
2024-03-08 17:48:24,550 [APISpecificationFactory] INFO : Detected: Swagger 1.x specification.
2024-03-08 17:48:24,655 [APIImportApp] INFO : Lookup actual API based on Path: /healthcheck_rng
2024-03-08 17:48:35,800 [APIImportManager] INFO : Recognized the following changes. Potentially Breaking: [vhost] plus Non-Breaking: []
2024-03-08 17:48:35,800 [APIImportManager] INFO : Is Breaking changes : true Enforce Breaking changes : true
2024-03-08 17:48:35,800 [APIImportManager] INFO : Update API Strategy: All changes can be applied in current state.
2024-03-08 17:48:35,800 [UpdateExistingAPI] INFO : Update existing published API: Rennaud_healthcheck 1.0 (ID: 7287e189-32c0-4086-91ee-f940b97b6e64)
2024-03-08 17:48:36,025 [ManageClientOrganization] INFO : reCreation : false
2024-03-08 17:48:36,025 [UpdateExistingAPI] INFO : Successfully updated published API: Rennaud_healthcheck 1.0 (ID: 7287e189-32c0-4086-91ee-f940b97b6e64)


The I still see the v-host in the export or on API Manager after this import.

**Comment by rathnapandi** [comment]
Hi @Rennaud 
Fixed it, Use the code 
[axway-apimcli-1.14.4-SNAPSHOT.zip](https://github.com/Axway-API-Management-Plus/apim-cli/files/14541720/axway-apimcli-1.14.4-SNAPSHOT.zip)

Scenario to consider. 

1. If api manager has an API with vhost and api-config has null vhost value, the CLI will replace the vhost on API manager. 
2. If api manager has an api with empty vhost and api-config has api.away.com, the CLI will create a new API as API manager allows same endpoint on multiple vhosts.

**Comment by Rennaud** [comment]
Hi @rathnapandi ,

It works fine with the latest SNAPSHOT.
We have an API with a vhost : "vhosttest", We export the API that gave me the line in api-config.json :   "vhost" : "vhosttest",
We just delete that full line.
We import the API and then in API Manager it deletes the vhost.

Regards
Rennaud
