### ISSUE TITLE
[Bug] NullPointerException during export using -wide option

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apim-cli#46]
**API-Mgr. CLI version**
1.1.0

**API-Manager and Service-Pack Version**
7.6.2 SP4

**Expected behavior**

**Actual behavior**
If I run an export like "apim api get -s <myStage> -wide" I get the stacktrace below.

**Log-Output in Debug**
java.lang.NullPointerException
        at com.axway.apim.api.export.impl.APIResultHandler.getUsedSecurity(APIResultHandler.java:140)
        at com.axway.apim.api.export.impl.ConsoleAPIExporter.lambda$printWide$11(ConsoleAPIExporter.java:64)
        at com.github.freva.asciitable.ColumnData.getCellValue(ColumnData.java:15)
        at com.github.freva.asciitable.AsciiTable.lambda$null$0(AsciiTable.java:40)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
        at com.github.freva.asciitable.AsciiTable.lambda$getTable$2(AsciiTable.java:41)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
        at com.github.freva.asciitable.AsciiTable.getTable(AsciiTable.java:42)
        at com.axway.apim.api.export.impl.ConsoleAPIExporter.printWide(ConsoleAPIExporter.java:56)
        at com.axway.apim.api.export.impl.ConsoleAPIExporter.execute(ConsoleAPIExporter.java:37)
        at com.axway.apim.APIExportApp.runExport(APIExportApp.java:113)
        at com.axway.apim.APIExportApp.export(APIExportApp.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:138)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:76)

**Test case sample**
> Please describe the steps you have done to replicate the issue

**Comment by cwiechmann** [comment]
This issue is already fixed and will be delivered with version 1.2.0

**Comment by jschaefer77** [comment]
great :). thx.
