### ISSUE TITLE
"ERROR: Cannot validate/fulfill configuration file." when importing back downloaded API

### ISSUE THREAD

**Issue by emmanuel-galindo** [Axway-API-Management-Plus/apim-cli#466]
### APIM-CLI version

1.14.4

### API-Management version

7.7.20231130

### Bug description

After downloading an api, and importing it back it, apim-cli informs:
"ERROR: Cannot validate/fulfill configuration file."

### Steps to reproduce

Sharing config, .dat and complete debug in a private email

### Relevant log output

```shell
2024-03-12 14:09:40,028 [APISpecification] DEBUG: JSON API-Definition detected
2024-03-12 14:09:40,029 [OAS3xSpecification] DEBUG: openapi tag value : null
2024-03-12 14:09:40,030 [APISpecificationFactory] DEBUG: Can't handle API specification with class: com.axway.apim.api.specification.OAS3xSpecification
2024-03-12 14:09:40,030 [APISpecification] DEBUG: JSON API-Definition detected
2024-03-12 14:09:40,031 [APISpecificationFactory] DEBUG: Can't handle API specification with class: com.axway.apim.api.specification.Swagger2xSpecification
2024-03-12 14:09:40,032 [APISpecification] DEBUG: JSON API-Definition detected
2024-03-12 14:09:40,033 [APISpecificationFactory] INFO : Detected: Swagger 1.x specification.
2024-03-12 14:09:40,034 [APIManagerCustomPropertiesAdapter] DEBUG: Read configured custom properties from API-Manager
2024-03-12 14:09:40,034 [RestAPICall] DEBUG: Http verb:GET and URI: https://apim.com:8075/api/portal/v1.4/config/customproperties
2024-03-12 14:09:40,864 [APIImportApp] ERROR: Cannot validate/fulfill configuration file.
com.axway.apim.lib.error.AppException: Cannot validate/fulfill configuration file.
        at com.axway.apim.apiimport.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:163)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:66)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:52)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:129)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:72)
Caused by: java.lang.NullPointerException
        at com.axway.apim.apiimport.APIImportConfigAdapter.handleOutboundSSLAuthN(APIImportConfigAdapter.java:671)
        at com.axway.apim.apiimport.APIImportConfigAdapter.validateOutboundAuthN(APIImportConfigAdapter.java:643)
        at com.axway.apim.apiimport.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:147)
        ... 8 more
2024-03-12 14:09:40,865 [APIManagerAdapter] DEBUG: Closing cache ...
2024-03-12 14:09:40,866 [RestAPICall] DEBUG: Http verb:DELETE and URI: https://apim.com:8075/api/portal/v1.4/login
```

**Comment by rathnapandi** [comment]
Hi @emmanuel-galindo, 

When you do an import add extra field named password under parameters.
