### ISSUE TITLE
API with star (*) on the name fails to be exported

### ISSUE THREAD

**Issue by emmanuel-galindo** [Axway-API-Management-Plus/apim-cli#467]
### APIM-CLI version

1.14.4

### API-Management version

7.7.20231130

### Bug description

If feAPI has star/asterisk (*) char on the name, when running "apim api get -o json" in windows, it fails with this error:
2024-03-12 14:59:26,198 [ExportHelper] DEBUG: Going to export API: (XX) API ** OLD** into folder: C:\Users\emgalin\dev\projects\apim-changelist\backup\20240311221747\e3debecd-3863-42e2-8f1c-ec453c45f180\api-old
2024-03-12 14:59:26,206 [APIExportApp] ERROR: Can't save API-Definition locally to file: C:\Users\emgalin\dev\projects\apim-changelist\backup\20240311221747\e3debecd-3863-42e2-8f1c-ec453c45f180\api-old/(XX) API ** OLD**.json
                                 | Can't write file
com.axway.apim.lib.error.AppException: Can't save API-Definition locally to file: C:\Users\emgalin\dev\projects\apim-changelist\backup\20240311221747\e3debecd-3863-42e2-8f1c-ec453c45f180\api-old/(XX) API ** OLD**.json
        at com.axway.apim.api.export.impl.ExportHelper.saveAPILocally(ExportHelper.java:66)
        at com.axway.apim.api.export.impl.JsonAPIExporter.execute(JsonAPIExporter.java:32)
        at com.axway.apim.APIExportApp.execute(APIExportApp.java:184)
        at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:129)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:72)
Caused by: com.axway.apim.lib.error.AppException: Can't write file
        at com.axway.apim.api.export.impl.ExportHelper.writeBytesToFile(ExportHelper.java:152)
        at com.axway.apim.api.export.impl.ExportHelper.saveAPILocally(ExportHelper.java:62)
        ... 9 more
Caused by: java.io.FileNotFoundException: C:\Users\emgalin\dev\projects\apim-changelist\backup\20240311221747\e3debecd-3863-42e2-8f1c-ec453c45f180\api-old\(XX) API ** OLD**.json (The filename, directory name, or volume label syntax is incorrect)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:126)
        at com.axway.apim.api.export.impl.ExportHelper.writeBytesToFile(ExportHelper.java:149)
        ... 10 more

**Comment by rathnapandi** [comment]
Fixed in 1.14.4
