### ISSUE TITLE
Importing breaking changes without force flag - [outboundProfiles, serviceProfiles]

### ISSUE THREAD

**Issue by emmanuel-galindo** [Axway-API-Management-Plus/apim-cli#468]
### APIM-CLI version

1.14.4

### API-Management version

7.7.20231130

### Bug description

For an APi that's just downloaded (w/the -useFE flag), and then imported back, it throws:

2024-03-12 15:18:36,992 [APIImportManager] INFO : Is Breaking changes : false Enforce Breaking changes : false
2024-03-12 15:18:36,993 [APIImportManager] DEBUG: Apply breaking changes: [outboundProfiles, serviceProfiles] & and Non-Breaking: [], for unpublished
2024-03-12 15:18:36,993 [APIImportManager] INFO : Update API Strategy: All changes can be applied in current state.

And then 
2024-03-12 15:18:38,180 [APIManagerAPIMethodAdapter] DEBUG: 35b0835e-90c7-4000-b972-a45c93e41040 - a343575c-5f29-4c10-91a2-5df8f73225d5
2024-03-12 15:18:38,185 [UpdateExistingAPI] ERROR: Error updating existing API
com.axway.apim.lib.error.AppException: No operation found with name: 'a343575c-5f29-4c10-91a2-5df8f73225d5'
        at com.axway.apim.adapter.apis.APIManagerAPIMethodAdapter.getMethodForName(APIManagerAPIMethodAdapter.java:82)
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.translateMethodIds(APIManagerAPIAdapter.java:356)
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.translateMethodIds(APIManagerAPIAdapter.java:254)
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.translateMethodIds(APIManagerAPIAdapter.java:233)
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.updateAPIProxy(APIManagerAPIAdapter.java:577)
        at com.axway.apim.apiimport.actions.UpdateExistingAPI.execute(UpdateExistingAPI.java:55)
        at com.axway.apim.apiimport.APIImportManager.applyChanges(APIImportManager.java:68)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:93)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:52)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:129)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:72)
2024-03-12 15:18:38,190 [APIImportApp] ERROR: Error updating existing API
com.axway.apim.lib.error.AppException: Error updating existing API
        at com.axway.apim.apiimport.actions.UpdateExistingAPI.execute(UpdateExistingAPI.java:89)
        at com.axway.apim.apiimport.APIImportManager.applyChanges(APIImportManager.java:68)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:93)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:52)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:129)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:72)

If introducing a change (a new tag), it informs:
2024-03-12 15:23:52,848 [APIImportManager] INFO : Is Breaking changes : false Enforce Breaking changes : false
2024-03-12 15:23:52,848 [APIImportManager] DEBUG: Apply breaking changes: [outboundProfiles] & and Non-Breaking: [tags], for unpublished
2024-03-12 15:23:52,849 [APIImportManager] INFO : Update API Strategy: All changes can be applied in current state.
2024-03-12 15:23:52,851 [UpdateExistingAPI] INFO : Update existing unpublished API: (IT EDS) API Management API 2.0 (ID: 35b0835e-90c7-4000-b972-a45c93e41040)
2024-03-12 15:23:52,852 [APIChangeState] INFO : Updating Frontend-API (Proxy) for the following properties: tags outboundProfiles

### Steps to reproduce

Sharing data on a private email

**Comment by rathnapandi** [comment]
Hi @emmanuel-galindo,

Works fine on latest release, please reopen if you see the issue on your environment.
