### ISSUE TITLE
APIM-cli import conflicts with older retired versions of a feAPI

### ISSUE THREAD

**Issue by emmanuel-galindo** [Axway-API-Management-Plus/apim-cli#469]
### APIM-CLI version

1.14.4

### API-Management version

7.7.20231130

### Bug description

When running apim-cli import for a feAPI that has 3 entries in APIM, two of them retired and one published, being the published the one that should be selected, api-cli exits because no unique api was found:

2024-03-12 15:38:10,374 [RestAPICall] DEBUG: Http verb:GET and URI: https://xxxx.com:8075/api/portal/v1.4/proxies/0fbe7852-e780-4318-a2ac-dbbc8b53d7b8/image
2024-03-12 15:38:11,190 [APIManagerAPIMethodAdapter] DEBUG: Load API-Methods for API: 0fbe7852-e780-4318-a2ac-dbbc8b53d7b8 from API-Manager
2024-03-12 15:38:11,191 [RestAPICall] DEBUG: Http verb:GET and URI: https://xxxx.com:8075/api/portal/v1.4/proxies/0fbe7852-e780-4318-a2ac-dbbc8b53d7b8/operations
2024-03-12 15:38:11,467 [APIImportApp] ERROR: No unique API found. Found 3 APIs based on filter: APIFilter{id='null', apiId='null', name='null', vhost='null', apiPath='/unique-path-api', queryStringVersion='null', state='null', backendBasepath='null', inboundSecurity='null', outboundAuthentication='null', organization='null', createdOn='null', type=ACTUAL_API, policyName='null', tag='null', customProperties=null, deprecated=false, retired=false, apiType='null', translateMethodMode=AS_NAME, loadBackendAPI=false, includeOperations=false, includeQuotas=true, includeClientOrganizations=true, includeClientApplications=true, includeClientAppQuota=false, includeImage=true, includeRemoteHost=false, includeOriginalAPIDefinition=true, useFEAPIDefinition=false, failOnError=true, includeMethods=true, translatePolicyMode=TO_NAME}
com.axway.apim.lib.error.AppException: No unique API found. Found 3 APIs based on filter: APIFilter{id='null', apiId='null', name='null', vhost='null', apiPath='/unique-path-api', queryStringVersion='null', state='null', backendBasepath='null', inboundSecurity='null', outboundAuthentication='null', organization='null', createdOn='null', type=ACTUAL_API, policyName='null', tag='null', customProperties=null, deprecated=false, retired=false, apiType='null', translateMethodMode=AS_NAME, loadBackendAPI=false, includeOperations=false, includeQuotas=true, includeClientOrganizations=true, includeClientApplications=true, includeClientAppQuota=false, includeImage=true, includeRemoteHost=false, includeOriginalAPIDefinition=true, useFEAPIDefinition=false, failOnError=true, includeMethods=true, translatePolicyMode=TO_NAME}
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getUniqueAPI(APIManagerAPIAdapter.java:200)
        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPI(APIManagerAPIAdapter.java:121)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:91)
        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:52)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:129)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:72)
2024-03-12 15:38:11,470 [APIManagerAdapter] DEBUG: Closing cache ...

### Steps to reproduce

Sharing data on a private email

**Comment by rathnapandi** [comment]
@emmanuel-galindo,

Please test the fix with - 
[axway-apimcli-1.14.4-SNAPSHOT.zip](https://github.com/Axway-API-Management-Plus/apim-cli/files/14579938/axway-apimcli-1.14.4-SNAPSHOT.zip)

**Comment by rathnapandi** [comment]
Fixed in 1.14.4
