### ISSUE TITLE
APIM-cli import breaks feAPIs with basic auth w/out password

### ISSUE THREAD

**Issue by emmanuel-galindo** [Axway-API-Management-Plus/apim-cli#470]
### APIM-CLI version

1.14.2

### API-Management version

7.7.3

### Bug description

For a feAPI that has an outbound backend servier with BASIC auth, and only username defined and password is empty, "apim api get" retrieves:
" [...]
  "authenticationProfiles" : [ {
    "name" : "_default",
    "isDefault" : true,
    "parameters" : {
      "username" : "user",
      "_id_" : 0
    },
[...]" 
Doing an import with this, breaks the feAPI and user gets 500. Exception in logs reads:
" 
[...]
nested fault: no password specified
java.lang.NullPointerException: no password specified
	at com.vordel.dwe.http.ClientTransaction.basicAuthString(Native Method)
	at com.vordel.circuit.net.BasicAuthNConnectionHandler$BasicState.getAuthToken(BasicAuthNConnectionHandler.java:152)
	at com.vordel.circuit.net.BasicAuthNConnectionHandler$BasicState.expectContinue(BasicAuthNConnectionHandler.java:191)
[...]" 

When setting this basic (user with no password) via API Manager UI, the PUT request body reads as:
" [...]
  "authenticationProfiles": [
    {
      "name": "_default",
      "isDefault": true,
      "parameters": {
        "username": "username",
        "_id_": 0,
        "password": ""
      },
      "type": "http_basic"
    }
[...]"

**Comment by emmanuel-galindo** [comment]
@rathnapandi this is fixed in 1.14.4 right?

**Comment by rathnapandi** [comment]
Hi @emmanuel-galindo, Can you test it with latest relelase?

**Comment by jschutte27** [comment]
I am having this issue with 1.14.9 yet.

**Comment by rathnapandi** [comment]
Hi @jschutte27, 

I can reproduce the issue; will let you know once it is fixed.

**Comment by rathnapandi** [comment]
Hi @jschutte27, 

I have fixed the issue. please test it with 

[axway-apimcli-1.14.11-SNAPSHOT.tar.gz](https://github.com/user-attachments/files/18969080/axway-apimcli-1.14.11-SNAPSHOT.tar.gz)

**Comment by jschutte27** [comment]
Sorry, I wasn't able to test before the 1.14.11 release.  I did some testing now with it and it still seems to cause issues with basic auth.  I ran api get and then api import of one api with a password in the file (authenticationProfiles) and one without the password and they both result in error 500s when being accessed.  Api gateway gives:  java.lang.NullPointerException: no password specified

It seems like apim is removing the password either way and it we need it to ignore the password when missing or set it when provided.

Thanks.

**Comment by rathnapandi** [comment]
Hi @jschutte27,

Due to security reasons APIM removes the password field from response for basic and 2-way SSL backend authentication.  There are couple of options
1.  Enable a system property ( com.axway.apimanager.api.model.disable.confidential.fields to true) to return password from api manager. 
2. Add the password field in api-config.json before doing import operation.  I did test and I don't see any issues connecting to the backend. 


Thanks 
Rathna

**Comment by jschutte27** [comment]
Sorry, I wasn't clear.  I tried importing the file that was exported directly without the password field

"authenticationProfiles": [
    {
      "name": "_default",
      "isDefault": true,
      "parameters": {
        "username": "xxxxxxxxxxxx",
        "_id_": 0
      },
      "type": "http_basic"
    }
  ]

and by adding the password field. 

 "authenticationProfiles": [
    {
      "name": "_default",
      "isDefault": true,
      "parameters": {
        "username": "xxxxxxxxxxxxx",
        "_id_": 0,
        "password": "xxxxxxxxxxxxx"
      },
      "type": "http_basic"
    }
  ]

 Both ways seem to remove the password from the API so it returns error 500 with the null password stack trace.

**Comment by rathnapandi** [comment]
I fixed the second item.   Can you enable the traffic monitor and see whats being sent from CLI?

**Comment by jschutte27** [comment]
I am no longer able to reproduce the first issue (no password)... I don't know what happened this morning but it worked on two different API's now.

**Comment by jschutte27** [comment]
I misunderstood your previous comment.  It does appear that the import is working correctly now if you specify the password in the api config file.  Thanks!
