### ISSUE TITLE
Handshake_failure at login in API Manager

### ISSUE THREAD

**Issue by biancaatsh** [Axway-API-Management-Plus/apim-cli#508]
### APIM-CLI version

1.14.3

### API-Management version

7.7.20231130

### Bug description

While using apim cli 1.14.3 with Nov23 API Gateway installation, receive a handshake error while trying to connect to API Manager.
 
While upgrading the OS to RHEL 9.2, the APIM CLI is unable to connect to the API Manager. Tested it on RHEL 8, where it works fine. However, when tested it on RHEL 9.4,  encountered the issue (handshake_failure). 

`./apim.sh -Djavax.net.debug=ssl,handshake apim settings get -s qa -k
2024-10-14 17:02:45,576 [APIManagerCLI] INFO : API-Manager CLI: 1.14.3
2024-10-14 17:02:45,578 [APIManagerCLI] INFO : Module: API-Manager - S E T T I N G S  (1.14.3)
2024-10-14 17:02:45,586 [EnvironmentProperties] DEBUG: Trying to load environment properties from file: env.properties ... not found.
2024-10-14 17:02:45,595 [EnvironmentProperties] DEBUG: Loaded environment properties from file: env.qa.properties
2024-10-14 17:02:46,747 [APIMHttpClient] DEBUG: API Manager CLI http client timeout : 30000
2024-10-14 17:02:46,834 [RestAPICall] DEBUG: Http verb:POST and URI:
https://10.133.133.92:8075/api/portal/v1.4/login
2024-10-14 17:02:46,925 [APIManagerSettingsApp] ERROR: Can't login to API-Manager
                                 | Unable to send HTTP-Request.
com.axway.apim.lib.error.AppException: Can't login to API-Manager
        at com.axway.apim.adapter.APIManagerAdapter.loginToAPIManager(APIManagerAdapter.java:242)
        at com.axway.apim.adapter.APIManagerAdapter.getInstance(APIManagerAdapter.java:101)
        at com.axway.apim.setup.APIManagerSettingsApp.exportAPIManagerSetup(APIManagerSettingsApp.java:103)
        at com.axway.apim.setup.APIManagerSettingsApp.runExport(APIManagerSettingsApp.java:89)
        at com.axway.apim.setup.APIManagerSettingsApp.exportConfig(APIManagerSettingsApp.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:131)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:74)
Caused by: com.axway.apim.lib.error.AppException: Unable to send HTTP-Request.
        at com.axway.apim.lib.utils.rest.RestAPICall.sendRequest(RestAPICall.java:51)
        at com.axway.apim.lib.utils.rest.POSTRequest.execute(POSTRequest.java:20)
        at com.axway.apim.adapter.HttpHelper.execute(HttpHelper.java:13)
        at com.axway.apim.adapter.APIManagerAdapter.loginToAPIManager(APIManagerAdapter.java:222)
        ... 10 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:318)
        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1401)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1309)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.axway.apim.lib.utils.rest.RestAPICall.sendRequest(RestAPICall.java:46)`

### Relevant log output

```shell
./apim.sh  apim settings get -s qa -k
2024-10-14 17:11:45,371 [APIManagerCLI] INFO : API-Manager CLI: 1.14.3
2024-10-14 17:11:45,373 [APIManagerCLI] INFO : Module: API-Manager - S E T T I N G S  (1.14.3)
2024-10-14 17:11:45,381 [EnvironmentProperties] DEBUG: Trying to load environment properties from file: env.properties ... not found.
2024-10-14 17:11:45,389 [EnvironmentProperties] DEBUG: Loaded environment properties from file: env.qa.properties
javax.net.ssl|FINE|01|main|2024-10-14 17:11:46.512 EEST|SSLCipher.java:438|jdk.tls.keyLimits:  entry = AES/GCM/NoPadding KeyUpdate 2^37. AES/GCM/NOPADDING:KEYUPDATE = 137438953472
2024-10-14 17:11:46,551 [APIMHttpClient] DEBUG: API Manager CLI http client timeout : 30000
2024-10-14 17:11:46,593 [RestAPICall] DEBUG: Http verb:POST and URI: https://10.133.133.92:8075/api/portal/v1.4/login
javax.net.ssl|WARNING|01|main|2024-10-14 17:11:46.656 EEST|ServerNameExtension.java:261|Unable to indicate server name
javax.net.ssl|FINE|01|main|2024-10-14 17:11:46.657 EEST|SSLExtensions.java:260|Ignore, context unavailable extension: server_name
javax.net.ssl|FINE|01|main|2024-10-14 17:11:46.657 EEST|SSLExtensions.java:260|Ignore, context unavailable extension: status_request
javax.net.ssl|WARNING|01|main|2024-10-14 17:11:46.660 EEST|SignatureScheme.java:297|Signature algorithm, ed25519, is not supported by the underlying providers
javax.net.ssl|WARNING|01|main|2024-10-14 17:11:46.660 EEST|SignatureScheme.java:297|Signature algorithm, ed448, is not supported by the underlying providers
javax.net.ssl|INFO|01|main|2024-10-14 17:11:46.664 EEST|AlpnExtension.java:178|No available application protocols
javax.net.ssl|FINE|01|main|2024-10-14 17:11:46.665 EEST|SSLExtensions.java:260|Ignore, context unavailable extension: application_layer_protocol_negotiation
javax.net.ssl|FINE|01|main|2024-10-14 17:11:46.665 EEST|SSLExtensions.java:260|Ignore, context unavailable extension: status_request_v2
javax.net.ssl|FINE|01|main|2024-10-14 17:11:46.665 EEST|SSLExtensions.java:260|Ignore, context unavailable extension: cookie
javax.net.ssl|FINE|01|main|2024-10-14 17:11:46.684 EEST|SSLExtensions.java:260|Ignore, context unavailable extension: renegotiation_info
javax.net.ssl|FINE|01|main|2024-10-14 17:11:46.685 EEST|PreSharedKeyExtension.java:631|No session to resume.
javax.net.ssl|FINE|01|main|2024-10-14 17:11:46.685 EEST|SSLExtensions.java:260|Ignore, context unavailable extension: pre_shared_key
javax.net.ssl|FINE|01|main|2024-10-14 17:11:46.690 EEST|ClientHello.java:564|Produced ClientHello handshake message (
"ClientHello": {
  "client version"      : "TLSv1.2",
  "random"              : "A9 30 96 BD A9 EC B3 82 D7 32 1F 2F 76 7F FC BD 6F 90 BD 5B 44 04 EB 13 27 75 FF 77 C8 58 D4 42",
  "session id"          : "55 B0 03 76 80 4F B4 A2 16 E5 EE 6D 69 69 86 F7 32 D1 A0 D6 CE 68 0F AD 53 09 F8 5C AB 5F B3 63",
  "cipher suites"       : "[TLS_AES_256_GCM_SHA384(0x1302), TLS_AES_128_GCM_SHA256(0x1301), TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384(0xC02C), TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256(0xC02B), TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384(0xC030), TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256(0xC02F), TLS_DHE_RSA_WITH_AES_256_GCM_SHA384(0x009F), TLS_DHE_RSA_WITH_AES_128_GCM_SHA256(0x009E), TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384(0xC024), TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384(0xC028), TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256(0xC023), TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256(0xC027), TLS_DHE_RSA_WITH_AES_256_CBC_SHA256(0x006B), TLS_DHE_RSA_WITH_AES_128_CBC_SHA256(0x0067), TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA(0xC00A), TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA(0xC014), TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA(0xC009), TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA(0xC013), TLS_DHE_RSA_WITH_AES_256_CBC_SHA(0x0039), TLS_DHE_RSA_WITH_AES_128_CBC_SHA(0x0033), TLS_RSA_WITH_AES_256_GCM_SHA384(0x009D), TLS_RSA_WITH_AES_128_GCM_SHA256(0x009C), TLS_RSA_WITH_AES_256_CBC_SHA256(0x003D), TLS_RSA_WITH_AES_128_CBC_SHA256(0x003C), TLS_RSA_WITH_AES_256_CBC_SHA(0x0035), TLS_RSA_WITH_AES_128_CBC_SHA(0x002F), TLS_EMPTY_RENEGOTIATION_INFO_SCSV(0x00FF)]",
  "compression methods" : "00",
  "extensions"          : [
    "supported_groups (10)": {
      "versions": [secp256r1, secp384r1, secp521r1, ffdhe2048, ffdhe3072, ffdhe4096, ffdhe6144, ffdhe8192]
    },
    "ec_point_formats (11)": {
      "formats": [uncompressed]
    },
    "signature_algorithms (13)": {
      "signature schemes": [ecdsa_secp256r1_sha256, ecdsa_secp384r1_sha384, ecdsa_secp521r1_sha512, rsa_pss_rsae_sha256, rsa_pss_rsae_sha384, rsa_pss_rsae_sha512, rsa_pss_pss_sha256, rsa_pss_pss_sha384, rsa_pss_pss_sha512, rsa_pkcs1_sha256, rsa_pkcs1_sha384, rsa_pkcs1_sha512, ecdsa_sha224, rsa_sha224]
    },
    "signature_algorithms_cert (50)": {
      "signature schemes": [ecdsa_secp256r1_sha256, ecdsa_secp384r1_sha384, ecdsa_secp521r1_sha512, rsa_pss_rsae_sha256, rsa_pss_rsae_sha384, rsa_pss_rsae_sha512, rsa_pss_pss_sha256, rsa_pss_pss_sha384, rsa_pss_pss_sha512, rsa_pkcs1_sha256, rsa_pkcs1_sha384, rsa_pkcs1_sha512, ecdsa_sha224, rsa_sha224]
    },
    "extended_master_secret (23)": {
      <empty>
    },
    "supported_versions (43)": {
      "versions": [TLSv1.3, TLSv1.2]
    },
    "psk_key_exchange_modes (45)": {
      "ke_modes": [psk_dhe_ke]
    },
    "key_share (51)": {
      "client_shares": [
        {
          "named group": secp256r1
          "key_exchange": {
            0000: 04 3A D3 15 80 5C 6A EF   23 B1 C6 28 F3 A2 8F 55  .:...\j.#..(...U
            0010: 39 EB EF E9 3C 77 B2 BB   B8 18 EC 78 CF 36 69 3D  9...<w.....x.6i=
            0020: 00 DE F9 53 6A 06 84 89   6F 97 59 99 4A 80 86 47  ...Sj...o.Y.J..G
            0030: 0A 67 62 82 48 93 E8 75   6D 8B A7 FB 2E 20 0F 59  .gb.H..um.... .Y
            0040: E1
          }
        },
      ]
    }
  ]
}
)
javax.net.ssl|FINE|01|main|2024-10-14 17:11:46.693 EEST|Alert.java:238|Received alert message (
"Alert": {
  "level"      : "fatal",
  "description": "handshake_failure"
}
)
javax.net.ssl|SEVERE|01|main|2024-10-14 17:11:46.694 EEST|TransportContext.java:323|Fatal (HANDSHAKE_FAILURE): Received fatal alert: handshake_failure (
"throwable" : {
  javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:318)
        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1401)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1309)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.axway.apim.lib.utils.rest.RestAPICall.sendRequest(RestAPICall.java:46)
        at com.axway.apim.lib.utils.rest.POSTRequest.execute(POSTRequest.java:20)
        at com.axway.apim.adapter.HttpHelper.execute(HttpHelper.java:13)
        at com.axway.apim.adapter.APIManagerAdapter.loginToAPIManager(APIManagerAdapter.java:222)
        at com.axway.apim.adapter.APIManagerAdapter.getInstance(APIManagerAdapter.java:101)
        at com.axway.apim.setup.APIManagerSettingsApp.exportAPIManagerSetup(APIManagerSettingsApp.java:103)
        at com.axway.apim.setup.APIManagerSettingsApp.runExport(APIManagerSettingsApp.java:89)
        at com.axway.apim.setup.APIManagerSettingsApp.exportConfig(APIManagerSettingsApp.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:131)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:74)}

)
javax.net.ssl|FINE|01|main|2024-10-14 17:11:46.695 EEST|SSLSocketImpl.java:1619|close the underlying socket
javax.net.ssl|FINE|01|main|2024-10-14 17:11:46.695 EEST|SSLSocketImpl.java:1638|close the SSL connection (initiative)
2024-10-14 17:11:46,698 [APIManagerSettingsApp] ERROR: Can't login to API-Manager
                                 | Unable to send HTTP-Request.
com.axway.apim.lib.error.AppException: Can't login to API-Manager
        at com.axway.apim.adapter.APIManagerAdapter.loginToAPIManager(APIManagerAdapter.java:242)
        at com.axway.apim.adapter.APIManagerAdapter.getInstance(APIManagerAdapter.java:101)
        at com.axway.apim.setup.APIManagerSettingsApp.exportAPIManagerSetup(APIManagerSettingsApp.java:103)
        at com.axway.apim.setup.APIManagerSettingsApp.runExport(APIManagerSettingsApp.java:89)
        at com.axway.apim.setup.APIManagerSettingsApp.exportConfig(APIManagerSettingsApp.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:131)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:74)
Caused by: com.axway.apim.lib.error.AppException: Unable to send HTTP-Request.
        at com.axway.apim.lib.utils.rest.RestAPICall.sendRequest(RestAPICall.java:51)
        at com.axway.apim.lib.utils.rest.POSTRequest.execute(POSTRequest.java:20)
        at com.axway.apim.adapter.HttpHelper.execute(HttpHelper.java:13)
        at com.axway.apim.adapter.APIManagerAdapter.loginToAPIManager(APIManagerAdapter.java:222)
        ... 10 more
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:318)
        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1401)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1309)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.axway.apim.lib.utils.rest.RestAPICall.sendRequest(RestAPICall.java:46)
        ... 13 more
[root@SL2SUPPAPP21542 scripts]# ./apim.sh  apim settings get -s qa -k > output.txt
javax.net.ssl|FINE|01|main|2024-10-14 17:11:59.437 EEST|SSLCipher.java:438|jdk.tls.keyLimits:  entry = AES/GCM/NoPadding KeyUpdate 2^37. AES/GCM/NOPADDING:KEYUPDATE = 137438953472
javax.net.ssl|WARNING|01|main|2024-10-14 17:11:59.589 EEST|ServerNameExtension.java:261|Unable to indicate server name
javax.net.ssl|FINE|01|main|2024-10-14 17:11:59.589 EEST|SSLExtensions.java:260|Ignore, context unavailable extension: server_name
javax.net.ssl|FINE|01|main|2024-10-14 17:11:59.589 EEST|SSLExtensions.java:260|Ignore, context unavailable extension: status_request
javax.net.ssl|WARNING|01|main|2024-10-14 17:11:59.592 EEST|SignatureScheme.java:297|Signature algorithm, ed25519, is not supported by the underlying providers
javax.net.ssl|WARNING|01|main|2024-10-14 17:11:59.592 EEST|SignatureScheme.java:297|Signature algorithm, ed448, is not supported by the underlying providers
javax.net.ssl|INFO|01|main|2024-10-14 17:11:59.597 EEST|AlpnExtension.java:178|No available application protocols
javax.net.ssl|FINE|01|main|2024-10-14 17:11:59.597 EEST|SSLExtensions.java:260|Ignore, context unavailable extension: application_layer_protocol_negotiation
javax.net.ssl|FINE|01|main|2024-10-14 17:11:59.597 EEST|SSLExtensions.java:260|Ignore, context unavailable extension: status_request_v2
javax.net.ssl|FINE|01|main|2024-10-14 17:11:59.598 EEST|SSLExtensions.java:260|Ignore, context unavailable extension: cookie
javax.net.ssl|FINE|01|main|2024-10-14 17:11:59.615 EEST|SSLExtensions.java:260|Ignore, context unavailable extension: renegotiation_info
javax.net.ssl|FINE|01|main|2024-10-14 17:11:59.616 EEST|PreSharedKeyExtension.java:631|No session to resume.
javax.net.ssl|FINE|01|main|2024-10-14 17:11:59.616 EEST|SSLExtensions.java:260|Ignore, context unavailable extension: pre_shared_key
javax.net.ssl|FINE|01|main|2024-10-14 17:11:59.619 EEST|ClientHello.java:564|Produced ClientHello handshake message (
"ClientHello": {
  "client version"      : "TLSv1.2",
  "random"              : "56 2A 71 DD D6 03 75 88 77 42 E4 58 01 B7 16 52 B5 98 16 24 FB 80 A6 23 17 F3 BB 5C 75 E2 66 32",
  "session id"          : "CF 47 13 D9 30 40 B5 77 2C AA 9B 22 2C F2 12 31 76 BC 8D 2A 9A 09 5D 1D 8E F1 8C F8 BF 75 1D 33",
  "cipher suites"       : "[TLS_AES_256_GCM_SHA384(0x1302), TLS_AES_128_GCM_SHA256(0x1301), TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384(0xC02C), TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256(0xC02B), TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384(0xC030), TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256(0xC02F), TLS_DHE_RSA_WITH_AES_256_GCM_SHA384(0x009F), TLS_DHE_RSA_WITH_AES_128_GCM_SHA256(0x009E), TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384(0xC024), TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384(0xC028), TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256(0xC023), TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256(0xC027), TLS_DHE_RSA_WITH_AES_256_CBC_SHA256(0x006B), TLS_DHE_RSA_WITH_AES_128_CBC_SHA256(0x0067), TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA(0xC00A), TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA(0xC014), TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA(0xC009), TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA(0xC013), TLS_DHE_RSA_WITH_AES_256_CBC_SHA(0x0039), TLS_DHE_RSA_WITH_AES_128_CBC_SHA(0x0033), TLS_RSA_WITH_AES_256_GCM_SHA384(0x009D), TLS_RSA_WITH_AES_128_GCM_SHA256(0x009C), TLS_RSA_WITH_AES_256_CBC_SHA256(0x003D), TLS_RSA_WITH_AES_128_CBC_SHA256(0x003C), TLS_RSA_WITH_AES_256_CBC_SHA(0x0035), TLS_RSA_WITH_AES_128_CBC_SHA(0x002F), TLS_EMPTY_RENEGOTIATION_INFO_SCSV(0x00FF)]",
  "compression methods" : "00",
  "extensions"          : [
    "supported_groups (10)": {
      "versions": [secp256r1, secp384r1, secp521r1, ffdhe2048, ffdhe3072, ffdhe4096, ffdhe6144, ffdhe8192]
    },
    "ec_point_formats (11)": {
      "formats": [uncompressed]
    },
    "signature_algorithms (13)": {
      "signature schemes": [ecdsa_secp256r1_sha256, ecdsa_secp384r1_sha384, ecdsa_secp521r1_sha512, rsa_pss_rsae_sha256, rsa_pss_rsae_sha384, rsa_pss_rsae_sha512, rsa_pss_pss_sha256, rsa_pss_pss_sha384, rsa_pss_pss_sha512, rsa_pkcs1_sha256, rsa_pkcs1_sha384, rsa_pkcs1_sha512, ecdsa_sha224, rsa_sha224]
    },
    "signature_algorithms_cert (50)": {
      "signature schemes": [ecdsa_secp256r1_sha256, ecdsa_secp384r1_sha384, ecdsa_secp521r1_sha512, rsa_pss_rsae_sha256, rsa_pss_rsae_sha384, rsa_pss_rsae_sha512, rsa_pss_pss_sha256, rsa_pss_pss_sha384, rsa_pss_pss_sha512, rsa_pkcs1_sha256, rsa_pkcs1_sha384, rsa_pkcs1_sha512, ecdsa_sha224, rsa_sha224]
    },
    "extended_master_secret (23)": {
      <empty>
    },
    "supported_versions (43)": {
      "versions": [TLSv1.3, TLSv1.2]
    },
    "psk_key_exchange_modes (45)": {
      "ke_modes": [psk_dhe_ke]
    },
    "key_share (51)": {
      "client_shares": [
        {
          "named group": secp256r1
          "key_exchange": {
            0000: 04 E6 30 94 1B 70 55 41   46 17 64 9C 39 82 15 96  ..0..pUAF.d.9...
            0010: 2D 94 E2 BF 48 A8 2A 9E   AB 53 05 3F 5F E2 0A 1D  -...H.*..S.?_...
            0020: E0 F7 9D 70 95 29 BC C7   87 C3 02 D7 76 76 22 73  ...p.)......vv"s
            0030: 70 23 C4 6B 42 4B E7 51   04 CB 22 3C 04 22 6F E7  p#.kBK.Q.."<."o.
            0040: 85
          }
        },
      ]
    }
  ]
}
)
javax.net.ssl|FINE|01|main|2024-10-14 17:11:59.622 EEST|Alert.java:238|Received alert message (
"Alert": {
  "level"      : "fatal",
  "description": "handshake_failure"
}
)
javax.net.ssl|SEVERE|01|main|2024-10-14 17:11:59.624 EEST|TransportContext.java:323|Fatal (HANDSHAKE_FAILURE): Received fatal alert: handshake_failure (
"throwable" : {
  javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:318)
        at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
        at sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:152)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1401)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1309)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.axway.apim.lib.utils.rest.RestAPICall.sendRequest(RestAPICall.java:46)
        at com.axway.apim.lib.utils.rest.POSTRequest.execute(POSTRequest.java:20)
        at com.axway.apim.adapter.HttpHelper.execute(HttpHelper.java:13)
        at com.axway.apim.adapter.APIManagerAdapter.loginToAPIManager(APIManagerAdapter.java:222)
        at com.axway.apim.adapter.APIManagerAdapter.getInstance(APIManagerAdapter.java:101)
        at com.axway.apim.setup.APIManagerSettingsApp.exportAPIManagerSetup(APIManagerSettingsApp.java:103)
        at com.axway.apim.setup.APIManagerSettingsApp.runExport(APIManagerSettingsApp.java:89)
        at com.axway.apim.setup.APIManagerSettingsApp.exportConfig(APIManagerSettingsApp.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:131)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:74)}

)
javax.net.ssl|FINE|01|main|2024-10-14 17:11:59.624 EEST|SSLSocketImpl.java:1619|close the underlying socket
javax.net.ssl|FINE|01|main|2024-10-14 17:11:59.625 EEST|SSLSocketImpl.java:1638|close the SSL connection (initiative)
[root@SL2SUPPAPP21542 scripts]# ll
```

**Comment by biancaatsh** [comment]
RHEL 9 may have different configurations for OpenSSL or GnuTLS that prioritize stronger encryption algorithms or protocols. These configurations might block weaker encryption protocols that RHEL 8 allows.
You can check the system-wide cryptographic policies on RHEL 9:
update-crypto-policies --show
If it's set to a strict profile like FIPS or DEFAULT, it may disallow certain algorithms or protocols.

Solution was the following command: sudo update-crypto-policies --set LEGACY
