### ISSUE TITLE
Api update failing if swagger version remains the same

### ISSUE THREAD

**Issue by gurpreetbhatoa** [Axway-API-Management-Plus/apim-cli#515]
### APIM-CLI version

apim-cli-1.14.5

### API-Management version

7.7.20240530

### Question

Hi There,

I am getting the following error in our build pipeline if we are pushing the same version of swagger file via cli to axway portal:

`[APIImportManager] DEBUG: No changes detected between Import- and API-Manager-API. Exiting now...
[APIImportApp] WARN : No changes detected between Import- and API-Manager-API: 'App' (aaa-bbb-ccc)
com.axway.apim.lib.error.AppException: No changes detected between Import- and API-Manager-API: 'App' (aaa-bbb-ccc)
at com.axway.apim.apiimport.APIImportManager.applyChanges(APIImportManager.java:57)
at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:94)
at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:130)
at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:72)
[APIManagerAdapter] DEBUG: Closing cache ...
[RestAPICall] DEBUG: Http verb:DELETE and URI: https://interway-axway-url
Failing task since return code of [/bin/sh ScriptBuildTask-6653613491816150482.sh] was 10 while expected 0
Finished task 'Deploy swagger changes' with result: Failed`

If there any setting which I could use to overwrite the swagger file even if version is same?
Also not sure what exit code 10 means, unable to find it in the documentation either.

Any help will be appreciated.

**Comment by rathnapandi** [comment]
Use the flag -forceUpdate to override the api.  all error codes are documented on https://github.com/Axway-API-Management-Plus/apim-cli/wiki/9.6-Error-Codes

**Comment by gurpreetbhatoa** [comment]
Thank you. Was looking at 9.1 error codes documentation.
