### ISSUE TITLE
Api import error with apps

### ISSUE THREAD

**Issue by olitho74** [Axway-API-Management-Plus/apim-cli#521]
### APIM-CLI version

1.14.1

### API-Management version

7.7.0

### Bug description

When I execute import command in Azure devops pipeline : 

Formatted command: exec bash '/home/tfs/axway-apim/apim-cli/scripts/apim.sh' - - api import  - --apidefinition https://coreapi-addresses.qual.apps.sig-ge.ch/swagger/v1/swagger.json  - --config ../DevopsTemplates/axway/api/rest-int-apikey-apikey/api-config.json - --host v966.sig-ge.ch  - --username apiadmin  - --password ***  - -port 8075  - -overrideSpecBasePath - -clearCache ALL - -force  - -ignoreCache  - -clientAppsMode add

I get an error once every 3 or 4 times.

Error is : 

2024-11-12 11:08:34,797 [APIImportApp] ERROR: Cannot read APIs from API-Manager
                                 | Error cant load subscribes applications from API-Manager.
com.axway.apim.lib.error.AppException: Cannot read APIs from API-Manager
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPIs(APIManagerAPIAdapter.java:99)
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPI(APIManagerAPIAdapter.java:105)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:93)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:133)
	at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:77)
Caused by: com.axway.apim.lib.error.AppException: Error cant load subscribes applications from API-Manager.
	at com.axway.apim.adapter.client.apps.APIMgrAppsAdapter.getAppsSubscribedWithAPI(APIMgrAppsAdapter.java:161)
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.addClientApplications(APIManagerAPIAdapter.java:431)
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPIs(APIManagerAPIAdapter.java:87)

**Comment by rathnapandi** [comment]
Can  you update the CLI to the latest version and test it again?

**Comment by olitho74** [comment]
Here is the DEBUG trace with the latest CLI  : 1.14.8

It happens once each 2 or 3 times  :

```
2024-11-14T05:52:25.5139258Z ##[section]Starting: Deploy API to qual - internal
2024-11-14T05:52:25.5145177Z ==============================================================================
2024-11-14T05:52:25.5145365Z Task         : Bash
2024-11-14T05:52:25.5145438Z Description  : Run a Bash script on macOS, Linux, or Windows
2024-11-14T05:52:25.5145590Z Version      : 3.246.1
2024-11-14T05:52:25.5145706Z Author       : Microsoft Corporation
2024-11-14T05:52:25.5145791Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
2024-11-14T05:52:25.5145945Z ==============================================================================
2024-11-14T05:52:25.6580502Z Generating script.
2024-11-14T05:52:25.6591806Z Formatted command: exec bash '/home/tfs/axway-apim/apim-cli/scripts/apim.sh' - - api import  - --apidefinition https://coreapi-digital.qual.apps.sig-ge.ch/swagger/v1/swagger.json  - --config ../DevopsTemplates/axway/api/rest-int-apikey-apikey/api-config.json - --host v966.sig-ge.ch  - --username apiadmin  - --password ***  - -port 8075  - -overrideSpecBasePath - -clearCache ALL - -force  - -ignoreCache  - -clientAppsMode add
2024-11-14T05:52:25.6593499Z ========================== Starting Command Output ===========================
2024-11-14T05:52:25.6600140Z [command]/usr/bin/bash /home/tfs/agent/_work/_temp/1d3ec7a6-bc59-4669-bfc0-831a6ab49b47.sh
2024-11-14T05:52:26.4761743Z [34m2024-11-14 06:52:26,473 [APIManagerCLI] INFO : API-Manager CLI: 1.14.8
2024-11-14T05:52:26.4763164Z [m[m2024-11-14 06:52:26,475 [APIManagerCLI] DEBUG: API-Manager CLI args: [-, -, api, import, -, --apidefinition, https://coreapi-digital.qual.apps.sig-ge.ch/swagger/v1/swagger.json, -, --config, ../DevopsTemplates/axway/api/rest-int-apikey-apikey/api-config.json, -, --host, v966.sig-ge.ch, -, --username, apiadmin, -, --password, ***, -, -port, 8075, -, -overrideSpecBasePath, -, -clearCache, ALL, -, -force, -, -ignoreCache, -, -clientAppsMode, add]
2024-11-14T05:52:26.4764047Z [m[m2024-11-14 06:52:26,475 [APIManagerCLI] DEBUG: Java Version: 17.0.13
2024-11-14T05:52:26.4765314Z [m[34m2024-11-14 06:52:26,475 [APIManagerCLI] INFO : Module: API - I M P O R T  (1.14.8)
2024-11-14T05:52:26.4814851Z [m[m2024-11-14 06:52:26,481 [EnvironmentProperties] DEBUG: Trying to load environment properties from file: env.properties ... not found.
2024-11-14T05:52:26.5788428Z [m[34m2024-11-14 06:52:26,578 [APIManagerAdapter] INFO : Cache: applicationsQuotaCache successfully cleared.
2024-11-14T05:52:26.5806085Z [m[34m2024-11-14 06:52:26,580 [APIManagerAdapter] INFO : Cache: organizationCache successfully cleared.
2024-11-14T05:52:26.5834888Z [m[34m2024-11-14 06:52:26,583 [APIManagerAdapter] INFO : Cache: applicationAPIAccessCache successfully cleared.
2024-11-14T05:52:26.5835328Z [m[34m2024-11-14 06:52:26,583 [APIManagerAdapter] INFO : Cache: organizationAPIAccessCache successfully cleared.
2024-11-14T05:52:26.5896405Z [m[34m2024-11-14 06:52:26,589 [APIManagerAdapter] INFO : Cache: oauthClientProviderCache successfully cleared.
2024-11-14T05:52:26.5923112Z [m[34m2024-11-14 06:52:26,591 [APIManagerAdapter] INFO : Cache: applicationsCache successfully cleared.
2024-11-14T05:52:26.5923572Z [m[34m2024-11-14 06:52:26,591 [APIManagerAdapter] INFO : Cache: applicationsSubscriptionCache successfully cleared.
2024-11-14T05:52:26.5923976Z [m[34m2024-11-14 06:52:26,591 [APIManagerAdapter] INFO : Cache: applicationsCredentialCache successfully cleared.
2024-11-14T05:52:26.5924519Z [m[34m2024-11-14 06:52:26,591 [APIManagerAdapter] INFO : Cache: applicationsQuotaCache successfully cleared.
2024-11-14T05:52:26.5935134Z [m[34m2024-11-14 06:52:26,593 [APIManagerAdapter] INFO : Cache: userCache successfully cleared.
2024-11-14T05:52:26.7859166Z [m[m2024-11-14 06:52:26,785 [APIMHttpClient] DEBUG: API Manager CLI http client timeout : 30000
2024-11-14T05:52:26.8318176Z [m[m2024-11-14 06:52:26,831 [RestAPICall] DEBUG: Http verb:POST and URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/login
2024-11-14T05:52:27.1139312Z [m[m2024-11-14 06:52:27,113 [RestAPICall] DEBUG: Http verb:GET and URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/currentuser
2024-11-14T05:52:27.2169600Z [m[m2024-11-14 06:52:27,216 [RestAPICall] DEBUG: Http verb:GET and URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/config
2024-11-14T05:52:27.3022027Z [m[34m2024-11-14 06:52:27,301 [APIManagerAdapter] INFO : Successfully connected to API-Manager (7.7.20240228) on: https://v966.sig-ge.ch:8075
2024-11-14T05:52:27.3108604Z [m[m2024-11-14 06:52:27,310 [Utils] DEBUG: Handling JSON Configuration file: ../DevopsTemplates/axway/api/rest-int-apikey-apikey/api-config.json
2024-11-14T05:52:27.4238223Z [m[m2024-11-14 06:52:27,423 [APIManagerOrganizationAdapter] DEBUG: Load organizations from API-Manager using filter: OrgFilter [name=SIG, id=null]
2024-11-14T05:52:27.4239889Z [m[m2024-11-14 06:52:27,423 [APIManagerOrganizationAdapter] DEBUG: Load organization with URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/organizations?field=name&op=eq&value=SIG
2024-11-14T05:52:27.4244044Z [m[m2024-11-14 06:52:27,423 [RestAPICall] DEBUG: Http verb:GET and URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/organizations?field=name&op=eq&value=SIG
2024-11-14T05:52:27.6770918Z [m[m2024-11-14 06:52:27,676 [APISpecificationFactory] DEBUG: GET https://coreapi-digital.qual.apps.sig-ge.ch/swagger/v1/swagger.json : 200 
2024-11-14T05:52:27.7160927Z [m[m2024-11-14 06:52:27,715 [APISpecificationFactory] DEBUG: Handle API-Specification: {
2024-11-14T05:52:27.7161279Z   "openapi": "3.0.1",
2024-11-14T05:52:27.7161502Z   "info": {
2024-11-14T05:52:27.7161834Z     "title": "API Core Digital - Acces aux informations necessaires aux solutions digitales",
2024-11-14T05:52:27.7162334Z     "description": "Cette API reutilisable permet d'acceder aux donnee... , apiDefinitionFile: https://coreapi-digital.qual.apps.sig-ge.ch/swagger/v1/swagger.json , API Name : API Core Digital 
2024-11-14T05:52:27.7292309Z [m[m2024-11-14 06:52:27,728 [APISpecification] DEBUG: JSON API-Definition detected
2024-11-14T05:52:27.7401790Z [m[m2024-11-14 06:52:27,739 [OAS3xSpecification] DEBUG: openapi tag value : "3.0.1"
2024-11-14T05:52:27.7422059Z [m[34m2024-11-14 06:52:27,741 [APISpecificationFactory] INFO : Detected: Open API 3.0 specification. 
2024-11-14T05:52:27.7424689Z [m[34m2024-11-14 06:52:27,742 [OAS3xSpecification] INFO : overriding openapi Servers url with value : https://coreapi-digital.qual.apps.sig-ge.ch
2024-11-14T05:52:27.7525599Z [m[34m2024-11-14 06:52:27,750 [APIImportConfigAdapter] INFO : Loading image from: /home/tfs/agent/_work/352/DevopsTemplates/axway/api/rest-int-apikey-apikey/api-image.jpg
2024-11-14T05:52:27.7585345Z [m[m2024-11-14 06:52:27,758 [APIManagerCustomPropertiesAdapter] DEBUG: Read configured custom properties from API-Manager
2024-11-14T05:52:27.7590764Z [m[m2024-11-14 06:52:27,758 [RestAPICall] DEBUG: Http verb:GET and URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/config/customproperties
2024-11-14T05:52:27.8151902Z [m[m2024-11-14 06:52:27,814 [RestAPICall] DEBUG: Http verb:POST and URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/certinfo
2024-11-14T05:52:27.8587841Z [m[m2024-11-14 06:52:27,858 [RestAPICall] DEBUG: Http verb:POST and URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/certinfo
2024-11-14T05:52:27.8913213Z [m[34m2024-11-14 06:52:27,890 [APIImportConfigAdapter] INFO : Handling configured client-applications.
2024-11-14T05:52:27.8944795Z [m[m2024-11-14 06:52:27,894 [APIMgrAppsAdapter] DEBUG: Sending request to find existing applications: https://v966.sig-ge.ch:8075/api/portal/v1.4/applications?field=name&op=eq&value=API-Qual-Ext
2024-11-14T05:52:27.8947881Z [m[m2024-11-14 06:52:27,894 [RestAPICall] DEBUG: Http verb:GET and URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/applications?field=name&op=eq&value=API-Qual-Ext
2024-11-14T05:52:28.0281197Z [m[m2024-11-14 06:52:28,027 [APIManagerOrganizationAdapter] DEBUG: Load organizations from API-Manager using filter: OrgFilter [name=null, id=f1525daa-e17f-4810-94f0-630734d87899]
2024-11-14T05:52:28.0281835Z [m[m2024-11-14 06:52:28,027 [APIManagerOrganizationAdapter] DEBUG: Load organization with URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/organizations/f1525daa-e17f-4810-94f0-630734d87899
2024-11-14T05:52:28.0282804Z [m[m2024-11-14 06:52:28,027 [RestAPICall] DEBUG: Http verb:GET and URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/organizations/f1525daa-e17f-4810-94f0-630734d87899
2024-11-14T05:52:28.0482341Z [m[m2024-11-14 06:52:28,047 [APIManagerOrganizationAdapter] DEBUG: Organization id to be cached : /f1525daa-e17f-4810-94f0-630734d87899
2024-11-14T05:52:28.0486843Z [m[m2024-11-14 06:52:28,048 [APIMgrAppsAdapter] DEBUG: Found: 1 applications
2024-11-14T05:52:28.0495333Z [m[34m2024-11-14 06:52:28,049 [APIImportConfigAdapter] INFO : Application exists : API-Qual-Ext (null)]
2024-11-14T05:52:28.0496729Z [m[m2024-11-14 06:52:28,049 [RestAPICall] DEBUG: Http verb:GET and URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/config
2024-11-14T05:52:28.0674297Z [m[34m2024-11-14 06:52:28,066 [APIImportApp] INFO : Lookup actual API based on Path: /digital/v1  
2024-11-14T05:52:28.0718329Z [m[m2024-11-14 06:52:28,071 [RestAPICall] DEBUG: Http verb:GET and URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/proxies?field=path&op=eq&value=%2Fdigital%2Fv1
2024-11-14T05:52:28.1834054Z [m[m2024-11-14 06:52:28,182 [APIManagerAPIAdapter] DEBUG: Found: 1 exposed API(s): 
2024-11-14T05:52:28.1892137Z [m[m2024-11-14 06:52:28,188 [APIManagerAPIMethodAdapter] DEBUG: Load API-Methods for API: e9189c20-2152-4996-b390-d93ed809d056 from API-Manager
2024-11-14T05:52:28.1894903Z [m[m2024-11-14 06:52:28,189 [RestAPICall] DEBUG: Http verb:GET and URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/proxies/e9189c20-2152-4996-b390-d93ed809d056/operations
2024-11-14T05:52:28.2412249Z [m[m2024-11-14 06:52:28,240 [APIManagerQuotaAdapter] DEBUG: Load quotas with ID: 00000000-0000-0000-0000-000000000001 from API-Manager URI : https://v966.sig-ge.ch:8075/api/portal/v1.4/quotas/00000000-0000-0000-0000-000000000001
2024-11-14T05:52:28.2416619Z [m[m2024-11-14 06:52:28,241 [RestAPICall] DEBUG: Http verb:GET and URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/quotas/00000000-0000-0000-0000-000000000001
2024-11-14T05:52:28.2629504Z [m[m2024-11-14 06:52:28,262 [APIManagerQuotaAdapter] DEBUG: Load quotas with ID: 00000000-0000-0000-0000-000000000000 from API-Manager URI : https://v966.sig-ge.ch:8075/api/portal/v1.4/quotas/00000000-0000-0000-0000-000000000000
2024-11-14T05:52:28.2668990Z [m[m2024-11-14 06:52:28,263 [RestAPICall] DEBUG: Http verb:GET and URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/quotas/00000000-0000-0000-0000-000000000000
2024-11-14T05:52:28.2886283Z [m[m2024-11-14 06:52:28,288 [RestAPICall] DEBUG: Http verb:GET and URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/proxies/e9189c20-2152-4996-b390-d93ed809d056/apiaccess
2024-11-14T05:52:28.3548709Z [m[m2024-11-14 06:52:28,353 [APIMgrAppsAdapter] DEBUG: Load subscribed applications for API-ID: e9189c20-2152-4996-b390-d93ed809d056 from API-Manager
2024-11-14T05:52:28.3553090Z [m[m2024-11-14 06:52:28,354 [RestAPICall] DEBUG: Http verb:GET and URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/proxies/e9189c20-2152-4996-b390-d93ed809d056/applications
2024-11-14T05:52:28.4749756Z [m[1;31m2024-11-14 06:52:28,473 [APIImportApp] ERROR: Cannot read APIs from API-Manager
2024-11-14T05:52:28.4750186Z                                  | Error cant load subscribes applications from API-Manager.
2024-11-14T05:52:28.4750519Z com.axway.apim.lib.error.AppException: Cannot read APIs from API-Manager
2024-11-14T05:52:28.4750821Z 	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPIs(APIManagerAPIAdapter.java:109)
2024-11-14T05:52:28.4751166Z 	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPI(APIManagerAPIAdapter.java:115)
2024-11-14T05:52:28.4751465Z 	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:94)
2024-11-14T05:52:28.4751732Z 	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:52)
2024-11-14T05:52:28.4751989Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-11-14T05:52:28.4752783Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2024-11-14T05:52:28.4753139Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-11-14T05:52:28.4753441Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2024-11-14T05:52:28.4753715Z 	at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:133)
2024-11-14T05:52:28.4754032Z 	at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:72)
2024-11-14T05:52:28.4754461Z Caused by: com.axway.apim.lib.error.AppException: Error cant load subscribes applications from API-Manager.
2024-11-14T05:52:28.4754854Z 	at com.axway.apim.adapter.client.apps.APIMgrAppsAdapter.getAppsSubscribedWithAPI(APIMgrAppsAdapter.java:158)
2024-11-14T05:52:28.4755272Z 	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.addClientApplications(APIManagerAPIAdapter.java:459)
2024-11-14T05:52:28.4755650Z 	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPIs(APIManagerAPIAdapter.java:97)
2024-11-14T05:52:28.4761477Z 	... 9 more
2024-11-14T05:52:28.4761927Z Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<com.axway.apim.api.model.apps.ClientApplication>` from Object value (token `JsonToken.START_OBJECT`)
2024-11-14T05:52:28.4762445Z  at [Source: (String)"{"errors":[{"code":102,"message":"The entity could not be found.  Please refresh your session."}]}"; line: 1, column: 1]
2024-11-14T05:52:28.4762874Z 	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
2024-11-14T05:52:28.4763277Z 	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1752)
2024-11-14T05:52:28.4763689Z 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1526)
2024-11-14T05:52:28.4764204Z 	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1473)
2024-11-14T05:52:28.4764814Z 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:396)
2024-11-14T05:52:28.4765212Z 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:252)
2024-11-14T05:52:28.4765630Z 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
2024-11-14T05:52:28.4766036Z 	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
2024-11-14T05:52:28.4766438Z 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
2024-11-14T05:52:28.4766786Z 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
2024-11-14T05:52:28.4767127Z 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3755)
2024-11-14T05:52:28.4767576Z 	at com.axway.apim.adapter.client.apps.APIMgrAppsAdapter.getAppsSubscribedWithAPI(APIMgrAppsAdapter.java:155)
2024-11-14T05:52:28.4767901Z 	... 11 more
2024-11-14T05:52:28.4768277Z [m[m2024-11-14 06:52:28,475 [APIManagerAdapter] DEBUG: Closing cache ...
2024-11-14T05:52:28.4775353Z [m[m2024-11-14 06:52:28,477 [RestAPICall] DEBUG: Http verb:DELETE and URI: https://v966.sig-ge.ch:8075/api/portal/v1.4/login
2024-11-14T05:52:28.5106692Z [m
2024-11-14T05:52:28.5144450Z ##[error]Bash exited with code '60'.
2024-11-14T05:52:28.5155978Z ##[section]Finishing: Deploy API to qual - internal
```

**Comment by rathnapandi** [comment]
API manager is returning an error when CLI tries to retrieve all applications associated with the API.  
Can you share the error from API Gateway log? Also, we are seeing the error at 2024-11-14T05:52:25.5139258Z when was the api created before / ran the pipeline? (this will help us to understand any issues related API manager cache)

**Comment by olitho74** [comment]
Hi,
I depublished the API , and I ran again the pipeline, and then it works.
At the end, the api is in the status 'published', but now updates are not on error anymore.

I confirmed with another API deployment. 
It looks like, sometimes, the API needs to be in the unpublished state to be upatable.
But sometimes, it works even when status is published.

This is something quiet new we can see. We did an upgrader in July of our Gateway version. It could be related, and maybe we did not have the case since the migration. 
I keep monitoring this subject.

thanks,

Olivier

**Comment by rathnapandi** [comment]
Sure, keep me posted. 

Thanks
Rathna

**Comment by rathnapandi** [comment]
Unable to reproduce. @olitho74  please reopen if you see the issue again.
