### ISSUE TITLE
When try to promote an API in an environment you get an error.

### ISSUE THREAD

**Issue by GennaroRiccio** [Axway-API-Management-Plus/apim-cli#525]
### APIM-CLI version

1.14.7

### API-Management version

7.7-20220830

### Bug description

Hi,
When I try to promote a configuration in the next environment I get this error.
If I import the same swagger file from the user interface this works without error.

In a previous environment via CLI worked without errors.

Thank's

### Steps to reproduce

apim api import -s preprod -c .\api-config.json -a .\inquiry-contratto-bff.json -force

### Relevant log output

```shell
2024-12-16 13:49:39,004 [APIManagerCLI] INFO : API-Manager CLI: 1.14.7
2024-12-16 13:49:39,007 [APIManagerCLI] DEBUG: Java Version: 21.0.5
2024-12-16 13:49:39,008 [APIManagerCLI] INFO : Module: API - I M P O R T  (1.14.7)
2024-12-16 13:49:39,014 [EnvironmentProperties] DEBUG: Trying to load environment properties from file: D:\apim-cli/conf/env.properties ... not found.
2024-12-16 13:49:39,022 [EnvironmentProperties] DEBUG: Loaded environment properties from file: D:\apim-cli/conf/env.preprod.properties
2024-12-16 13:49:39,365 [APIMHttpClient] DEBUG: API Manager CLI http client timeout : 30000
2024-12-16 13:49:39,419 [RestAPICall] DEBUG: Http verb:POST and URI: https://manager.cloud-preprod.cippolippo.it.it/api/portal/v1.4/login
2024-12-16 13:49:39,888 [RestAPICall] DEBUG: Http verb:GET and URI: https://manager.cloud-preprod.cippolippo.it.it/api/portal/v1.4/currentuser
2024-12-16 13:49:40,008 [RestAPICall] DEBUG: Http verb:GET and URI: https://manager.cloud-preprod.cippolippo.it.it/api/portal/v1.4/config
2024-12-16 13:49:40,085 [APIManagerAdapter] INFO : Successfully connected to API-Manager (7.7.20220830) on: https://manager.cloud-preprod.cippolippo.it.it
2024-12-16 13:49:40,091 [Utils] DEBUG: No stage provided
2024-12-16 13:49:40,095 [Utils] DEBUG: Handling JSON Configuration file: .\api-config.json
2024-12-16 13:49:40,191 [APIManagerOrganizationAdapter] DEBUG: Load organizations from API-Manager using filter: OrgFilter [name=API Development, id=null]
2024-12-16 13:49:40,191 [APIManagerOrganizationAdapter] DEBUG: Load organization with URI: https://manager.cloud-preprod.cippolippo.it.it/api/portal/v1.4/organizations?field=name&op=eq&value=API+Development
2024-12-16 13:49:40,191 [RestAPICall] DEBUG: Http verb:GET and URI: https://manager.cloud-preprod.cippolippo.it.it/api/portal/v1.4/organizations?field=name&op=eq&value=API+Development
2024-12-16 13:49:40,240 [APISpecificationFactory] INFO : Reading API-Definition (Swagger/WSDL) from file: inquiry-contratto-bff.json (relative path)
2024-12-16 13:49:40,264 [APISpecificationFactory] DEBUG: Handle API-Specification: {
  "servers": [
    {
      "url": "http://inquiry-contratto-bff.contratti-collaudo.svc.cluster.local/api/v2"
    }
  ],
  "openapi": "3.0.1",
  "info": {
    "title": "inquiry-contratto-bff"... , apiDefinitionFile: inquiry-contratto-bff.json , API Name : inquiry-contratto-bff 
2024-12-16 13:49:40,292 [APISpecification] DEBUG: JSON API-Definition detected
2024-12-16 13:49:40,327 [OAS3xSpecification] DEBUG: openapi tag value : "3.0.1"
2024-12-16 13:49:40,327 [APISpecificationFactory] INFO : Detected: Open API 3.0 specification. 
2024-12-16 13:49:40,345 [APIManagerCustomPropertiesAdapter] DEBUG: Read configured custom properties from API-Manager
2024-12-16 13:49:40,345 [RestAPICall] DEBUG: Http verb:GET and URI: https://manager.cloud-preprod.cippolippo.it.it/api/portal/v1.4/config/customproperties
2024-12-16 13:49:40,386 [RestAPICall] DEBUG: Http verb:GET and URI: https://manager.cloud-preprod.cippolippo.it.it/api/portal/v1.4/config
2024-12-16 13:49:40,450 [APIImportApp] INFO : Lookup actual API based on Path: /newage/inquiry-contratto/bff/api/v2 , V-Host: vittoria-internal-private.cloud-collaudo.cippolippo.it.it 
2024-12-16 13:49:40,454 [RestAPICall] DEBUG: Http verb:GET and URI: https://manager.cloud-preprod.cippolippo.it.it/api/portal/v1.4/proxies?field=path&op=eq&value=%2Fnewage%2Finquiry-contratto%2Fbff%2Fapi%2Fv2
2024-12-16 13:49:40,748 [APIManagerOrganizationAdapter] DEBUG: Load organizations from API-Manager using filter: OrgFilter [name=null, id=7e4ee97a-c267-4d6e-b476-47638f2f4782]
2024-12-16 13:49:40,748 [APIManagerOrganizationAdapter] DEBUG: Load organization with URI: https://manager.cloud-preprod.cippolippo.it.it/api/portal/v1.4/organizations/7e4ee97a-c267-4d6e-b476-47638f2f4782
2024-12-16 13:49:40,748 [RestAPICall] DEBUG: Http verb:GET and URI: https://manager.cloud-preprod.cippolippo.it.it/api/portal/v1.4/organizations/7e4ee97a-c267-4d6e-b476-47638f2f4782
2024-12-16 13:49:40,780 [APIManagerOrganizationAdapter] DEBUG: Organization id to be cached : /7e4ee97a-c267-4d6e-b476-47638f2f4782
2024-12-16 13:49:40,786 [APIManagerAPIAdapter] DEBUG: No existing API found based on filter: [apiPath=/newage/inquiry-contratto/bff/api/v2 vHost=vittoria-internal-private.cloud-collaudo.cippolippo.it.it]
2024-12-16 13:49:40,788 [APIChangeState] DEBUG: No existing API found. Creating  complete new API
2024-12-16 13:49:40,789 [APIImportManager] INFO : No existing API found, creating new!
2024-12-16 13:49:40,790 [APIManagerAPIAdapter] DEBUG: Import backend API: inquiry-contratto-bff based on Open API 3.0 specification.
2024-12-16 13:49:40,796 [RestAPICall] DEBUG: Http verb:POST and URI: https://manager.cloud-preprod.cippolippo.it.it/api/portal/v1.4/apirepo/import/
2024-12-16 13:49:41,154 [APIManagerAPIAdapter] ERROR: Error importing API-Specification (Open API 3.0) to create Backend-API using URI: https://manager.cloud-preprod.cippolippo.it.it/api/portal/v1.4/apirepo/import/ Received Status-Code: 400 Response: {"errors":[{"code":400,"message":"Malformed OAS3 document: attribute paths.'/contratti/{codiceCliente}/preventivi'(get).responses.200.content.'text/plain'.schema.#/components/schemas/PreventivoDto is missing"}]}
2024-12-16 13:49:41,161 [APIImportApp] ERROR: Can't import definition / Create BE-API.
                                 | Can't import API-Specification to create Backend-API.
com.axway.apim.lib.error.AppException: Can't import definition / Create BE-API.
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.importBackendAPI(APIManagerAPIAdapter.java:800)
	at com.axway.apim.apiimport.actions.CreateNewAPI.execute(CreateNewAPI.java:48)
	at com.axway.apim.apiimport.APIImportManager.applyChanges(APIImportManager.java:47)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:96)
	at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:52)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:130)
	at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:72)
Caused by: com.axway.apim.lib.error.AppException: Can't import API-Specification to create Backend-API.
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.createBackend(APIManagerAPIAdapter.java:863)
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.importFromSwagger(APIManagerAPIAdapter.java:851)
	at com.axway.apim.adapter.apis.APIManagerAPIAdapter.importBackendAPI(APIManagerAPIAdapter.java:792)
	... 8 more
2024-12-16 13:49:41,164 [APIManagerAdapter] DEBUG: Closing cache ...
2024-12-16 13:49:41,165 [RestAPICall] DEBUG: Http verb:DELETE and URI: https://manager.cloud-preprod.cippolippo.it.it/api/portal/v1.4/login
```

**Comment by rathnapandi** [comment]
Hi @GennaroRiccio, 

Can you confirm whether you run the same version of Axway apim on dev and preprod? The API manager is complaining about open api specification, can you check api gateway logs and validate the spec?

Thanks
Rathna

**Comment by GennaroRiccio** [comment]
Hi @rathnapandi 
I have 4 env Test,Stage,PreProd,Production

Test and Stage API Manager version is 7.7.0.20231130, PreProd and Production at moment the version is 7.7-20220830

But 2 weeks ago the test ( 7.7.0.20231130) and staging (7.7-20220830) versions were different and I did not encounter any problems

Is there a workaround we can apply?

If the swgger file is identical and from the GUI it works, how come from apim-cli we get this error? 

This is the error from the API Manager:

```
<html>
<body>
<!--StartFragment-->
ERROR 17/Dec/2024:08:09:13.772 [15d0:000000000000000000000000] Exception ocurred while trying to retrieve service:
--
com.vordel.api.common.BadRequestException: Malformed OAS3 document: attribute paths.'/contratti/{codiceCliente}/preventivi'(get).responses.200.content.'text/plain'.schema.#/components/schemas/PreventivoDto is missing
at com.vordel.apiportal.config.OAS3ResourceValidator.validate(OAS3ResourceValidator.java:58)
at com.vordel.apiportal.config.OAS3ResourceValidator.getDocument(OAS3ResourceValidator.java:33)
at com.vordel.apiportal.config.OAS3ResourceValidator.getDocument(OAS3ResourceValidator.java:21)
at com.vordel.apiportal.config.BaseResourceValidator.validate(BaseResourceValidator.java:18)
at com.vordel.apiportal.config.ServiceRetriever.commit(ServiceRetriever.java:57)
at com.vordel.apiportal.config.StreamServiceRetriever.run(StreamServiceRetriever.java:22)

<!--EndFragment-->
</body>
</html>
```

Thank's for help.

**Comment by rathnapandi** [comment]
Hi @GennaroRiccio, 

I don't think of a workaround.  Can you share the CLI command used for testing? CLI does manipulate openapi spec for some cases. 
1.  if we use overridebasepath 
2. if spec contains multiple servers section. 

Thanks
Rathna

**Comment by GennaroRiccio** [comment]
Hi @rathnapandi
The cli command i have used is : 

Export from previous env:
apim api get -s collaudo -name inquiry-contratto-bff -deleteTarget  -o json

Impport to next env:
apim api import -s preprod -c .\api-config.json -a .\inquiry-contratto-bff.json -force

Thanks
Gennaro.

**Comment by GennaroRiccio** [comment]
Yes i send you in email 
Thanks

**Comment by rathnapandi** [comment]
closing the issue as spec has some issues.
