### ISSUE TITLE
Error timeout 

### ISSUE THREAD

**Issue by thiagonogueira-edilabs** [Axway-API-Management-Plus/apim-cli#529]
### APIM-CLI version

1.14.8

### API-Management version

7.7.0-20230830

### Bug description

We are facing an error when calling this endpoint that is being executed via apimcli.
The timeout error.
End point https://apimgr.openapi.tu.teste.internet:443/api/portal/v1.4/proxies/a6192a6f-b852-4e92-bed3-0a7b45c27b6a/applications

logs:

error   23-Dec-2024 12:54:29    [m[m2024-12-23 13:53:46,468 [RestAPICall] DEBUG: Http verb:GET and URI: https://apimgr.openapi.tu.teste.internet:443/api/portal/v1.4/proxies/a6192a6f-b852-4e92-bed3-0a7b45c27b6a/applications
error   23-Dec-2024 12:54:29    [m[1;31m2024-12-23 13:54:16,482 [APIImportApp] ERROR: Cannot read APIs from API-Manager
error   23-Dec-2024 12:54:29                                     | Error cant load subscribes applications from API-Manager.
error   23-Dec-2024 12:54:29    com.axway.apim.lib.error.AppException: Cannot read APIs from API-Manager
error   23-Dec-2024 12:54:29        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPIs(APIManagerAPIAdapter.java:109)
error   23-Dec-2024 12:54:29        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPI(APIManagerAPIAdapter.java:115)
error   23-Dec-2024 12:54:29        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:94)
error   23-Dec-2024 12:54:29        at com.axway.apim.APIImportApp.importAPI(APIImportApp.java:52)
error   23-Dec-2024 12:54:29        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
error   23-Dec-2024 12:54:29        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
error   23-Dec-2024 12:54:29        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
error   23-Dec-2024 12:54:29        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
error   23-Dec-2024 12:54:29        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:133)
error   23-Dec-2024 12:54:29        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:72)
error   23-Dec-2024 12:54:30    Caused by: com.axway.apim.lib.error.AppException: Error cant load subscribes applications from API-Manager.
error   23-Dec-2024 12:54:30        at com.axway.apim.adapter.client.apps.APIMgrAppsAdapter.getAppsSubscribedWithAPI(APIMgrAppsAdapter.java:158)
error   23-Dec-2024 12:54:30        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.addClientApplications(APIManagerAPIAdapter.java:459)
error   23-Dec-2024 12:54:30        at com.axway.apim.adapter.apis.APIManagerAPIAdapter.getAPIs(APIManagerAPIAdapter.java:97)
error   23-Dec-2024 12:54:30        ... 9 more
error   23-Dec-2024 12:54:30    Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
error   23-Dec-2024 12:54:30     at [Source: (String)"<html><body><h1>504 Gateway Time-out</h1>
error   23-Dec-2024 12:54:30    The server didn't respond in time.
error   23-Dec-2024 12:54:30    </body></html>
error   23-Dec-2024 12:54:30    "; line: 1, column: 2]
error   23-Dec-2024 12:54:30        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2477)
error   23-Dec-2024 12:54:30        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:750)
error   23-Dec-2024 12:54:30        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:674)
error   23-Dec-2024 12:54:30        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:2085)
error   23-Dec-2024 12:54:30        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:808)
error   23-Dec-2024 12:54:30        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4912)
error   23-Dec-2024 12:54:30        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4818)
error   23-Dec-2024 12:54:30        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772)
error   23-Dec-2024 12:54:30        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3755)
error   23-Dec-2024 12:54:30        at com.axway.apim.adapter.client.apps.APIMgrAppsAdapter.getAppsSubscribedWithAPI(APIMgrAppsAdapter.java:155)

**Comment by rathnapandi** [comment]
Hi @thiagonogueira-edilabs,

You can increase the timeout via command line parameter timeout. The default value is 30000 milliseconds. 

thanks
Rathna

**Comment by rathnapandi** [comment]
Hi @thiagonogueira-edilabs, 

I am closing the issue. Do let me know if you see any other issues.
