### ISSUE TITLE
[Bug] NullPointerException with -credential option

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apim-cli#57]
**API-Mgr. CLI version**
1.2.1

**API-Manager and Service-Pack Version**
7.6.2 SP4

**Expected behavior**

**Actual behavior**
If I run the following command, a NullPointerException happens.
`apim app get -s <myStage> -credential <myCredential>`

**Log-Output in Debug**
```
----------------------------------------------------------------------------------------
API-Manager CLI: 1.2.1

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: Application - E X P O R T / U T I L S (1.2.1)
----------------------------------------------------------------------------------------
4659   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.6.2 SP4) on: https://...:8075
30036  ERROR ApplicationExportApp| Can't initialize API-Manager API-Representation.
com.axway.apim.lib.errorHandling.AppException: Can't initialize API-Manager API-Representation.
        at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.getApplications(APIMgrAppsAdapter.java:146)
        at com.axway.apim.appexport.ApplicationExportApp.runExport(ApplicationExportApp.java:87)
        at com.axway.apim.appexport.ApplicationExportApp.export(ApplicationExportApp.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: java.lang.NullPointerException
        at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
        at java.util.regex.Matcher.reset(Matcher.java:309)
        at java.util.regex.Matcher.<init>(Matcher.java:229)
        at java.util.regex.Pattern.matcher(Pattern.java:1093)
        at com.axway.apim.adapter.clientApps.ClientAppFilter.filterCredential(ClientAppFilter.java:221)
        at com.axway.apim.adapter.clientApps.ClientAppFilter.filter(ClientAppFilter.java:207)
        at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.getApplications(APIMgrAppsAdapter.java:140)
        ... 8 more
```

**Test case sample**
> Please describe the steps you have done to replicate the issue

**Comment by cwiechmann** [comment]
@jschaefer77, The NPE should normally not happen, as this means, an application has a _Credential_, such as API-Key, OAuth, OAuth (Ext) configured, but this _Credential_ doesn't have an API-Key or Client-ID (means null). 
More detailed: The code causing the NPE is looping over all configured Credentials for an application and checks, if the searched API-Key/Client-ID matches to the application credential. The code assumes, if a credential for an application is given, it must either contain an API-Key or Client-ID. But in your case it is NULL.

Anyway, I'm handling this situation now to avoid the error. Additionally the code is printing the following warning message:
`Inconsistent application: 'Application ABC' found. API-Key/Client-ID is NULL for credential.`
Perhaps a good idea to investigate then if such an application is somehow inconsistent.
