### ISSUE TITLE
Error creating/updating organization

### ISSUE THREAD

**Issue by gcornacchia** [Axway-API-Management-Plus/apim-cli#69]
**API-Mgr. CLI version**
1.2.1

**API-Manager and Service-Pack Version**
7.6.2 SP2

**Expected behavior**
I tried the new feature to import organizations, I tried with a simple json file like this:

{
  "name" : "API Development 6425",
  "description" : "Test Org 6425 test",
  "restricted" : false,
  "enabled" : true,
  "development" : true,
  "createdOn" : 1593700799104
}

I run apim-cli and the organization is correctly created.
Then I modified the description field in json file and I launched again the tool. I expected that the description in my organization is updated and the tool return a success status code.

**Actual behavior**
The strange thing is that the description is effectively updated but the api call (put on organization id) returns a 404 status and so an exception is thrown (see log below). It seems that the PUT call on the specific organization must contain all the fields of the organization (see my ticket to axway support #01190568). 

**Log-Output in Debug**

```
2020-09-04 13:25:41,497 DEBUG              headers| http-outgoing-3 >> PUT /api/portal/v1.3/organizations/44478fbe-4e75-4b38-9b7e-a67ac1198269 HTTP/1.1
2020-09-04 13:25:41,519 DEBUG              headers| http-outgoing-3 >> Content-type: application/json
2020-09-04 13:25:41,524 DEBUG              headers| http-outgoing-3 >> CSRF-Token: A5963742B05663825171817DB3A0DFFCA27B3F13E568BE7395B536FCA7B887AE
2020-09-04 13:25:41,524 DEBUG              headers| http-outgoing-3 >> Content-Length: 145
2020-09-04 13:25:41,543 DEBUG              headers| http-outgoing-3 >> Host: 192.168.2.43:8075
2020-09-04 13:25:41,563 DEBUG              headers| http-outgoing-3 >> Connection: Keep-Alive
2020-09-04 13:25:41,569 DEBUG              headers| http-outgoing-3 >> User-Agent: Apache-HttpClient/4.5.12 (Java/1.8.0_261)
2020-09-04 13:25:41,587 DEBUG              headers| http-outgoing-3 >> Cookie: APIMANAGERSESSION=0c089bd8-4816-4fad-a14c-6480f2ac53b7; APIMANAGERSTATIC=0729a9b5-4a71-45ea-966e-ba9e337da826
2020-09-04 13:25:41,594 DEBUG              headers| http-outgoing-3 >> Accept-Encoding: gzip,deflate
2020-09-04 13:25:41,595 DEBUG                 wire| http-outgoing-3 >> "PUT /api/portal/v1.3/organizations/44478fbe-4e75-4b38-9b7e-a67ac1198269 HTTP/1.1[\r][\n]"
2020-09-04 13:25:41,613 DEBUG                 wire| http-outgoing-3 >> "Content-type: application/json[\r][\n]"
2020-09-04 13:25:41,633 DEBUG                 wire| http-outgoing-3 >> "CSRF-Token: A5963742B05663825171817DB3A0DFFCA27B3F13E568BE7395B536FCA7B887AE[\r][\n]"
2020-09-04 13:25:41,638 DEBUG                 wire| http-outgoing-3 >> "Content-Length: 145[\r][\n]"
2020-09-04 13:25:41,638 DEBUG                 wire| http-outgoing-3 >> "Host: 192.168.2.43:8075[\r][\n]"
2020-09-04 13:25:41,656 DEBUG                 wire| http-outgoing-3 >> "Connection: Keep-Alive[\r][\n]"
2020-09-04 13:25:41,662 DEBUG                 wire| http-outgoing-3 >> "User-Agent: Apache-HttpClient/4.5.12 (Java/1.8.0_261)[\r][\n]"
2020-09-04 13:25:41,662 DEBUG                 wire| http-outgoing-3 >> "Cookie: APIMANAGERSESSION=0c089bd8-4816-4fad-a14c-6480f2ac53b7; APIMANAGERSTATIC=0729a9b5-4a71-45ea-966e-ba9e337da826[\r][\n]"
2020-09-04 13:25:41,680 DEBUG                 wire| http-outgoing-3 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020-09-04 13:25:41,699 DEBUG                 wire| http-outgoing-3 >> "[\r][\n]"
2020-09-04 13:25:41,703 DEBUG                 wire| http-outgoing-3 >> "{"name":"API Development 6425","description":"Test Org 6425 test","restricted":false,"enabled":true,"development":true,"createdOn":1593700799104}"
2020-09-04 13:25:41,861 DEBUG                 wire| http-outgoing-3 << "HTTP/1.1 404 Not Found[\r][\n]"
2020-09-04 13:25:41,861 DEBUG                 wire| http-outgoing-3 << "Date: Fri, 04 Sep 2020 11:25:41 GMT[\r][\n]"
2020-09-04 13:25:41,865 DEBUG                 wire| http-outgoing-3 << "Content-Type: application/json[\r][\n]"
2020-09-04 13:25:41,880 DEBUG                 wire| http-outgoing-3 << "Server: Gateway[\r][\n]"
2020-09-04 13:25:41,884 DEBUG                 wire| http-outgoing-3 << "Connection: close[\r][\n]"
2020-09-04 13:25:41,899 DEBUG                 wire| http-outgoing-3 << "X-CorrelationID: Id-3524525f33039563125ed3af 0[\r][\n]"
2020-09-04 13:25:41,903 DEBUG                 wire| http-outgoing-3 << "[\r][\n]"
2020-09-04 13:25:41,903 DEBUG                 wire| http-outgoing-3 << "{"errors":[{"code":102,"message":"Not Found"}]}"
2020-09-04 13:25:41,922 DEBUG              headers| http-outgoing-3 << HTTP/1.1 404 Not Found
2020-09-04 13:25:41,929 DEBUG              headers| http-outgoing-3 << Date: Fri, 04 Sep 2020 11:25:41 GMT
2020-09-04 13:25:41,930 DEBUG              headers| http-outgoing-3 << Content-Type: application/json
2020-09-04 13:25:41,949 DEBUG              headers| http-outgoing-3 << Server: Gateway
2020-09-04 13:25:41,956 DEBUG              headers| http-outgoing-3 << Connection: close
2020-09-04 13:25:41,974 DEBUG              headers| http-outgoing-3 << X-CorrelationID: Id-3524525f33039563125ed3af 0
2020-09-04 13:25:41,977 DEBUG                 wire| http-outgoing-3 << "end of stream"
2020-09-04 13:25:41,978 DEBUG HttpClientConnection| http-outgoing-3: Close connection
2020-09-04 13:25:41,996 DEBUG       MainClientExec| Connection discarded
2020-09-04 13:25:42,000 DEBUG entConnectionManager| Connection released: [id: 3][route: {s}->https://192.168.2.43:8075][total available: 0; route allocated: 0 of 2; total allocated: 0 of 5]
2020-09-04 13:25:42,018 ERROR rOrganizationAdapter| Error creating/updating organization. Response-Code: 404. Got response: '{"errors":[{"code":102,"message":"Not Found"}]}'
2020-09-04 13:25:42,023 ERROR   OrganizationCLIApp| Error creating/updating organization
com.axway.apim.lib.errorHandling.AppException: Error creating/updating organization
        at com.axway.apim.adapter.apis.APIManagerOrganizationAdapter.createOrUpdateOrganization(APIManagerOrganizationAdapter.java:164)
        at com.axway.apim.adapter.apis.APIManagerOrganizationAdapter.updateOrganization(APIManagerOrganizationAdapter.java:112)
        at com.axway.apim.organization.OrganizationImportManager.replicate(OrganizationImportManager.java:33)
        at com.axway.apim.organization.OrganizationCLIApp.importOrganization(OrganizationCLIApp.java:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.axway.apim.lib.errorHandling.AppException: Error creating/updating organization.
        at com.axway.apim.adapter.apis.APIManagerOrganizationAdapter.createOrUpdateOrganization(APIManagerOrganizationAdapter.java:153)
        ... 9 more
Caused by: com.axway.apim.lib.errorHandling.AppException: Error creating/updating organization. Response-Code: 404
        at com.axway.apim.adapter.apis.APIManagerOrganizationAdapter.createOrUpdateOrganization(APIManagerOrganizationAdapter.java:149)
        ... 9 more
```

**Test case sample**
SEE Expected behaviour

**Comment by cwiechmann** [comment]
Thanks for reporting this bug @gcornacchia. I was able to reproduce it. I extended the integration test and fixed the root cause. The fix will be part of the 1.2.2 release.
