### ISSUE TITLE
Swagger Promote publishing failure (Response: 'HTTP/1.1 201 Created')

### ISSUE THREAD

**Issue by niklasbeck** [Axway-API-Management-Plus/apim-cli#75]
**API-Mgr. CLI version**
> Please make sure to use the latest available version before reporting a bug.
Swagger Promote 1.6.7-1

**API-Manager and Service-Pack Version**
7.5.3 SP12 and 7.7 SP2 (error appears on both versions)

**Expected behavior**
Publish the new API and delete the old one on the same path

**Actual behavior**
The new API gets published, but then an error interrupts the process and the rollback is not performed properly.
Now, the new and the old API are both published, resulting in path conflicts.

**Log-Output in Debug**
```
------------------------------------------------------------------------
API-Manager Promote: 1.6.7-1 - I M P O R T

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote
------------------------------------------------------------------------

0      INFO  nvironmentProperties| Loaded environment properties from file: env.properties
3804   INFO     APIManagerAdapter| API-Manager version is: 7.7.20200730
4934   INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: 'my-cool-api-definition.json' (relative path)
4947   INFO      APISpecification| Used the configured backendBasepath: 'https://path-to.backend.sample' to adjust the Swagger definition.
4953   INFO  IImportConfigAdapter| Handling configured client-applications.
7191   INFO  IImportConfigAdapter| Found existing application: 'App1' (null) based on given name 'App1'
7195   INFO               Proxies| Sending request to find existing APIs: https://localhost:8075/api/portal/v1.3/proxies?field=path&op=eq&value=%2Fapi%2Fcoolpath%2Fv1
8225   INFO               Proxies| Found existing API on path: '/api/coolpath/v1' (published) (ID: 'aa71612c-e0ba-4719-bba0-6f75ea25f80c')
8225   INFO               Proxies| Found: 1 exposed API(s)
46849  INFO      APISpecification| Detected API-Definition-Filesizes: API-Manager: 7129 vs. Import: 7139
46859  INFO      APIImportManager| Strategy: Going to update existing API: My Cool API (Version: 1.0.0)
46860  INFO      APIImportManager| Recognized the following changes. Potentially Breaking: [APIDefinition] plus Non-Breaking: [applications]
46860  INFO      APIImportManager| Strategy: Apply breaking changes: [APIDefinition] & and Non-Breaking: [applications], for PUBLISHED API by recreating it!
46867  INFO     APIManagerAdapter| Importing backend API (Swagger/WSDL Import)
47285  INFO     APIManagerAdapter| Create API-Proxy (Front-End API)
87849  INFO     APIManagerAdapter| Updating Frontend-API (Proxy) for the following properties: securityProfiles authenticationProfiles outboundProfiles corsProfiles path name
90196  ERROR          RestAPICall| Response: 'HTTP/1.1 201 Created'
90199  INFO        RollbackAction| Rollback FE-API: 'My Cool API' (ID: '937d58dd-c251-4bf2-8727-1ac3656f8e7b')
90568  ERROR       RollbackAction| Error while deleteting FE-API: '937d58dd-c251-4bf2-8727-1ac3656f8e7b' to roll it back: '{"errors":[{"code":403,"message":"Cannot delete a published API"}]}'
90956  ERROR       RollbackAction| Error while deleteting BE-API: '9b50a297-0e07-4f82-b7c1-3915b85fd076' to roll it back: '{"errors":[{"code":403,"message":"Cannot delete an API that has been virtualized."}]}'
90959  INFO               Proxies| Sending request to find existing APIs: https://localhost:8075/api/portal/v1.3/apirepo?field=name&op=like&value=My+Cool+API+HTTP&field=createdOn&op=gt&value=1599636703203
92797  INFO               Proxies| No existing API found based on filter: [ filter=[field=name, op=like, value=My Cool API HTTP, field=createdOn, op=gt, value=1599636703203]]
92798  INFO       RollbackHandler| Rolled back: '[Frontend-API: false, Backend-API: true]'
92799  ERROR                  App| The status change from: 'unpublished' to 'published' is not possible!
com.axway.apim.lib.errorHandling.AppException: The status change from: 'unpublished' to 'published' is not possible!
        at com.axway.apim.apiimport.actions.tasks.UpdateAPIStatus.execute(UpdateAPIStatus.java:177)
        at com.axway.apim.apiimport.actions.tasks.UpdateAPIStatus.execute(UpdateAPIStatus.java:81)
        at com.axway.apim.apiimport.actions.CreateNewAPI.execute(CreateNewAPI.java:95)
        at com.axway.apim.apiimport.actions.RecreateToUpdateAPI.execute(RecreateToUpdateAPI.java:41)
        at com.axway.apim.apiimport.APIImportManager.applyChanges(APIImportManager.java:77)
        at com.axway.apim.App.run(App.java:247)
        at com.axway.apim.App.main(App.java:53)
Caused by: com.axway.apim.lib.errorHandling.AppException: Unable to parse HTTP-Response
        at com.axway.apim.lib.utils.rest.RestAPICall.parseResponse(RestAPICall.java:73)
        at com.axway.apim.lib.utils.rest.POSTRequest.execute(POSTRequest.java:30)
        at com.axway.apim.apiimport.actions.tasks.UpdateAPIStatus.execute(UpdateAPIStatus.java:171)
        ... 6 more
Caused by: com.axway.apim.lib.errorHandling.AppException: Unable to parse response
        at com.axway.apim.apiimport.actions.tasks.UpdateAPIStatus.parseResponse(UpdateAPIStatus.java:200)
        at com.axway.apim.lib.utils.rest.RestAPICall.parseResponse(RestAPICall.java:65)
        ... 8 more
Caused by: java.lang.NullPointerException
        at com.axway.apim.apiimport.actions.tasks.UpdateAPIStatus.parseResponse(UpdateAPIStatus.java:193)
        ... 9 more
```

**Comment by cwiechmann** [comment]
Thanks @niklasbeck, for reporting this issue. I have a few questions:
- can you please validate if the error also happens with the APIM-CLI?
  - `apim api import -h <host> -u <user> -p <passwd> - c <your-config>`
- can you please enable Traffic-Monitoring for the API-Manager REST-API (8075)
  - How this works is described here: https://docs.axway.com/bundle/APIGateway_762_AdministratorGuide_allOS_en_HTML5/page/Content/AdminGuideTopics/logging.htm#Configur2
  - When enabled, please re-run and we should see, why the error happens
- does this happen for a specific API?
  - If yes, can you send me that API-Specification and API-Config-File via Email?

**Comment by cwiechmann** [comment]
Going to close this issue now, as the APIM-CLI is now optimized to be plugged into a Maven-Plugin or any other Java-Program. Everybody, who is still using Swagger-Promote should migrate to the APIM-CLI.
