### ISSUE TITLE
Retrieving API list with ultra param results in NullPointerException

### ISSUE THREAD

**Issue by mpentzek** [Axway-API-Management-Plus/apim-cli#80]
**API-Mgr. CLI version**
v1.2.2 & 1.3.0-SNAPSHOT

**API-Manager and Service-Pack Version**
7.7.20200730

**Expected behavior**
The API list with all columns should be shown

**Actual behavior**
Retrieving the list results in NullPointerException

**Log-Output in Debug**
```
c:\Demo\Presales\APIs\APIs>apim api get -s api-env -ultra
----------------------------------------------------------------------------------------
API-Manager CLI: 1.3.0-SNAPSHOT

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: API - E X P O R T / U T I L S (1.3.0-SNAPSHOT)
----------------------------------------------------------------------------------------
1721   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20200730) on: https://api-env:8075
Loading 6 APIs [********--] 80%
2065   INFO          APIExportApp| 6 API(s) selected.
2075   ERROR         APIExportApp|
java.lang.NullPointerException
        at com.axway.apim.api.export.impl.APIResultHandler.getUsedSecurity(APIResultHandler.java:124)
        at com.axway.apim.api.export.impl.ConsoleAPIExporter.lambda$printUltra$21(ConsoleAPIExporter.java:80)
        at com.github.freva.asciitable.ColumnData.getCellValue(ColumnData.java:15)
        at com.github.freva.asciitable.AsciiTable.lambda$null$0(AsciiTable.java:40)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
        at java.util.stream.ReferencePipeline.toArray(Unknown Source)
        at com.github.freva.asciitable.AsciiTable.lambda$getTable$2(AsciiTable.java:41)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
        at java.util.stream.ReferencePipeline.toArray(Unknown Source)
        at com.github.freva.asciitable.AsciiTable.getTable(AsciiTable.java:42)
        at com.axway.apim.api.export.impl.ConsoleAPIExporter.printUltra(ConsoleAPIExporter.java:72)
        at com.axway.apim.api.export.impl.ConsoleAPIExporter.execute(ConsoleAPIExporter.java:40)
        at com.axway.apim.APIExportApp.execute(APIExportApp.java:138)
        at com.axway.apim.APIExportApp.export(APIExportApp.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)

```

**Test case sample**
The error occurs if the attached API (exported with APIM CLI) is available in the API Manager:

[PetstoreAPIHttps.zip](https://github.com/Axway-API-Management-Plus/apim-cli/files/5257882/PetstoreAPIHttps.zip)

**Comment by cwiechmann** [comment]
Thanks for reporting @mpentzek. Also an easy fix which will be included in the next release. Also I made the Console-View a bit nice, using Clear-Text names for the security devices instead of the internal key.
