### ISSUE TITLE
Change API fails with a ClassCastException

### ISSUE THREAD

**Issue by cwiechmann** [Axway-API-Management-Plus/apim-cli#85]
**API-Mgr. CLI version**
1.2.2

**API-Manager and Service-Pack Version**
7.7-July

**Expected behavior**
The backend URL is changed

**Actual behavior**
`java.lang.ClassCastException: com.ax....ib.APIChangeParams cannot be cast to com.ax....b.APIImportParams`

**Log-Output in Debug**
```
apim api change -s api-env -id bd246fb0-98c8-4f2b-9db6-e21cd9f758ed -newBackend https://my.newhost.com/das -force
----------------------------------------------------------------------------------------
API-Manager CLI: 1.2.2

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: API - E X P O R T / U T I L S (1.3.0-SNAPSHOT)
----------------------------------------------------------------------------------------
2163   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20200730) on: https://api-env:8075
2523   INFO          APIExportApp| 1 API(s) selected.
2523   INFO      APIResultHandler| 1 selected to change.
2630   INFO      APIResultHandler| Planned changes for API: 'Airports API': [customProperties, serviceProfiles]
Force flag given to change: 1 API(s)
2636   INFO      APIResultHandler| Apply changes for API: 'Airports API'
2639   ERROR     APIResultHandler| Error applying changes for API: Airports API
java.lang.ClassCastException: com.axway.apim.api.export.lib.APIChangeParams cannot be cast to com.axway.apim.apiimport.lib.APIImportParams
        at com.axway.apim.apiimport.lib.APIImportParams.getInstance(APIImportParams.java:16)
        at com.axway.apim.apiimport.APIImportManager.applyChanges(APIImportManager.java:32)
        at com.axway.apim.api.export.impl.APIChangeHandler.execute(APIChangeHandler.java:78)
        at com.axway.apim.APIExportApp.execute(APIExportApp.java:154)
        at com.axway.apim.APIExportApp.change(APIExportApp.java:130)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
```

**Comment by giancolli** [comment]
Hi, just want to notify that I still have this issue on CLI 1.3.3 and API Manager 7.7 - July.

Have you any useful advice/news about that, if needed I can provide more informations.

**Comment by cwiechmann** [comment]
@giancolli, Can you please create a new issue and attach the log information you get. Very likely, it's a different error.
