### ISSUE TITLE
Problem with accent in the description of an application configuration 

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apim-cli#88]
**API-Mgr. CLI version**
1.2.3

**API-Manager and Service-Pack Version**
7.7.20200730

**Expected behavior**
Having a config file such as : 
{
  "name": "Test API Specifique",
  "description": "Accès aux API spécifiques",
  ...
  ... 
}

**Actual behavior**
Having accents in the description return this error : 
 335    ERROR    APIMgrAppsAdapter| Error creating/updating application. Response-Code: 400. Got response: '{"errors":[{"code":400,"message":"Invalid JSON format"}]}'

**Log-Output **
 335    ERROR    APIMgrAppsAdapter| Error creating/updating application. Response-Code: 400. Got response: '{"errors":[{"code":400,"message":"Invalid JSON format"}]}'
339    ERROR ApplicationImportApp| Error creating/updating application
com.axway.apim.lib.errorHandling.AppException: Error creating/updating application
        at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.createOrUpdateApplication(APIMgrAppsAdapter.java:378)
        at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.createApplication(APIMgrAppsAdapter.java:318)
        at com.axway.apim.appimport.ClientAppImportManager.replicate(ClientAppImportManager.java:35)
        at com.axway.apim.appimport.ClientApplicationImportApp.importApp(ClientApplicationImportApp.java:72)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.axway.apim.lib.errorHandling.AppException: Error creating/updating application.
        at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.createOrUpdateApplication(APIMgrAppsAdapter.java:362)
        ... 9 more
Caused by: com.axway.apim.lib.errorHandling.AppException: Error creating/updating application. Response-Code: 400
        at com.axway.apim.adapter.clientApps.APIMgrAppsAdapter.createOrUpdateApplication(APIMgrAppsAdapter.java:358)
        ... 9 more

**Test case sample**
> Please describe the steps you have done to replicate the issue
use the sample in the wiki for application or just add a description with an accent and import it.

**Comment by cwiechmann** [comment]
Thanks for reporting @Rennaud. Will be fixed as well with the next release.
