### ISSUE TITLE
Problem exporting API to json

### ISSUE THREAD

**Issue by niklasbeck** [Axway-API-Management-Plus/apim-cli#90]
**API-Mgr. CLI version**
apim-cli-1.2.3

**API-Manager and Service-Pack Version**
7.7.20200730

**Expected behavior**
Export the given API and create the json-files and certs

**Actual behavior**
Despite the tool throwing an error, the export folder gets created, but the api-definition, as well as the api-config is incomplete (e.g. missing apps and orgs and closing curly brackets). Also no certs are created.

**Log-Output in Debug**
```
----------------------------------------------------------------------------------------
API-Manager CLI: 1.2.3

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apim-cli
----------------------------------------------------------------------------------------
Module: API - E X P O R T / U T I L S (1.2.3)
----------------------------------------------------------------------------------------
1704   INFO     APIManagerAdapter| Successfully connected to API-Manager (7.7.20200730) on: https://localhost:8075
13766  INFO          APIExportApp| 1 API(s) selected.
13769  INFO       JsonAPIExporter| Going to export API into folder: .\myapi-v4
13938  ERROR      JsonAPIExporter| Can't export API: Can't create API-Configuration file for API: 'MyAPI V4' exposed on path: '/myapi/v4'. Please check in API-Manager UI the API is valid.
com.axway.apim.lib.errorHandling.AppException: Can't create API-Configuration file for API: 'MyAPI V4' exposed on path: '/myapi/v4'.
        at com.axway.apim.api.export.impl.JsonAPIExporter.saveAPILocally(JsonAPIExporter.java:116)
        at com.axway.apim.api.export.impl.JsonAPIExporter.execute(JsonAPIExporter.java:52)
        at com.axway.apim.APIExportApp.execute(APIExportApp.java:154)
        at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:67)
        at com.axway.apim.APIExportApp.exportAPI(APIExportApp.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.axway.apim.cli.APIManagerCLI.run(APIManagerCLI.java:142)
        at com.axway.apim.cli.APIManagerCLI.main(APIManagerCLI.java:78)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.axway.apim.api.export.ExportAPI["customProperties"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
        at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3906)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3160)
        at com.axway.apim.api.export.impl.JsonAPIExporter.saveAPILocally(JsonAPIExporter.java:114)
        ... 10 more
Caused by: java.lang.NullPointerException
        at com.axway.apim.api.export.ExportAPI.getCustomProperties(ExportAPI.java:212)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
        ... 16 more`
```
**Test case sample**
apim api get -a /myapi/v4 -o json

***Interestingly, I also tried to export the API with Swagger Promote 1.6.7-1 and it works fine.***

If needed, I can get in touch with you via mail to provide you the details of the real API that is causing this error.

**Comment by cwiechmann** [comment]
@niklasbeck, has the API custom properties configured when you check at the UI? 

The code causing the NPE is the following:
```java
public Map<String, String> getCustomProperties() {
	if(this.actualAPIProxy.getCustomProperties()!=null && this.actualAPIProxy.getCustomProperties().size()==0) return null;
	Iterator<String> it = this.actualAPIProxy.getCustomProperties().values().iterator(); // <<<< NPE happens here
	boolean propertyFound = false;
	while(it.hasNext()) {
		String propValue = it.next();
		if(propValue!=null) {
			propertyFound = true;
			break;
		}
	}
	if(!propertyFound) return null; // If no property is declared for this API return null
	return this.actualAPIProxy.getCustomProperties();
}
```
It's already checked that `getCustomProperties()` is not null (which is a Map). `value()` is executed on the returned Map is therefore the only remaining thing to be null. I haven't expected that, this can ever be `null`. 

Therefore, please confirm how the API is configured. Just to make sure and I would like to replicate that issue first.

**Comment by niklasbeck** [comment]
The API has no custom properties configured. 

However, the only thing that may be interesting and/or different from most APIs is the following:
It has a custom security Profile, which is used by Inbound Per-Method Override for 4 methods.
Additionally, those 4 methods also have Outbound Per-Method Overrides with a custom Request Policy.

Other than that, i dont see any abnormality with this API.

**Comment by cwiechmann** [comment]
Thanks for the info,
I think the best would be, if you send me the .dat export file. This gives me an exact copy of the API how it is in your API-Manager (July-Release is perfect). With that it should be easy to re-produce that issue.

**Comment by cwiechmann** [comment]
Hi @niklasbeck, I have added an additional `null` check to avoid the NPE. As the custom-properties are not set anyway that should be okay. Can you please test with this this version:
[axway-apimcli-1.2.4-SNAPSHOT.zip](https://github.com/Axway-API-Management-Plus/apim-cli/files/5317624/axway-apimcli-1.2.4-SNAPSHOT.zip)

**Comment by cwiechmann** [comment]
@niklasbeck, I expect this issue to be fixed and I'm going to close this issue now. The fix will be finally delivered with the next release 1.2.4
